### ISSUE TITLE
Небольшое исправление в RadiusFlash.

### ISSUE THREAD

**Issue by Chuvi-w** [s1lentq/ReGameDLL_CS#1]
Нет желания делать PullRequest ради одной переменной.

В общем, там где идёт поиск тех, кто за игроком наблюдает, флэшить нужно не бедного игрока многократно, а наблюдателей.
То есть вместо
UTIL_ScreenFade(pPlayer, Vector(255, 255, 255), fadeTime, fadeHold, alpha, 0);
должно быть
UTIL_ScreenFade(pObserver, Vector(255, 255, 255), fadeTime, fadeHold, alpha, 0);

**Comment by s1lentq** [comment]
Спасибо.
Поправлю в следующем коммите.

**Comment by coolmans** [comment]
будут сборки делаться, или только самим собирать и почему проект редко выпускает новые версии?

**Comment by latinas** [comment]
Как самостоятельный проект мод еще не работоспособен, он работает в связке с оригинальным filesystem_stdio.dll. Почитайте лучше wiki данного репозитория
