### ISSUE TITLE
Player Spawn kill still prevalent!

### ISSUE THREAD

**Issue by souvikdas95** [s1lentq/ReGameDLL_CS#100]
I have tested it in a 32 player 24x7 full server with latest ReHLDS & ReGameDLL. The spawn kill issue still occurs in certain maps like "css_mirage", "de_inferno", etc. Moreover, I have got reports from some server admins that, sometimes when playing maps other than de_dust2, the Server crashes within 1-2 seconds of spawn.

**Comment by In-line** [comment]
Just add more spawns
