### ISSUE TITLE
server crash!

### ISSUE THREAD

**Issue by Escap3d** [s1lentq/ReGameDLL_CS#1017]
https://www.mediafire.com/file/gxqnaryqxdkqntv/hlds_crash_20240928_125624.mdmp/file

After server join then server was crash there is dump file any check it and fix it plzzz

**Comment by s1lentq** [comment]
Please refer to this AMXX [documentation](https://wiki.alliedmods.net/AMX_Mod_X_1.9_Release_Notes#Upgrading)
It states that ReGameDLL is supported starting from version 1.9

amxmodx cstrike module 1.8.2 does not support ReGameDLL, remove this module or consider updating to the recent version

**Comment by Escap3d** [comment]
> Please refer to this AMXX [documentation](https://wiki.alliedmods.net/AMX_Mod_X_1.9_Release_Notes#General) It states that ReGameDLL is supported starting from version 1.9
> 
> amxmodx cstrike module 1.8.2 does not support ReGameDLL, remove this module or consider updating to the recent version

We all use the AutoMix AMX plugin, but we don't have its source code, so we can't compile it. That's why we use version 1.8.2. When we try to use the latest version, it crashes.

**Comment by Nord1cWarr1or** [comment]
It's not regamedll's problem
