### ISSUE TITLE
How to use with AMXMODX?

### ISSUE THREAD

**Issue by dummbummboy** [s1lentq/ReGameDLL_CS#1021]
Since some admin closed my last qustion without really answering. I ask again.

When I've installed metamod and amxmodx I've had to change this line from
`gamedll "dlls\mp.dll"`
to
`gamedll "addons\metamod\dlls\metamod.dll"`

Since I've replaced the mp.dll from here, I changed it back to the original line. But metamod and amxmodx stop working if I do this. Can someone help me? 

_btw @ admin: I followed the manual installation instructions, don't post me this link again -.-_

**Comment by Nord1cWarr1or** [comment]
> Since I've replaced the mp.dll from here, I changed it back to the original line.

You don't have to do that.

**Comment by wopox1337** [comment]
ref https://github.com/s1lentq/ReGameDLL_CS/issues/1020
