### ISSUE TITLE
mp_forcerespawn

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#106]
mp_forcerespawn "5" 
i used this but player are respawning before 5 secs.

**Comment by ish12321** [comment]
Is there any other unit used and not seconds ?

**Comment by theAsmodai** [comment]
Actually it's boolean.

**Comment by ish12321** [comment]
o. O ? 
please can it not be the way that we mention after how many secs player shouldd respawn ?

**Comment by ish12321** [comment]
0 = respawn immediate
-1 = no respawn

**Comment by s1lentq** [comment]
[read it](https://github.com/s1lentq/ReGameDLL_CS#configuration-cvars).

`0` disabled
`>0.00001` time delay to respawn

**Comment by ish12321** [comment]
ok ...
please if possible try to fix it as soon as possible :'(

**Comment by ish12321** [comment]
Bump

**Comment by ish12321** [comment]
BUMP

**Comment by ish12321** [comment]
Bump.

**Comment by In-line** [comment]
Same as #121
