### ISSUE TITLE
abs UB on integral types (negate UB) and float->int UB

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [s1lentq/ReGameDLL_CS#107]
@spark512 have found some bug: the server crashes with emit sound error (bad volume) on deathrun_clouds_v2 when you activating the first trap. This trap activates func_breakable which has `9999999999999999999` HP. So, the problem is located in [CBreakable::Die](https://github.com/s1lentq/ReGameDLL_CS/blob/7c9d59101b67525a35b0b3a31e17159ab5d42fbd/regamedll/dlls/func_break.cpp#L679):
```C++
fvol = RANDOM_FLOAT(0.85f, 1.0f) + (Q_abs(int(pev->health)) / 100.0f);
```
There we have 2 kinds of UB:

- float->int conversion. If the value cannot fit into the destination type, the behavior is undefined. When converting `9999999999999999999` from float to int I get `-2147483648` on my platform.
- Taking absolute value from INT_MIN (if INT_MIN < -INT_MAX). The behavior is undefined if the result cannot be represented by the return type (negate operation has the same problem). When taking absolute value for `-2147483648` I get `-2147483648` on my platform.

Then we get negative `fvol` and crash...

So, I don't know about other places in code, but this UB should be checked and fixed in all the code. This not only refers to ReGameDLL, but to ReHLDS and other projects.

**Comment by spark512** [comment]
`Deathrun: Restarting. Reason: Fatal error - EMIT_SOUND: volume = 1073741824`

So that number is basically a garbage value due to improper float -> int conversion..

**Comment by WPMGPRoSToTeMa** [comment]
@spark512 nope, float values are pushed into another stack, so it prints fully garbage, not converted float.

**Comment by spark512** [comment]
Any progress on this?

Can we just clamp the value taken from pev->health? That will prevent the overflow and will prevent a negative value being passed.

Also, why is the health being transformed to an int? We are working with floats, fvol is a float..

**Comment by IgnacioFDM** [comment]
It's probably best to clamp pev->health of map entities on spawn. I might be wrong (haven't really checked), but there may be some HP to int casts client side or in netcode too, as happens with player health.

**Comment by WPMGPRoSToTeMa** [comment]
@IgnacioFDM entity health is not transmitted to client.

**Comment by spark512** [comment]
pev->health is being retrieved here, and it's a float. Why not just check abs on float? There are plenty of code snippets for that.

Or we can just get it ourselves if we check pev_health > 0 || pev_health < 0..
