### ISSUE TITLE
Weird code in CHalfLifeMultiplay::StackVIPQueue(void)

### ISSUE THREAD

**Issue by IgnacioFDM** [s1lentq/ReGameDLL_CS#11]
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/multiplay_gamerules.cpp#L2198-L2218

Is there some black magic there or is it just a bug? (Notice the i - 1 overruns)

**Comment by s1lentq** [comment]
I previously did wrong.
Thank you for reminding me.
