### ISSUE TITLE
mp_auto_join_team breaks EngFunc_RunPlayerMove

### ISSUE THREAD

**Issue by Kushfield** [s1lentq/ReGameDLL_CS#110]
I've been trying to figure out why my bots are no longer working after installing ReGameDLL for quite a while now. Now, I finally narrowed it down to EngFunc_RunPlayerMove and mp_auto_join_team. If mp_auto_join_team is enabled, as soon as EngFunc_RunPlayerMove is ran on a bot, the bot will rejoin the team and become unresponsive.

**Comment by In-line** [comment]
Closing as non active. Create new issue if problem persists.
