### ISSUE TITLE
mp_forcerespawn respawn spectators

### ISSUE THREAD

**Issue by TheRedShoko** [s1lentq/ReGameDLL_CS#111]
If you transfer yourself in spectator team using AMXX plugin you will get respawned as you can see on the screenshot http://steamcommunity.com/sharedfiles/filedetails/?id=861168532 
But It wont happen if you transfer yourself using team menu (chooseteam)

**Comment by SmirnoffBG** [comment]
I had the same issue and it seams that when you set the dead flag to like DEAD_DYING or DEAD_DEAD
It just doesn't set. I get immediately respawned no mater whats the cvar's value.

**Comment by In-line** [comment]
How to reproduce issue.
1) Join server
2) Join `CT` or `TT`
3) `mp_forcerespawn 1`
4) Transfer yourself using [amxmodx](https://github.com/alliedmodders/amxmodx/blob/fa3d28872ebf80d497d6464d7df8681cbd27b398/plugins/plmenu.sma#L843-L854) 1.8.3 amx_teammenu command to spectators
5) Wait ~1 second.
6) Yes! You was respawned as spectator.

But if you set `mp_forcerespawn` high enough (for example 15) you will not face this issue. It seems that, `(m_afPhysicsFlags & PFLAG_OBSERVER) != 0` only when `StartObserver()` was called (see `StartDeathCam()` [here](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L3648) ). Proposed fix is to remove `(m_afPhysicsFlags & PFLAG_OBSERVER)` check [here.](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L3682) and [here](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L9734)

Thx to WaLkZ for additional information.

**Comment by In-line** [comment]
How to reproduce issue.
1) Join server
2) Join `CT` or `TT`
3) `mp_forcerespawn 1`
4) Transfer yourself using [amxmodx](https://github.com/alliedmodders/amxmodx/blob/fa3d28872ebf80d497d6464d7df8681cbd27b398/plugins/plmenu.sma#L843-L854) 1.8.3 amx_teammenu command to spectators
5) Wait ~1 second.
6) Yes! You was respawned as spectator.

But if you set `mp_forcerespawn` high enough (for example 15) you will not face this issue. It seems that, `(m_afPhysicsFlags & PFLAG_OBSERVER) != 0` only when `StartObserver()` was called (see `StartDeathCam()` [here](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L3648) ). Proposed fix (#160) is to remove `(m_afPhysicsFlags & PFLAG_OBSERVER)` check [here.](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L3682) and [here](https://github.com/s1lentq/ReGameDLL_CS/blob/6d613fc9f072318bce4b44a2c8f3183358688ce7/regamedll/dlls/player.cpp#L9734)

Thx to WaLkZ for additional information.
