### ISSUE TITLE
Add to set the owner of the entity env_explosion

### ISSUE THREAD

**Issue by Sylvert0** [s1lentq/ReGameDLL_CS#120]
Something like m_hOwnerEntity in sourcemod

**Comment by In-line** [comment]
There is already `pEntity->pev->owner`
https://github.com/s1lentq/ReGameDLL_CS/blob/64ccba41cc6c8ed7d84a666fe7ffc9f9c1c91aa5/regamedll/dlls/cbase.cpp#L897
