### ISSUE TITLE
mp_forcerespawn bug

### ISSUE THREAD

**Issue by ghost** [s1lentq/ReGameDLL_CS#121]
Обнаружил баг с mp_forcerespawn если ставим напр. 12 сек гамедлл спавнить нас раньше.
Пока я решил исключив код (добавив #ifndef REGAMEDLL_ADD) здесь 

https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/player.cpp#L3679

**Comment by In-line** [comment]
It was fixed a long time ago.
