### ISSUE TITLE
AbstractHookChainRegistry::addhook : The same handler cant be used twice on the hookchain error

### ISSUE THREAD

**Issue by omertelli** [s1lentq/ReGameDLL_CS#124]
some times i got this error, anybody have any idea ?

AbstractHookChainRegistry::addhook : The same handler cant be used twice on the hookchain

version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
ReHLDS version: 3.0.0.484-dev
Build date: 22:21:19 Mar  1 2017 (1054)
Build from: https://github.com/dreamstalker/rehlds/commit/f8e2b50

game version
ReGameDLL version: 5.2.0.178-dev
Build date: 20:09:43 Mar  1 2017
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/6186ae5

**Comment by theAsmodai** [comment]
Please post output of `meta list`

**Comment by omertelli** [comment]
description      stat pend  file              vers      src   load  unlod
 [ 1] Reunion          RUN   -    reunion_mm.dll    v0.1.75   ini   Start Never
 [ 2] ReAuthCheck      RUN   -    reauthcheck_mm.d  v0.1.5    ini   Start Never
 [ 3] AMX Mod X  RUN   -    amxmodx_mm.dll    v1.8.3-d  ini   Start ANY
 [ 4] Rechecker        RUN   -    rechecker_mm.dll  v2.3      ini   Chlvl ANY
 [ 5] Revoice          RUN   -    revoice_mm.dll    v0.1.26   ini   Start Never
 [ 6] WHBlocker        RUN   -    whblocker_mm.dll  v1.5.672  ini   Chlvl ANY
 [ 7] SQLite           RUN   -    sqlite_amxx.dll   v1.8.3-d  pl3   ANY   ANY
 [ 8] Fun              RUN   -    fun_amxx.dll      v1.8.3-d  pl3   ANY   ANY
 [ 9] Engine           RUN   -    engine_amxx.dll   v1.8.3-d  pl3   ANY   ANY
 [10] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.8.3-d  pl3   ANY   ANY
 [11] CStrike          RUN   -    cstrike_amxx.dll  v1.8.3-d  pl3   ANY   ANY
 [12] CSX              RUN   -    csx_amxx.dll      v1.8.3-d  pl3   ANY   ANY
 [13] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl3   ANY   ANY
 [14] ReAPI            RUN   -    reapi_amxx.dll    v5.1.0.1  pl3   ANY   Never
 [15] ReAimDetector    RUN   -    reaimdetector_am  v0.1.3    pl3   ANY   Never

**Comment by In-line** [comment]
Closing as non active.
