### ISSUE TITLE
Does ReGameDLL_CS (or ReHlds) bugfixed fix an old accuracy bug ?

### ISSUE THREAD

**Issue by Freeman-AM** [s1lentq/ReGameDLL_CS#138]
Here is the bug i mention :
https://forums.alliedmods.net/showthread.php?p=1549133?p=1549133
Is it fixed in ReGameDLL_CS (or ReHlds) or do I still need the plugin to fix it ?
Thanks

**Comment by WPMGPRoSToTeMa** [comment]
Nope. This is the duplicate of https://github.com/s1lentq/ReGameDLL_CS/issues/88.
