### ISSUE TITLE
[Bug] mp.dll failed to load for listenserver.

### ISSUE THREAD

**Issue by wbyokomo** [s1lentq/ReGameDLL_CS#15]
Hi,
I tried to use this mp.dll on my cs16 game and create a new game but it do nothing instead of give me this error message on console.

Console message:
LoadLibrary failed on e:\steam\steamapps\common\half-life\cstrike\dlls\mp.dll (1114)
Host_Error: Couldn't get DLL API from e:\steam\steamapps\common\half-life\cstrike\dlls\mp.dll!

I can only load mp.dll by using hlds.exe with params:
start hlds.exe -console -game cstrike -maxplayers 16 -map de_dust2

The '-game cstrike' is play the most important part, if i don't add that param.. the same error will happen.

**Comment by jonatan1024** [comment]
Thats caused by return(FALSE) on line 40 in main_mp.cpp

Change #ifdef _WIN32 to #if 0 or delete the whole preprocessor-if testing related block.
