### ISSUE TITLE
Warning ammo index mismatch

### ISSUE THREAD

**Issue by fl0werD** [s1lentq/ReGameDLL_CS#161]
Периодически шлется вот такая штука в консоль. В чем может быть проблема?

Warning: ammo '556Nato' index mismatch; expected 4, real 3
Warning: ammo 'buckshot' index mismatch; expected 5, real 4
Warning: ammo '45acp' index mismatch; expected 6, real 5
Warning: ammo '57mm' index mismatch; expected 7, real 6
Warning: ammo '50AE' index mismatch; expected 8, real 7
Warning: ammo '357SIG' index mismatch; expected 9, real 8
Warning: ammo '9mm' index mismatch; expected 10, real 9
Warning: ammo 'Flashbang' index mismatch; expected 11, real 10
Warning: ammo 'HEGrenade' index mismatch; expected 12, real 11
Warning: ammo 'SmokeGrenade' index mismatch; expected 13, real 12
Warning: ammo 'C4' index mismatch; expected 14, real 13

Откуда шлется: https://github.com/s1lentq/ReGameDLL_CS/blob/7c9d59101b67525a35b0b3a31e17159ab5d42fbd/regamedll/dlls/weapons.cpp#L262

**Comment by In-line** [comment]
Closing as non active. Create new issue if problem persists. I guess this was fixed a long time ago.
