### ISSUE TITLE
de_dust2 texture abuse fix

### ISSUE THREAD

**Issue by stambeto2006** [s1lentq/ReGameDLL_CS#168]
Will you fix this bug with texture on de_dust2 without using plugins.
https://www.youtube.com/watch?v=hr_R83ZqsI0
More info: https://forums.alliedmods.net/showthread.php?t=179340

**Comment by In-line** [comment]
Map issue shouldn't be fixed by gamedll

**Comment by WPMGPRoSToTeMa** [comment]
This is more like client engine bug.
> Map issue shouldn't be fixed by gamedll

But regamedll can contain fixed maps.

**Comment by stambeto2006** [comment]
I agree with @WPMGPRoSToTeMa .
