### ISSUE TITLE
Round Terminator (request)

### ISSUE THREAD

**Issue by csroger** [s1lentq/ReGameDLL_CS#170]
Will you be incorporating the future from Arkshine's plugin Round Terminator which requires orpheu. It has commands to end rounds by ct win/t win or round draw.

**Comment by Mistrick** [comment]
Already exists.
https://github.com/s1lentq/reapi/blob/master/reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc#L239-L250

**Comment by Vaqtincha** [comment]
mp_forcewin
