### ISSUE TITLE
"The bomb has been defused" Broken Sound

### ISSUE THREAD

**Issue by Freeman-AM** [s1lentq/ReGameDLL_CS#181]
'the bomb has been defused' sound used to work in old versions of CS, but in CS 1.6 its blocked by 'cts win'.

Is it possible to fix it in the bugfixed version of the DLL ?

Here is an amxmodx plugin fixing that : 
https://forums.alliedmods.net/showthread.php?p=883102

**Comment by s1lentq** [comment]
Fixes 25d2e6ce9e95aa42a72bd640075f076ab30043c9

**Comment by fred0r** [comment]
Could you please make this behavior configurable ?

**Comment by s1lentq** [comment]
Why do you want? This changes was broken something?

**Comment by fred0r** [comment]
A lot of player are used to the 'faulty behavior' since it exists since 1.6 came out.

**Comment by fred0r** [comment]
Pls....
