### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#190]
Sometimes dmg done from awp are shown as demo done by other weapons
Like I found at my server that 440dmg by flashbang which was actually by awp
It was shown in amxmodx plugin that shows damage done by you through miscstats.amxx i think...
Is it problem with regamedll or reamxx ?

**Comment by In-line** [comment]
Use amx x 1.8.3-dev

**Comment by ish12321** [comment]
Link to it?
Is it stable?

**Comment by ish12321** [comment]
Has reamxx stopped?

**Comment by simeonniko** [comment]
https://github.com/alliedmodders/amxmodx/pull/417

**Comment by Phantomsq** [comment]
Here you go: http://www.amxmodx.org/snapshots.php. Use for pleasure
