### ISSUE TITLE
How to block jump/landing sounds?

### ISSUE THREAD

**Issue by eat1k** [s1lentq/ReGameDLL_CS#198]
В FM_EmitSound не блокируются звуки прыжка и приземления, если можно то сделать какую-то замену или как-то решить эту проблему

**Comment by In-line** [comment]
http://amxxmodx.ru/fun/funinc/20-set_user_footsteps-besshumnye-shagi.html ¯\_(ツ)_/¯

**Comment by eat1k** [comment]
@In-line это давно не работает (в нормальном формате), чтобы бесшумные шаги адекватно работали на AMXX 1.8.3 нужно добавлять проверку в PreThink. И даже так, звук от шагов блокируется, но от прыжков и после приземления нет

**Comment by eat1k** [comment]
Решение: http://www.dedicated-server.ru/vbb/showpost.php?p=293817&postcount=35
