### ISSUE TITLE
Connecting player shown as *DEAD* CT or TT

### ISSUE THREAD

**Issue by IgnacioFDM** [s1lentq/ReGameDLL_CS#21]
(for REGAMEDLL_FIXES)
Always show connecting players as spectators instead of randomly showing some of them as DEAD CT/TTs 

I peeked at this issue but couldn't find what really caused it, and didn't want to add a hacky workaround (such as re-setting team in ClientConnected). Although it may just be that, that team is never set.

**Comment by s1lentq** [comment]
you are talking about hanged players in the scoreboard after changing the level?
if yes so it was fixed in rehlds.

**Comment by IgnacioFDM** [comment]
Yeah, that's it I guess. Silly me. I'm not running ReHLDS since it's not stable yet for me, so I didn't notice it was fixed there.
