### ISSUE TITLE
Add the possibility to block two sounds with RH_SV_StartSound

### ISSUE THREAD

**Issue by eat1k** [s1lentq/ReGameDLL_CS#211]
Возможность заблокировать эти два звука:
"items/gunpickup2.wav" после использования rg_round_respawn (т.е. после воскрешения).
"common/bodysplat.wav" после падения, если урон от падения выше чем здоровье.

**Comment by Vaqtincha** [comment]
RH_ Это REHLDS хуки. так что регейм тут не причем. Но ты можошь блокнут через FM_EmidSound

**Comment by eat1k** [comment]
@Vaqtincha через FM_EmitSound эти два звука так же не блокируются

**Comment by Vaqtincha** [comment]
покажи попытки
