### ISSUE TITLE
Galileo 1.1.290 doesn't work

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#213]
Tried 'mp_round_infinite ae' with 'mp_roundover 1' on latest regamedll on linux and since a certain amount of maptime (~3/4) the de_ round doest restart after bomb explosion.
Happend on css_overpass

**Comment by In-line** [comment]
When did this start to happen?

**Comment by fred0r** [comment]
Since switching to regamedll.
Before i've been using a Amxx-Plugin for that, but it was disabled at that time.

**Comment by In-line** [comment]
Update galileo

**Comment by fred0r** [comment]
i'm using the 'original version' from Brad and **NOT** this:
https://forums.alliedmods.net/showthread.php?t=273019
i did recompile the 'latest brad' with 'the latest amxx 1.8.3 5144' that time.

**Comment by In-line** [comment]
@fred0r Update it. Don't use old version.

**Comment by fred0r** [comment]
thx - i'll try.

**Comment by fred0r** [comment]
Updated galileo to v5.8.1-918  and now everything works.
i didnt enable the rehlds-option for map extension now, but:
thank you
