### ISSUE TITLE
Bad bomb angles (#207)

### ISSUE THREAD

**Issue by Freeman-AM** [s1lentq/ReGameDLL_CS#218]
Related to https://github.com/s1lentq/ReGameDLL_CS/pull/207

Since most people use right hand ingame, bomb feel reversed about the angle. The right is at the left and so on.

That could be easly fix by changing the angle value, but i have no time to test this.

**Comment by In-line** [comment]
Nobody actially voted for this idea, so this is not number one priority. Did you mean that bomb is placed backwards?

**Comment by Freeman-AM** [comment]
https://github.com/s1lentq/ReGameDLL_CS/blob/519a73179fd039d22a50829b04c65c9ed8945370/regamedll/dlls/wpn_shared/wpn_c4.cpp#L163

Basically it's just a value to change here.
Basically since most people use right hand, IE on the models, the wires are on the right, but when the bomb fall in the world, the wires are on the left.
