### ISSUE TITLE
Server Crash on Round End + SV_RESTART + USER_KILL

### ISSUE THREAD

**Issue by Depresie** [s1lentq/ReGameDLL_CS#219]
https://forums.alliedmods.net/showthread.php?p=2562176#post2562176

**Comment by In-line** [comment]
I was unable to reproduce crash.

**Comment by Depresie** [comment]
Steps to reproduce
- Join the game
- set mp_roundtime to 1
- set mp_freezetime to 0
- set sv_restart to 1
- Now you will either get stuck in a round end loop or it will crash

Alternative
- set mp_roundtime to 1 ( from .cfg file )
- set mp_freezetime to 0 ( from .cfg file )
- Join the game
- Wait for the round to end
- Now both the client and the server shall crash

Usually without ReHLDS and ReGame you will be stuck in a loop
With ReHLDS 
- exe version: 1.1.2.7
- exe build: 18:03:22 OCT 24 2017 ( 1291)
ReGame
- 5.3.0.256 dev

**Comment by In-line** [comment]
@Depresie Was this your crash message?
```PF_MessageBegin_I: New message started When msg 'X 'has not been sent yet```

**Comment by Depresie** [comment]
I couldn't read the error message, but HamletEagle figured out what the problem was..
Basically sending a message from a get_user_msgid hook is not a thing to do, he explained it here
https://forums.alliedmods.net/showthread.php?p=2562219#post2562219

[quote]
 When you try to kill the player, game is executing code from PlayerKilled and DeathNotice, which in turn are sending messages. But when you hook a message with register_message, it is not sent already, so most likely game tries to send another message while the previous one is not finished yet.
[/quote]

This issue can be closed, since it is not a bug, it actually works as intended.
