### ISSUE TITLE
Feature-Request: mp_show_voiceicon

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#222]
It would be really great if the voiceicon isnt visible during alltalk.

**Comment by Vaqtincha** [comment]
https://forums.alliedmods.net/showthread.php?p=368204?p=368204

**Comment by fred0r** [comment]
Oh - thought that its basically the same thing as 'mp_show_radioicon'

**Comment by In-line** [comment]
Closing, because it's impossible for obvious reasons.
