### ISSUE TITLE
Bot Commiting Continues Suicide/Weird Colors on Maps

### ISSUE THREAD

**Issue by MAXBURAOT** [s1lentq/ReGameDLL_CS#223]
-Bot Commiting Continues Suicide after round finish
-Weird color in de_dust home base

![1](https://user-images.githubusercontent.com/33173384/33232901-1559221a-d249-11e7-8be6-345900c19a22.png)
![2](https://user-images.githubusercontent.com/33173384/33232902-159948b8-d249-11e7-98d8-e0524cc3a1ed.png)

> 
] meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.8.3-d  ini   Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm.dll    v0.1.75   ini   Start Never
 [ 3] LocalizeBug Fix  RUN   -    localizebugfix_m  v2.3      ini   Start Never
 [ 4] PatchMoney       RUN   -    patchmoney_mm.dl  v2.2      ini   Start Never
 [ 5] Rechecker        RUN   -    rechecker_mm.dll  v2.5      ini   Chlvl ANY  
 [ 6] ReSemiclip       fail load  resemiclip_mm.dl  v2.3.9    ini   Chlvl ANY  
 [ 7] SafeNameAndChat  RUN   -    safenameandchat.  v1.1      ini   ANY   ANY  
 [ 8] VoiceTranscoder  RUN   -    voicetranscoder.  v2017RC3  ini   ANY   ANY  
 [ 9] WinHL-Booster    RUN   -    booster_mm.dll    v1.46     ini   Chlvl Pause
 [10] GetGameDirFix    RUN   -    getgamedirfix_mm  v1.0      ini   ANY   ANY  
 [11] NoHeadShot       RUN   -    noheadshot_mm.dl  v1.12     ini   Chlvl ANY  
 [12] POD-Bot mm       RUN   -    podbot_mm.dll     vV3B23    ini   Chlvl ANY  
 [13] RealBot          RUN   -    realbot_mm.dll    v3073     ini   Chlvl ANY  
 [14] Yet Another POD  RUN   -    yapb.dll          v2.8      ini   Chlvl ANY  
14 plugins, 13 running

] meta version
Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:14 EET (optimized)

] game version
ReGameDLL version: 5.3.0.273-dev
Build date: 17:43:30 Nov 22 2017
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/7f9cf53

] amxx version
AMX Mod X 1.8.3-dev+5144 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Oct 31 2017 15:08:16
Built from: https://github.com/alliedmodders/amxmodx/commit/175d492
Build ID: 5144:175d492
Core mode: JIT+ASM32

] version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
ReHLDS version: 3.3.0.605-dev
Build date: 22:55:56 Nov  8 2017 (1306)
Build from: https://github.com/dreamstalker/rehlds/commit/dab2663

**Comment by voed** [comment]
1. You have 3 different bot modules on your server
2. You have alot of memory patching modules, they dont work on rehlds and may produce a lot of bugs.
First of all,try too disable all except amxmodx, re* modules, VTC and POD-Bot

**Comment by MAXBURAOT** [comment]
@voed ,thanks using awp_map.bsp, i found what wrong must set mp_roundover 1 and mp_forcerespawn 1, if mp_forcerespawn set below 1 all player will kill-respawn automatic (infinite loop)
-what i noticed is everytime map-round ends server will kill random player (Bots and Humans)
![3](https://user-images.githubusercontent.com/33173384/33237588-e2f418ce-d2b2-11e7-8cd3-ed502c939684.png)

**Comment by In-line** [comment]
@MAXBURAOT Did you disable pb_autokill?

**Comment by MAXBURAOT** [comment]
@In-line yup for PodBotMM v3.0.23 i set to "0", also its happening kill-respawn also on other BOTS -CSBotv1.5/RealBot r3073 Beta/YaPB Bot v2.8.4766 and Human Players. 
mp_roundtime 1

![3](https://user-images.githubusercontent.com/33173384/33238772-e67272cc-d2ce-11e7-8717-216815860ff3.png)
![4](https://user-images.githubusercontent.com/33173384/33238773-e6c0e3f8-d2ce-11e7-9714-b9c2f0712b1f.png)
![1](https://user-images.githubusercontent.com/33173384/33238770-e5d77fc4-d2ce-11e7-9ea7-05bfd68a523f.png)
![2](https://user-images.githubusercontent.com/33173384/33238771-e62894fe-d2ce-11e7-9994-b78fad831d49.png)

**Comment by MAXBURAOT** [comment]
![1](https://user-images.githubusercontent.com/33173384/33428722-f7617428-d604-11e7-88e1-feccd37bff40.png)
![2](https://user-images.githubusercontent.com/33173384/33428723-f7a4fb62-d604-11e7-9a65-3d91f5af9233.png)
![3](https://user-images.githubusercontent.com/33173384/33428724-f7e5356a-d604-11e7-9937-b0fd11737577.png)
![4](https://user-images.githubusercontent.com/33173384/33428725-f823c8a2-d604-11e7-97b1-bb14421e9257.png)
