### ISSUE TITLE
"trigger_changetarget" broken in maps since a recent commit

### ISSUE THREAD

**Issue by Freeman-AM** [s1lentq/ReGameDLL_CS#231]
Since this commit : https://github.com/s1lentq/ReGameDLL_CS/commit/7f9cf53c4906343514e9560e0e536a517c195444 aka 5.3.0.273-dev

"trigger_changetarget" stopped working in maps fun_matrix, fun_matrix_reloaded and fun_matrix_revolutions
from data i gathered from the map, those entity use m_iszNewTarget

Those maps are important to us, so i'm rolling back to 5.3.0.270-dev

I'm not sure at 100% that it's linked to those entities, but i will describe the problem  :
- Usually when 2 players connect, deagle door open, round is over, awp door open... and it circle with other weapons doors... in a specific order. 
- Since that update, only deagle door open at each round

You must need 2 players ingame otherwise no door will open.

**Comment by s1lentq** [comment]
actually affected by commit 0318c36

**Comment by fred0r** [comment]
It looks like its the same problem as in https://github.com/s1lentq/ReGameDLL_CS/issues/221

**Comment by Freeman-AM** [comment]
Working fine now. Thanks for your work. ;)
