### ISSUE TITLE
bug round end c4 plant

### ISSUE THREAD

**Issue by OsweRRR** [s1lentq/ReGameDLL_CS#237]
when the bomb is planted and the anti terrorists kill all the terrorists the round ends without having defused the bomb and the anti terrorists win.

this usually happens a few times.

rehlds 3.3.0.618
regamedll 5.3.0.276
Reapi 5.2.0.143

**Comment by lespaul64** [comment]
Agreed, it happen on me too.

Details (Windows OS):
mp.dll version -- "game_version" is "5.3.0.276-dev"
ReHLDS -- "sv_version" is "1.1.2.7/Stdio,48,1340"
ReAPI -- version: 5.2.0.143-dev

**Comment by OsweRRR** [comment]
good.

2017-12-15 14:44 GMT-03:00 lespaul64 <notifications@github.com>:

**Comment by fred0r** [comment]
Are you using Galileo-Plugin ?
If yes you need to update to latest Galileo:https://github.com/s1lentq/ReGameDLL_CS/issues/213

**Comment by OsweRRR** [comment]
I do not use galileo plugin I only have a few plugins working

https://image.prntscr.com/image/Xyh9BE4vQaO0PqDATCE8-g.png

**Comment by In-line** [comment]
Closing as non active.
