### ISSUE TITLE
TakeDamage Knockback calculation is not accurate

### ISSUE THREAD

**Issue by Depresie** [s1lentq/ReGameDLL_CS#241]
This part of CBaseEntity:TakeDamage regarding the method used for knockback calculation is not accurate, more exactly it is not how it works in the default game dll

This is the method used in regame dll for knockback calculation on take damage
real_t flForce = flDamage * ((32 * 32 * 72.0) / (pev->size.x * pev->size.y * pev->size.z)) * 5;

But in the default game dll each weapon has it's own knockback modifier

**Comment by WPMGPRoSToTeMa** [comment]
Proof?

**Comment by In-line** [comment]
Closing as non active
