### ISSUE TITLE
Hostages: Climb/Crawl-Support

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#246]
It would be nice to play with 'more intelligent' Hostages.
They should be able to follow all CT movements.

**Comment by spark512** [comment]
https://forums.alliedmods.net/showthread.php?t=50842

You can check this for reference. Would be interesting to see a gamedll implementation of this :).

**Comment by fred0r** [comment]
So this would be possible ?

**Comment by Phantomsq** [comment]
Use "-host-improv" parameter

**Comment by In-line** [comment]
`-host-improv` should enable czero hostages, they have advanced AI and
require waypoints (.nav files).You'll also need bunch of hostage specific
czero models and sounds. It is option created for testing purposes, I can't
guarantee that hostages will work correctly.

**Comment by fred0r** [comment]
The `-host-improv` doesnt work so well.
Its also a problem that there are so less .nav-files around for custom cs_Maps as generating takes ages.
It would be really nice to have 'native support'.

**Comment by In-line** [comment]
It will be interesting if tell us about test results. Particularly what "doesn't work well"

**Comment by fred0r** [comment]
For example cs_deadline.
The player is able to crouch inside the metal tunnel 'passages' - but the hostages dont follow.

**Comment by fred0r** [comment]
is there some 'bounty programm' available covering regamedll_cs ?

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r what do you mean?

**Comment by fred0r** [comment]
that its possible to 'pay' for reaching features

**Comment by fred0r** [comment]
> https://forums.alliedmods.net/showthread.php?t=50842
> You can check this for reference. Would be interesting to see a gamedll implementation of this :).

I enabled that plugin on cs_maps only a few weeks ago and maybe all of my other latest bug-posts are the result ?
https://github.com/s1lentq/ReGameDLL_CS/issues/497
https://github.com/s1lentq/ReGameDLL_CS/issues/510
https://github.com/s1lentq/ReGameDLL_CS/issues/511

**Comment by RauliTop** [comment]
> > https://forums.alliedmods.net/showthread.php?t=50842
> > You can check this for reference. Would be interesting to see a gamedll implementation of this :).
> 
> I enabled that plugin on 'cs_maps only' a few weeks ago and maybe all of my other latest bug-posts are the result ?
> #497
> #510
> #511

So, check disabling the plugin, no?

**Comment by fred0r** [comment]
yes, but at the same time i did a downgrade to `ReHLDS version: 3.7.0.692-dev` and `ReGameDLL version: 5.13.0.447-dev+m` - until now the mentioned errors didnt occur anymore.
i'll recheck with enabled prometheus soon.

**Comment by fred0r** [comment]
My mentioned errors outside this Issue still exist - even with downgraded rehlds/regameDLL.
I'll update the other other posts.
So it may be 'safe' to use prometheus.

**Comment by fred0r** [comment]
Just as Info:
Prometheus works ok for me with latest ReHLDS/regamedll_cs, since my errors mentioned in this Issue-Thread got resolved by https://github.com/s1lentq/ReGameDLL_CS/pull/528
