### ISSUE TITLE
mp_teamflashpunish cvar

### ISSUE THREAD

**Issue by GoRiLliAz** [s1lentq/ReGameDLL_CS#247]
Hi 
Its possible to add this function ? 
Flashteam Detection and punish Thanks

**Comment by Phantomsq** [comment]
This already can be implemented by reapi. Look the [_reapi_gamedll_const_](https://github.com/s1lentq/reapi/blob/master/reapi/extra/amxmodx/scripting/include/reapi_gamedll_const.inc#L502) include

**Comment by GoRiLliAz** [comment]
Yes but I'm not encoders
Is there already mp_tkpunish for not mp_teamflashpunish?

**Comment by In-line** [comment]
It will be very unflexible and useless, because same functionality can be easily implemented via AMXX plugin.

**Comment by fred0r** [comment]
There are already amxx-plugins for this:
https://forums.alliedmods.net/showthread.php?p=651444
or
https://forums.alliedmods.net/showthread.php?p=596743
