### ISSUE TITLE
Bomb planted, all ct's died, but no roundend.

### ISSUE THREAD

**Issue by bjallamo** [s1lentq/ReGameDLL_CS#25]
Sometimes happened the bomb planted, all CT's died, but no roundend.
We have to wait for the bomb explode.

**Comment by Arkshine** [comment]
A friend told me it usually happens when you have a crashed CT player, who is somehow disconnected but the entity is still around for some reason, invisible, and you can try to kill him at the CT spawn.

**Comment by Vaqtincha** [comment]
Really?

**Comment by Vaqtincha** [comment]
Fix
