### ISSUE TITLE
[Request] Map Spawn Fix

### ISSUE THREAD

**Issue by Dr-Strange91** [s1lentq/ReGameDLL_CS#250]
Many maps have bugged spawns.
Like map is of 32 Players but only 20 players can join teams [CT + T].
And we have use 3rd party plugins to fix them.
What if it gets, fix with regame??

Cvars:
Normal Behavior- 0
Spawn_Fix_Behavior 1

**Comment by In-line** [comment]
How do you imagine that? We can generate new spawn positions, but it will be very hard to do in some cases.

**Comment by regener** [comment]
It is caused by the map authors, if they don't make enough it is hard to generate new ones that are still in buy zone and don't trigger death for the other ones.
