### ISSUE TITLE
mp_legacy_bombtarget_touch: Bomb is not plantable

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#251]
Since this https://github.com/s1lentq/ReGameDLL_CS/commit/7a429eadfe72ae0a09b3e08784b4a97f81a9751e Commit the Bomb isnt plant-able at all on several Maps.
 - de_mjolby6
 - de_westwood
- de_westwood_2011_beta2 

There might be even more.
Then i configured that 'the old behavior' and it worked for some maps but then again failed on de_mjolby6.
i used the bugfixed binarys and also latest galileo.

**Comment by fred0r** [comment]
Am i really the only person with that problem ?
Server runs on Linux.

**Comment by In-line** [comment]
It is because of weird bombtarget placement in the map. This bug will be
fixed soon

**Comment by wopox1337** [comment]
![image](https://user-images.githubusercontent.com/18553678/35479901-aa61e8d2-0413-11e8-9d0a-a5ac0a0a9642.png) - good area

![image](https://user-images.githubusercontent.com/18553678/35479904-c8cd6e54-0413-11e8-96cb-e8a2eed2f693.png) - poor area

**Comment by fred0r** [comment]
Thank you.

**Comment by Phantomsq** [comment]
@fred0r, don't forget to close it
