### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by csoyuncu** [s1lentq/ReGameDLL_CS#254]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':regamedll:compileReleaseRegamedllFixesRegamedll_mp_gamedllSharedLibraryRegamedll_mp_gamedllEngine_src'.
> A build operation failed.
      C++ compiler failed while compiling unicode_strtools.cpp.
  See the complete log at: file:///root/ReGameDLL_CS/regamedll/build/tmp/compileReleaseRegamedllFixesRegamedll_mp_gamedllSharedLibraryRegamedll_mp_gamedllEngine_src/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.0 secs

how can i fix this ? i dont use icc

**Comment by In-line** [comment]
Windows?

**Comment by csoyuncu** [comment]
no, i use fedora core 25 32 bit.

**Comment by In-line** [comment]
Non ICC compilers are not supported of Linux.
