### ISSUE TITLE
Compile error with Visual Studio 2013.

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#259]
Hi,
Again i've failed to compile this project, but now it's different errors.

> Error	48	error C2334: unexpected token(s) preceding '{'; skipping apparent function body	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	60	1	ReGameDLL
> Error	49	error C2062: type 'auto' unexpected	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	61	1	ReGameDLL
> Error	50	error C3553: decltype expects an expression not a type	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	61	1	ReGameDLL
> Error	51	error C2059: syntax error : ')'	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	61	1	ReGameDLL
> Error	52	error C2334: unexpected token(s) preceding '{'; skipping apparent function body	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	61	1	ReGameDLL
> Error	53	error C2062: type 'auto' unexpected	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	67	1	ReGameDLL
> Error	54	error C3553: decltype expects an expression not a type	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	67	1	ReGameDLL
> Error	55	error C2059: syntax error : ')'	f:\x\x\downloads\compressed\regamedll_cs-master\regamedll\dlls\vector.h	67	1	ReGameDLL

Most of errors are from vector.h, any idea how to fix it?

**Comment by In-line** [comment]
What is the output when you try to compile the project with gradle?

**Comment by lespaul64** [comment]
@In-line 
Errmm i don't use gradle, i compile directly using "ReGameDLL_CS-master\msvc\ReGameDLL.sln" file.

**Comment by In-line** [comment]
@lespaul64 Yes, I know. Try to use gradle.

**Comment by lespaul64** [comment]
@In-line here is the output from gradlew https://pastebin.com/8uJXirxX

**Comment by lespaul64** [comment]
Ok i've found the culprit, it because of my outdated vs, i need vs2015 or later. Now everything works fine.

**Comment by In-line** [comment]
Fixed in #260 .
