### ISSUE TITLE
Weapon Restrictions (Amxmodx)

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#261]
I'm using latest 5151-amxx with rehlds and regame_dll/reapi.
it happens quite often that players are able to buy restricted weapons.
in my case i've disable the shields but under 'certain conditions' the cts are able to buy them.
to me it looks like this happens randomly.

weaprest.ini
```
; Generated by Restrict Weapons Plugin. Do not modify!
; value name
g3sg1            ; H&K G3/SG-1 Sniper Rifle
sg550            ; Sig SG-550 Sniper
shield           ; Tactical Shield

**Comment by In-line** [comment]
Use https://dev-cs.ru/threads/181/

**Comment by Arkshine** [comment]
The plugin `Restrict Weapons` is using the `ReGameDLL` API as well. It does the same as the `Item Restrict`  plugin. If it doesn't work under _certain conditions_ and assuming no one is playing with the `amx_restrict` command or menu, I can't see an issue with the plugin.

@fred0r What conditions are you talking about, can you somehow reproduce/elaborate them?

**Comment by In-line** [comment]
Check the source code. @s1lentq's implementation and AMX Mod X version work very differently.

**Comment by Arkshine** [comment]
You could have explained directly, at least for people having the same issue, but I get it, it's true `HasRestrictItem` is not called only on buy and that `Item Restrict` plugin will block in all context. `Restrict Weapons` cares only on buy [for now].

**Comment by fred0r** [comment]
@In-line It seems like the Shield is missing in that plugin ?!
@Arkshine So i dont need to look further - you found the cause ?

**Comment by Arkshine** [comment]
@fred0r , in that plugin, the shield is in the first position.

About your issue, as said above, Restrict Weapons is only to restrict weapons when you buy them (at least for now, it's on the todo list to expand further). If you get it in another way, like from the ground, it's not going to work.

**Comment by spark512** [comment]
@Arkshine i think they can still get them via the autobuy and the rebuy commands. @s1lentq 's implementation prevents those cases as well.

**Comment by Arkshine** [comment]
Nope, If it's about alias command, it's covered. I remember testing it, but like as said, the plugin is only preventing buying for now. For fred, it's likely recommended to use Item Restrict.

**Comment by fred0r** [comment]
@Arkshine Thats why i started this Ticket: The Players can buy restricted Weapons.

**Comment by In-line** [comment]
@fred0r Was the problem solved?

**Comment by fred0r** [comment]
No - but i think its not a RegameDLL-Bug.
