### ISSUE TITLE
Botcount = 0 ?

### ISSUE THREAD

**Issue by csoyuncu** [s1lentq/ReGameDLL_CS#262]
hello. can i do botcount 0 when i add bots to my server ?

**Comment by In-line** [comment]
What do you mean by that?

**Comment by csoyuncu** [comment]
i will bots to my server but i want to see botcount "0" at hlsw

**Comment by In-line** [comment]
It should be implemented in reunion, but I guess nobody will actually do it. Fooling players is bad.
