### ISSUE TITLE
Chat question.

### ISSUE THREAD

**Issue by lspublic** [s1lentq/ReGameDLL_CS#274]
Hello i want to ask i have one problem i have sv_alltalk 0 , but i dont know when write dead players who is live can see in chat all , and it is one problem because players tell when hide players and its not okey i want to ask how to blocked just for dead players when write cant see live players

**Comment by In-line** [comment]
https://forums.alliedmods.net/showthread.php?t=56825

**Comment by lspublic** [comment]
Yes i know i think for any cvar in game.cfg

**Comment by WPMGPRoSToTeMa** [comment]
Communication between dead and alive is blocked by default, isn't it?
https://github.com/s1lentq/ReGameDLL_CS/blob/40f3bc488be6fb7893df1490f06c595af8785259/regamedll/dlls/client.cpp#L944-L948

**Comment by lspublic** [comment]
I have last update regamedll and sv_alltalk i have 0 in game.cfg but one my friend tell me you have chat prefix and he think this chat prefix not allow to working this cvar dead when write can see all who is dead and alive in server and is bad because can tell where is players,wheres is bomb and i want to block

**Comment by In-line** [comment]
Stop, sv_alltalk isn't related to the chat.

**Comment by lspublic** [comment]
Aha okey :D
