### ISSUE TITLE
Respawn Problem

### ISSUE THREAD

**Issue by lspublic** [s1lentq/ReGameDLL_CS#275]
Hello i have last update ReGameDLL i have active plugin Maps Spawn Editor but in some maps more time in cs_assault_1337 when respawn players 3-4 dead in respawn can you check what its wrong ?

**Comment by In-line** [comment]
Roll the dice.

1. You placed spawns wrongly
2. There were not enough spawns
3. It is something else

**Comment by vitorrossi** [comment]
This is likely not a ReGameDLL issue.
I agree with In-line, its either 1 or 2.
Here is the original thread of the plugin you mentioned: https://forums.alliedmods.net/showthread.php?t=43660
Go there and read how to set spawns properly.
I'd recommend deleting the current spawn file you have and starting fresh.
