### ISSUE TITLE
Playing from spectator

### ISSUE THREAD

**Issue by lspublic** [s1lentq/ReGameDLL_CS#278]
Hello i dont know i remove all admin acces to change team but use jointeam and when change some players and admin can play from spectator can you help me how to blocked cant play from spectator look photo : https://i.imgur.com/NMp5Y6L.jpg

My ReHLDS Version :  
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.4.0.639-dev
         Build date: 17:47:13 Feb 21 2018 (1411)
         Build from: https://github.com/dreamstalker/rehlds/commit/822df9a

My ReGameDLL : 
         ReGameDLL version: 5.7.0.295-dev
         Build date: 15:10:22 Feb 19 2018
         Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/aa329db

**Comment by In-line** [comment]
Disable all amxmodx plugins related to teamchange or provide more information ¯\\_(ツ)_/¯

**Comment by lspublic** [comment]
@In-line  i want to sent more prove but players not sent video how play i have photo very much https://i.imgur.com/edEdwTu.jpg i think maybe when try to write in console jointeam 6 and when back again in game can play from spec and can kill friend

**Comment by TheRedShoko** [comment]
I believe that it's something related to [https://github.com/s1lentq/ReGameDLL_CS/issues/111](this). I see it's fixed and closed but there may be some other way for this to happen.

**Comment by lspublic** [comment]
@TheRedShoko this mp_forcerespawn 1 is bad because i have public server no deathmatch
