### ISSUE TITLE
Too fast firing with dual elites

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [s1lentq/ReGameDLL_CS#3]
With this code https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/wpn_shared/wpn_elite.cpp#L126 dual elites can fire about 13 times per second. It's too fast, isn't it?
You can test it with this:
```
alias f "+attack;wait;-attack;wait"
alias f2 "f;f"
alias f4 "f2;f2"
alias f8 "f4;f4"
alias f16 "f8;f8"
alias f32 "f16;f16"
alias f64 "f32;f32"
bind mouse1 f64
```

**Comment by s1lentq** [comment]
thanks! good to know.
i think enough

```
flCycleTime -= 0.078;
```

**Comment by WPMGPRoSToTeMa** [comment]
Yeah, this value is best balanced.

**Comment by satnatantas** [comment]
Oh I see, just need "pure" version.

**Comment by satnatantas** [comment]
I'd like to make a CVAR for that, will you accept it if I program it? I think that it should be the same as in pure library because firing speed is already balanced with mad recoil (which is twice the recoil displayed on screen, bullets actually go even higher). You are just killing fun because many servers now use bugfixed ReGame.

**Comment by voed** [comment]
@s1lentq can we revert this? It breaks game balance and seems completely illogic.
For example, glock has 0.05 cycletime, usp has 0.075, so why two guns cannot shoot faster than one?🤔

**Comment by satnatantas** [comment]
The "fix" has also a terrible side effect being that the client will display shots at requested speed without using bullets unless the client has very small network latency,

**Comment by WPMGPRoSToTeMa** [comment]
https://coub.com/view/1mlp7k

**Comment by Vaqtincha** [comment]
fix strelba ot voedlol

**Comment by satnatantas** [comment]
I appreciate this reversion!

**Comment by satnatantas** [comment]
This weapon is almost never used, it is next to impossible to control it at higher firing rate, and the bullet marks are not even correct with cl_lw 0 on any server and it has parallax unlike any other weapon - these are all the issues you need to deal with when you use it. Please do not ruin the only fun weapon who nobody uses.

ValveSoftware/halflife#2822

**Comment by satnatantas** [comment]
pussies
