### ISSUE TITLE
Bad Spawn Prevention/Fix

### ISSUE THREAD

**Issue by Dr-Strange91** [s1lentq/ReGameDLL_CS#316]
Though the plugin exist, but it would be amazing, this as a part of Game it self.

There are many maps that have corrupted spawn points. If you get spawned in one of those - you will get killed thus leaving you dead waiting for next round. This plugin respawns the player if he got killed because of bad spawn position and respawns the player if he is stuck in the wall at spawn.

OR Something Like this, which would Automatically Fix Bad Spawns?

https://forums.alliedmods.net/showthread.php?p=1047629?p=1047629

**Comment by Vaqtincha** [comment]
test

**Comment by Karaulov** [comment]
> Though the plugin exist, but it would be amazing, this as a part of Game it self.
> 
> There are many maps that have corrupted spawn points. If you get spawned in one of those - you will get killed thus leaving you dead waiting for next round. This plugin respawns the player if he got killed because of bad spawn position and respawns the player if he is stuck in the wall at spawn.
> 
> OR Something Like this, which would Automatically Fix Bad Spawns?
> 
> https://forums.alliedmods.net/showthread.php?p=1047629?p=1047629

In latest ReHLDS you can manually fix it, need enable sv_use_entity_file cvar and edit /cstrike/maps/mapname.ent file. ))) (For example using BspViewer locate needed spawn, and move it, then save values to ent file and restart map ('restart' or 'changelevel') )

Example modifications using sv_use_entity_file https://github.com/Karaulov/rehlds-entity-files-for-maps

**Comment by afwn90cj93201nixr2e1re** [comment]
mp_kill_filled_spawn
