### ISSUE TITLE
mp_respawn_immunitytime - protection condition 

### ISSUE THREAD

**Issue by Zetz512** [s1lentq/ReGameDLL_CS#318]
Hello, can protection be improved?

I want disable it automatically the protection if player make a SHOOT, because he can kill while still has protection

Sry for my bad english

**Comment by Vaqtincha** [comment]
тут я даже https://github.com/s1lentq/ReGameDLL_CS/commit/26db32e8845647cf024e38f11cb3da3071ac0dd1
предложил но как всегда умничали и никуя не сделали...

**Comment by PredatorFly** [comment]
amxx, 	 set_member(id, m_flSpawnProtectionEndTime, 0.00001)
