### ISSUE TITLE
Broken bot chatter

### ISSUE THREAD

**Issue by a1batross** [s1lentq/ReGameDLL_CS#321]
This [line](https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/bot/cs_bot_chatter.cpp#L609) may break bot chatter in certain situations. For example:
* When sounds are packed in PAK file.
* When sounds are stored somewhere else than "cstrike" folder, for example, "cstrike_hd", "cstrike_download" or "cstrike_<language>".

**Comment by s1lentq** [comment]
Closed by 9b4def6
