### ISSUE TITLE
Failed To Build

### ISSUE THREAD

**Issue by HowToDoThis** [s1lentq/ReGameDLL_CS#329]
I Know This Question Is Quite Stupid, But I Still Wanna Ask About It.

I Download This As ZIP and trying to build it with Visual Studio 2017 and Gradle ( Code From ReadMe.md )
and I get a weird build error, it says missing appversion.h
so I make a blank appversion.h (For Seeing other errors), vector.h also get a lots of error.

*Note : BTW my Javac Version is javac 1.8.0_192 and Visual Studio is 2010 - 2017

**Comment by WPMGPRoSToTeMa** [comment]
Clone it through git instead of downloading zip.

**Comment by HowToDoThis** [comment]
Oh Thanks, It Fixed that weird bugs, I can build now. Is that any black magic cause this working?

**Comment by HowToDoThis** [comment]
Okay, I found a quite weird bug, i can build with gradlew normally but if i using Visual Studio build, it still showing vector.h error. Output Log : https://hastebin.com/goyecivuqi.shell
