### ISSUE TITLE
[Error] Game/Server crash when CSBot spawned.

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#33]
I'm using latest build downloaded from snapshots build: regamedll-0.2-20160511.191129-85.zip
Game is legit steam and running without metamod.

How to reproduce:
1. Create new game.
2. In-game open console and type bot_quota 9

On 4th / 5th bot spawned game will crash.

Game not crash on older regamedll build regamedll-0.2-20160424.183401-84.zip

**Comment by s1lentq** [comment]
You've already read the [manual](https://github.com/s1lentq/ReGameDLL_CS#how-to-install-zbot-for-cs-16)?
to running from CS 1.6 to clients you need run with parameters -bots

**Comment by lespaul64** [comment]
Of course i read the manual, i use -bots in steam parameters.
**Game not crash on older regamedll build regamedll-0.2-20160424.183401-84.zip**

**Comment by s1lentq** [comment]
Will clarify some things.
- Do you use Steam CS 1.6?
- and what is your OS?

**Comment by lespaul64** [comment]
Did you read my 1st post?
I clearly said that i'm using legit cs16 game which mean original steam cs1.6
I'm on Windows 10 Pro x64

**Comment by s1lentq** [comment]
> Did you read my 1st post?
> I clearly said that i'm using legit cs16 game which mean original steam cs1.6

I meant mod the game. (cs16, czero)

Try last build.

**Comment by lespaul64** [comment]
Sorry for that, yes mod is CS1.6.
Ok tested the new build regamedll-0.2-20160517.134238-90.zip game no longer crash.

Mind to tell me what cause the issue?
