### ISSUE TITLE
Number of Teamcount is flipped

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#330]
I dont know if this is rehlds or regamedll_cs related, but:
The count for the teams are flipped:
http://i.imgur.com/7dZVZ4V.png
Screenshot shows 7 Players of T - but there are actually only 6.
The CT Team has 7 Players, but there are 6 shown.
It happens on Windows and Linux-Clients.

**Comment by voed** [comment]
This numbers are counted in client as i know, so its might be client-side bug. Maybe even localization bug

**Comment by fred0r** [comment]
i did some more tests.
It seems that i could narrow it down to using a  'native Linux Clients'.
i'm playing CS using the 'steam-native'-binary.
When the Teamcount is flipped, this dont happen to other people playing on Windows.
