### ISSUE TITLE
Request - Prevent jump

### ISSUE THREAD

**Issue by Droads2** [s1lentq/ReGameDLL_CS#337]
Is it possible to create a jump block like PLAYER_PREVENT_CLIMB/DUCK?
It can be done with setting player high gravity but i think thats bad way..
Any suggestion?

**Comment by CrazY770** [comment]
Actually you can hook RG_PM_Move with ReAPI and unset from pmove->cmd.buttons var the IN_DUCK and IN_JUMP, something like the code below, but for some reason jump still applies a little velocity in z axis of player.

```
#include <amxmodx>
#include <reapi>

public plugin_init()
{
	register_plugin("[ReAPI] Block Jump/Duck", "1.0", "Crazy");

	RegisterHookChain(RG_PM_Move, "PM_Move");
}

public PM_Move(const PlayerMove:pmove, server)
{
	static cmd, bitsButtons;

	cmd = get_pmove(pm_cmd);
	bitsButtons = get_ucmd(cmd, ucmd_buttons);
	bitsButtons &= ~IN_JUMP;
	bitsButtons &= ~IN_DUCK;
	set_ucmd(cmd, ucmd_buttons, bitsButtons);
}`
```

**Comment by LevShisterov** [comment]
> but for some reason jump still applies a little velocity in z axis of
player.
It's client side prediction. Check with cl_lc 0.

**Comment by CrazY770** [comment]
> but for some reason jump still applies a little velocity in z axis of
> player. It's client side prediction. Check with cl_lc 0.

I did the test but same.

**Comment by fl0werD** [comment]
It can be closed because https://github.com/s1lentq/ReGameDLL_CS/pull/410

**Comment by s1lentq** [comment]
Closing per the last comment.
