### ISSUE TITLE
ReGameDLL 5.7.0.333 remove fix of boost roof bug

### ISSUE THREAD

**Issue by FLYskills360** [s1lentq/ReGameDLL_CS#345]
Already completed !
Working as bugfixed version, but you can use cvar for BUG BOOST
mp_bug_boost_disable "1" = NOT HAVE A BOOST BUG
mp_bug_boost_disable "0" = BOOST BUG IS AVAILABLE
Special for HideNSeek Mode
Link : http://teamcity.rehlds.org/viewType.html?buildTypeId=ReGameDLL_Publish&guest=1&branchSelecto
Edited by stfkolev

**Comment by RauliTop** [comment]
What's the reason of removing a bugfix? 🤔

**Comment by FLYskills360** [comment]
stfkolev How i can put this ? I see u understand me and i am so grateful can you give me ready file i can't understand these codes

**Comment by FLYskills360** [comment]
Where is mp.dll ?

**Comment by stfkolev** [comment]
> Where is mp.dll ?

Learn to use the git correctly.http://teamcity.rehlds.org/viewLog.html?buildId=16365&buildTypeId=ReGameDLL_Publish&guest=1

**Comment by FLYskills360** [comment]
Already completed !
Working as bugfixed version, but you can use cvar for BUG BOOST
mp_bug_boost_disable "1" = NOT HAVE A BOOST BUG
mp_bug_boost_disable "0" = BOOST BUG IS AVAILABLE
Special for HideNSeek Mode

**Comment by popilas** [comment]
Hello, im use regamedll-dist-5.20.0.492-dev version and boost dont work for like hns servers
