### ISSUE TITLE
What do you think about adding these improvements?

### ISSUE THREAD

**Issue by 666JuL** [s1lentq/ReGameDLL_CS#353]
**What do you think about adding these improvements?**

1) add that the player can not place the bomb if it is on top of another player.
2) add the sound Counter Terrorist Win !, after the sound the bomb has been defused!
3) add that while the player is deactivating the bomb it can not jump.
4) add If the bomb has been defused, the model of w_c4.mdl does not disappear, it remains there and at the beginning of the next round it disappears.
5) add that players can not jump and crouch during the freezing period.
6) add that the bomb can not be deactivated through walls or boxes
7) add that players can not place the bomb in boxes, only on the ground, or at a certain distance from the ground so they can not place the bomb in boxes

**Comment by torriz** [comment]
`5. add that players can not jump and crouch during the freezing period`. 
Wtf why?

Pump = bomb? :p

**Comment by 666JuL** [comment]
> `5. add that players can not jump and crouch during the freezing period`.
> Wtf why?

To avoid advantages of some players in some maps.
