### ISSUE TITLE
Add real time ray tracing

### ISSUE THREAD

**Issue by milutinke** [s1lentq/ReGameDLL_CS#370]
Hello, It would be neat if you can add real-time ray tracing (path tracing).

https://github.com/straaljager/OpenCL-path-tracing-tutorial-3-Part-2
https://github.com/LWJGL/lwjgl3-wiki/wiki/2.6.1.-Ray-tracing-with-OpenGL-Compute-Shaders-%28Part-I%29
https://developer.nvidia.com/rtx/raytracing/dxr/DX12-Raytracing-tutorial-Part-1

**Comment by Bounty780** [comment]
Errr... Why would someone NEED RAY-TRACING?

**Comment by Bounty780** [comment]
Welp, I knew it would get closed
