### ISSUE TITLE
Steamers Can't Connect

### ISSUE THREAD

**Issue by Dr-Strange91** [s1lentq/ReGameDLL_CS#377]
I updated server to 

ReHLDS- 3.6.0.71 to ReHLDS- 3.6.0.72
ReGameDLL- 5.7.0.330 to ReGameDLL 5.7.0.345
ReApi- 5.9.0.166 to ReApi- 5.9.0.167

And restarted server. what I was able to witness, as soon as steamers join server they were getting disconnected from server. we are 2 steamers at that moment in server and both got same problem and when I joined with non-steam, there was no problem at all, I was easily able to join, then I reverted settings back:

ReHLDS- 3.6.0.71
ReGameDLL- 5.7.0.330
ReApi- 5.9.0.166

And I was easily able to join back server again with Steam !!

P.S: I use AMX MOD X 1.90 [5247]

**Comment by eat1k** [comment]
Delete Steam Money Fix plugin if you have installed it. It's not needed anymore.

**Comment by Dr-Strange91** [comment]
Yes I was using it !! was it making problem?

**Comment by eat1k** [comment]
> Yes I was using it !! was it making problem?

Yes, it is.

**Comment by Dr-Strange91** [comment]
Oh !! I will update here soon !! just after confirming it, so, everyone could get help here.

**Comment by Dr-Strange91** [comment]
Hello !! Yes !! It fixes the issue but I can't see team mates money or hp with Tab.

![image](https://user-images.githubusercontent.com/35621407/59065972-653ee180-88c7-11e9-87fb-67dcf73980e7.png)
![image (1)](https://user-images.githubusercontent.com/35621407/59066058-961f1680-88c7-11e9-8803-1c837f0e0d91.png)

**Comment by eat1k** [comment]
Because you need to have the last CS 1.6 beta.

**Comment by Dr-Strange91** [comment]
Can I have link to files or how to? Move on beta CS 1.6?

**Comment by eat1k** [comment]
> Can I have link to files or how to? Move on beta CS 1.6?

Steam -> CS 1.6 -> Settings (I don't know how it's in English; it's the last option for me) - Beta-versions - choose Beta.

**Comment by Dr-Strange91** [comment]
And not available for non-steamers? Just steamers for them also with beta update?

**Comment by eat1k** [comment]
> And not available for non-steamers? Just steamers for them also with beta update?

Of course it's not available for non-steam players. At the moment yes, it's available only in beta version. Soon it will be available for each CS 1.6 player (public release).

**Comment by Dr-Strange91** [comment]
Oh Glad To Know !!

Thanks !! @eat1k

**Comment by eat1k** [comment]
I think this issue should be closed.
