### ISSUE TITLE
Problems with metamod-am regamedll combination

### ISSUE THREAD

**Issue by germansassone** [s1lentq/ReGameDLL_CS#378]
Some maps are having trouble with regamedll and metamod-am 1.21.1

For example: as_oilrig, de_airstrip

`L 06/06/2019 - 19:07:00: [META] ERROR: Couldn't find game entity 'item_generic' in game DLL 'cstrike': /home/administrador/steamcmd/servidormix2/cstrike/dlls/cs.so: undefined symbol: item_generic`

**Comment by eat1k** [comment]
Why don’t you install the latest metamod-p or metamod-r?

**Comment by germansassone** [comment]
Sorry my mistake

Solution: The problem was caused by this plugin https://forums.alliedmods.net/showthread.php?t=43979
