### ISSUE TITLE
s1lentq should double-check commit timestamps

### ISSUE THREAD

**Issue by nvtkaszpir** [s1lentq/ReGameDLL_CS#379]
s1lentq please take a look on your machine time settings, you are making commits in the future:

![image](https://user-images.githubusercontent.com/1480252/59126590-b43b5400-8965-11e9-8f27-48e5a72f4b19.png)

this might be a bit problematic :)

**Comment by Karaulov** [comment]
Fatal error 🤣

**Comment by s1lentq** [comment]
fix

**Comment by Karaulov** [comment]
@s1lentq 
![UV3xzqK 1](https://user-images.githubusercontent.com/6445336/59128718-8b21c000-8973-11e9-8bc1-2fbf137e3a7d.png)

**Comment by nvtkaszpir** [comment]
nope ;D

**Comment by s1lentq** [comment]
and now?

**Comment by Karaulov** [comment]
Now fixed)))

Time machine ?)

**Comment by nvtkaszpir** [comment]
\o/ great success!
