### ISSUE TITLE
Issue with kick nonsteam players with latest update?

### ISSUE THREAD

**Issue by Karaulov** [s1lentq/ReGameDLL_CS#380]
https://dev-cs.ru/threads/134/post-60856

RevEmu users will be kicked from server with new messages from Steam Beta client?

Possible need send this messages only for CS 1.6 beta client.

**Comment by s1lentq** [comment]
works fine

```
Protocol version 48
Exe version 1.1.2.6/2.0.0.0 (cstrike)
Exe build: 16:05:41 Jun 15 2009 (4554)
```

I'm not see any reason to worry about support clients jurassic period

**Comment by Karaulov** [comment]
But 99% users with nonsteam? )))

**Comment by s1lentq** [comment]
why do you present it as a non-steam? check above it's really very very non-steam

**Comment by Karaulov** [comment]
I do not use Non-steam client and did not understand. I thought all non-steam clients stopped working :)
If only old protocol stopped works, this is not problem)))
