### ISSUE TITLE
[Feature Request] Make ZBot attack team-mates (Deathmatch FFA)

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#39]
Is it possible to make zbot attack team-mates too? i need to use 3rd-party bot to support Free For All mode.

**Comment by s1lentq** [comment]
i will try to make

**Comment by ViBE-HU** [comment]
is it possible to add Zbot for CS 1.6?

**Comment by s1lentq** [comment]
@ViBE-HU of course, [link](https://github.com/s1lentq/ReGameDLL_CS#how-to-install-zbot-for-cs-16)

**Comment by ViBE-HU** [comment]
@s1lentq woah, that's cool. how can i configure them? are there any infos cause i never used them before. what about the performance? better than any known bots?

**Comment by s1lentq** [comment]
> how can i configure them? are there any infos cause i never used them before.

[https://steamcommunity.com/sharedfiles/filedetails/?id=126699221](There) is a good configuration guide also compatible with this zBot

> what about the performance? better than any known bots?

To be honest, I don't know.
I didn't conducted a benchmark performance.

**Comment by ViBE-HU** [comment]
@s1lentq thanks! can i make any request for enhance them? cause i have some little idea?

**Comment by Phantom-J** [comment]
@ViBE-HU, why not? Enhancement never will not be denied

**Comment by ViBE-HU** [comment]
@Phantom-J i'm not sure what's the exact point of the project. bugfixing or enhancing or both. and maybe my idea can break the compatibility.

**Comment by Phantom-J** [comment]
@ViBE-HU, may be need to create another branch for it?

**Comment by lespaul64** [comment]
@s1lentq 
The bot works, but you need to update reapi module too because when player/bot spawn the game crash instantly. Game not crash if reapi module not loaded.

So here i can say it was reapi issue.

Thanks.
