### ISSUE TITLE
memory replacement alternative

### ISSUE THREAD

**Issue by justgo97** [s1lentq/ReGameDLL_CS#392]
can we have something that allows us to patch game strings like orpheu does but in a more native way ?

```
{
    "name"        : "ResString",
    "library"     : "mod",
    "type"        : "string",
    "memoryType"  : "data"
}
```

**Comment by fant1kua** [comment]
Why do you need memorry patch when you have public API?

**Comment by justgo97** [comment]
for example i want to change player model without increasing precache limit

**Comment by fant1kua** [comment]
But you can change player model without memory patching. Take a look for ReAPI.

**Comment by justgo97** [comment]
i know but it will increase the precache limit...
i want something that doesn't increase the precache limit...

**Comment by eat1k** [comment]
> i know but it will increase the precache limit...
> i want something that doesn't increase the precache limit...

If I understood you correctly, you want to change one default model per other without increasing the limit. Did you try to use Ultimate Unprecacher?

**Comment by Mistrick** [comment]
You just have to wait for God to come to us
https://github.com/ValveSoftware/halflife/issues/12
`Future release`

**Comment by justgo97** [comment]
@eat1k 
If i remember correctly it requires server restart on each change ?

**Comment by justgo97** [comment]
@Mistrick 

well, we can wait more 10 years, no problem xD

**Comment by eat1k** [comment]
> @eat1k
> If i remember correctly it requires server restart on each change ?

What change? You just unprecache the files you don't need. You can also change default files for the ones you need.

**Comment by justgo97** [comment]
I mean for the change to take effect server should be restarted on each change ?

**Comment by eat1k** [comment]
> I mean for the change to take effect server should be restarted on each change ?

Sure.

**Comment by justgo97** [comment]
ok i guess, i will just use orpheu for memory patching and i faced problems will go with Ultimate Unprecacher
