### ISSUE TITLE
mp_round_infinite problem

### ISSUE THREAD

**Issue by Infamous2017** [s1lentq/ReGameDLL_CS#407]
REHLDS + REGAME, REAMXMOD

version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.692-dev
Build date: 02:59:17 Aug 12 2019 (1948)
Build from: https://github.com/dreamstalker/rehlds/commit/c86199f
game version
ReGameDLL version: 5.9.0.379-dev
Build date: 21:25:38 Aug 13 2019
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/411a028

I have an big problem with round infinite ... in game.cfg i added:

mp_round_infinite 0
mp_round_infinite "0"

in server.cfg too.

After this Mapchange and i get the console message:

---------- [admincmd.amxx] Cmd: "set cvar (name "mp_round_infinite") (value "1") Server cvar "mp_round_infinite" = "1" -------------------

How is this possible ?

after that i checked more and found:

---- cstrike/ halflife-cs.fgd ----------

i changed there :

life(string) : "Life (seconds 0 = infinite)" : "1"

--> to

life(string) : "Life (seconds 0 = infinite)" : "0"

but still after server start and mapchange it got changed to 1.

After this i disabled admincmd.amxx and then it was working without problems.

Anyone can help?

**Comment by eat1k** [comment]
> After this i disabled admincmd.amxx and then it was working without problems.

So shouldn't it be a problem of AMXX? Also, you're using ReAMXX, which have bugs and it's not supported anymore. Use AMXX 1.9.0 or 1.10.0.

**Comment by Infamous2017** [comment]
ok thx for answer. will try with 1.9 amxmodx.

**Comment by Infamous2017** [comment]
THX for help. Problem solved.  It was Re-Amxmod.

**Comment by eat1k** [comment]
> THX for help. Problem solved. It was Re-Amxmod.

Close the issue then.
