### ISSUE TITLE
[Feature Request] Make it possible to Zbot's leave only when a player join to the gameplay

### ISSUE THREAD

**Issue by ViBE-HU** [s1lentq/ReGameDLL_CS#41]
The basic idea is that the well known bots leave when a player join to a server. It's a very popular behavior which is very annoying nowadays when CS 1.6 is very orphaned and players come and go. PODBot and YaPBot act the same. It would be good if we can set how the bots behave when a player join. For example if a server admin or a player would like to spectate what's going on the bots should not leave just stay in game till the spectator join to a team. It could really help to keep the headcount when players hop on and hop off and helps to keep the unity.

**Comment by s1lentq** [comment]
you mean about this?

```
bot_auto_vacate [0, 1] 
Set to 1 to force bots to automatically leave the server to make room for human players (set to 0 to disable).
```

**Comment by ViBE-HU** [comment]
@s1lentq yes.
