### ISSUE TITLE
[Bug] Kevlar pickup

### ISSUE THREAD

**Issue by eat1k** [s1lentq/ReGameDLL_CS#423]
When you already have 100 armor, you can pickup more armor but you still have 100 armor, I think touch should be blocked.

Reference: https://github.com/ValveSoftware/halflife/issues/2175

**Comment by eat1k** [comment]
Fix proposed, thanks to @theshadowz and @s1lentq:

https://github.com/s1lentq/ReGameDLL_CS/blob/26db32e8845647cf024e38f11cb3da3071ac0dd1/regamedll/dlls/items.cpp#L381

```
#ifdef REGAMEDLL_FIXES
	if (pPlayer->m_iKevlar == ARMOR_VESTHELM)
		return FALSE;
	if (pPlayer->m_iKevlar == ARMOR_KEVLAR && pPlayer->pev->armorvalue >= MAX_NORMAL_BATTERY)
		return FALSE;
#endif
```

https://github.com/s1lentq/ReGameDLL_CS/blob/26db32e8845647cf024e38f11cb3da3071ac0dd1/regamedll/dlls/items.cpp#L424

```
#ifdef REGAMEDLL_FIXES
	if(pPlayer->m_iKevlar == ARMOR_VESTHELM && pPlayer->pev->armorvalue >= MAX_NORMAL_BATTERY)
		return FALSE;
#endif
```

https://github.com/s1lentq/ReGameDLL_CS/blob/a2a6997278dc3888be92d1715fe21ad64cacadcf/regamedll/dlls/weapons.cpp#L2324

```
case ARMOURY_KEVLAR:
{
#ifdef REGAMEDLL_FIXES
	if (pToucher->m_iKevlar != ARMOR_NONE && pToucher->pev->armorvalue >= MAX_NORMAL_BATTERY)
#else
	if (pToucher->m_iKevlar == ARMOR_KEVLAR)
#endif
	{
		return;
	}

	pToucher->GiveNamedItem("item_kevlar");
	m_iCount--;
	break;
}
```

https://github.com/s1lentq/ReGameDLL_CS/blob/a2a6997278dc3888be92d1715fe21ad64cacadcf/regamedll/dlls/weapons.cpp#L2333

```
case ARMOURY_ASSAULT:
{
	if (pToucher->m_iKevlar == ARMOR_VESTHELM
#ifdef REGAMEDLL_FIXES
	&& pToucher->pev->armorvalue >= MAX_NORMAL_BATTERY
#endif
	)
	{
		return;
	}

	pToucher->GiveNamedItem("item_assaultsuit");
	m_iCount--;
	break;
}
```

**Comment by theshadowz** [comment]
I think, it should be closed now

**Comment by eat1k** [comment]
@s1lentq @Vaqtincha why this checks instead of the proposed one?

https://github.com/s1lentq/ReGameDLL_CS/commit/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2#diff-9f81f638cfc50144f27b9b4fa2707cc3R383

If I understand correctly, we will have a bug with this check.

Example: we have 80 of ARMOR_VESTHELM and we try to pick up ARMOR_KEVLAR, it shouldn't be picked up, but as I understand this check, it will allow to pick up and we'll have 100 of ARMOR_KEVLAR instead of ARMOR_VESTHELM. Isn't it a bug?

**Comment by Vaqtincha** [comment]
@eat1k 
Yes, this is not a bug. We can pick up  (if armor is less than 100) and the type of armor does not change.

https://github.com/s1lentq/ReGameDLL_CS/commit/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388

**Comment by eat1k** [comment]
> @eat1k
> Yes, this is not a bug. We can pick up (if armor is less than 100) and the type of armor does not change.
> 
> [6955ae9#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388](https://github.com/s1lentq/ReGameDLL_CS/commit/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388)

https://github.com/s1lentq/ReGameDLL_CS/blob/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2/regamedll/dlls/weapons.cpp#L2327-L2331

If we have ARMOR_VESTHELM less than 100 we'll be able to touch ARMOR_KEVLAR and then ARMOR_VESTHELM will be changed to ARMOR_KEVLAR, isn't it?

**Comment by Vaqtincha** [comment]
@eat1k https://github.com/s1lentq/ReGameDLL_CS/commit/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388

**Comment by eat1k** [comment]
> @eat1k [6955ae9#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388](https://github.com/s1lentq/ReGameDLL_CS/commit/6955ae9f65ec2b51576cbafd95f8ce32800ac3c2#diff-9f81f638cfc50144f27b9b4fa2707cc3R387-R388)

Ah, yes. I misunderstood. Seems fine.
