### ISSUE TITLE
hlds_run: 92: shift: can't shift that many

### ISSUE THREAD

**Issue by Ant1Lamer** [s1lentq/ReGameDLL_CS#440]
Hellol i have problem update regame with lastest version and put in command console -beta for money and health in scoreboard and server not running this is error hlds_run: 92: shift: can't shift that many on linux i try on windwos and everything is okay. Any solution for this problem ?

**Comment by GiovaniFerraroTrivelli** [comment]
I am having the same problem (Ubuntu 16.04):
```./hlds_run: 92: shift: can't shift that many```

This only happens when I run with -beta.
