### ISSUE TITLE
mp_scoreboard_showhealth and mp_scoreboard_showmoney doesn't works on the server!

### ISSUE THREAD

**Issue by stambeto2006** [s1lentq/ReGameDLL_CS#442]
![Capture](https://user-images.githubusercontent.com/5206809/67618683-2b7d6180-f7fb-11e9-9532-2cd9085da652.JPG)
@s1lentq  I'm using the latest version of **ReGameDLL 5.11.0.421-dev+m** and the following two cvars on the server do not work:
**mp_scoreboard_showhealth**

**mp_scoreboard_showmoney**

**Comment by wopox1337** [comment]
@stambeto2006 launch server with -beta parameter

**Comment by stambeto2006** [comment]
@wopox1337 Thank you! :)
