### ISSUE TITLE
Bot not kicked if real player come

### ISSUE THREAD

**Issue by jokypapa** [s1lentq/ReGameDLL_CS#447]
Hy guys, 

For the first time, I apologize for my poor English!

I have some errors on the server and have no idea what else to doing. I've tried several versions, but it doesn't work. 

If a player comes in, and chooses a team(CT or T), the server will not kick the bots. 
It looks like that: CT: 6 players (all bot), T: 7 players with 6 bots!

This problem exists with:
- Regamedll 5.11.0.424/425/420
- Amxmodx 1.9.0 5260/5262
- Amxmodx 1.10.0 5388
- bot_join_after_player 1/0
- bot_join_delay 0/10/20
- bot_quota_mode normal/fill

I haven´t any idea!! Anything?

The current configuration:
`version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.692-dev
Build date: 18:58:01 Sep 21 2019 (1988)
Build from: https://github.com/dreamstalker/rehlds/commit/e7232be

game version
ReGameDLL version: 5.11.0.420-dev+m
Build date: 12:57:16 Oct  9 2019
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/4996564

meta version
Metamod-r v1.3.0.128, API (5:13)
Metamod-r build: 17:47:54 Aug 24 2018
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/0cf2f70

meta list
Currently loaded plugins:
      description      stat pend  file                        vers             src  load  unload
 [ 1] Reunion          RUN   -    reunion_mm_i386.so          v0.1.0.92        ini  Start Never
 [ 2] VoiceTranscoder  RUN   -    VoiceTranscoder.so          v2017RC3         ini  ANY   ANY
 [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.so          v1.9.0.5261      ini  Start ANY
 [ 4] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so      v0.1.6           ini  Start Never
 [ 5] Rechecker        RUN   -    rechecker_mm_i386.so        v2.5             ini  Chlvl ANY
 [ 6] WHBlocker        RUN   -    whblocker_mm_i386.so        v1.5.696         ini  Chlvl ANY
 [ 7] ReSemiclip       RUN   -    resemiclip_mm_i386.so       v2.3.9           ini  Chlvl ANY
 [ 8] MySQL            RUN   -    mysql_amxx_i386.so          v1.9.0.5261      pl3  ANY   ANY
 [ 9] ReAPI            RUN   -    reapi_amxx_i386.so          v5.10.0.188-dev  pl3  ANY   Never
 [10] hackdetector     RUN   -    hackdetector_amxx_i386.so   v0.15.328.lite   pl3  ANY   ANY
 [11] ReAimDetector    RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl3  ANY   Never
 [12] VTC AMXX API     RUN   -    VtcApi_amxx_i386.so         v2017 RC         pl3  ANY   ANY
 [13] Fun              RUN   -    fun_amxx_i386.so            v1.9.0.5261      pl3  ANY   ANY
 [14] FakeMeta         RUN   -    fakemeta_amxx_i386.so       v1.9.0.5261      pl3  ANY   ANY
 [15] GeoIP            RUN   -    geoip_amxx_i386.so          v1.9.0.5261      pl3  ANY   ANY
 [16] Engine           RUN   -    engine_amxx_i386.so         v1.9.0.5261      pl3  ANY   ANY
 [17] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5261      pl3  ANY   ANY
 [18] CStrike          RUN   -    cstrike_amxx_i386.so        v1.9.0.5261      pl3  ANY   ANY
 [19] CSX              RUN   -    csx_amxx_i386.so            v1.9.0.5261      pl3  ANY   ANY
19 plugins, 19 running`

**Comment by wopox1337** [comment]
Confirmed at local tests also with hltv

**Comment by 666JuL** [comment]
It is true, also if bot_join_after_player 0 is placed when starting the server, it closes

**Comment by RauliTop** [comment]
Not related. But be careful and update your VoiceTranscoder to RC4

**Comment by jokypapa** [comment]
If you need,  I can make a HLTV at the weekend. 
And if we are here: there is also the problem that if bot_join_after_player 1 and the last player leave the server, not all bots will be disconnected from the server.

**Comment by afwn90cj93201nixr2e1re** [comment]
He is stupid kid, just leave his comments.

**Comment by jokypapa** [comment]
Sorry, but my question is stupid or what? :)

**Comment by afwn90cj93201nixr2e1re** [comment]
Check comments order, im not about you.
![изображение](https://user-images.githubusercontent.com/9306996/68761810-51459b80-062e-11ea-93bc-145b37219524.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
Can you explain how it's should works? Coz i don't see anything wrong in this behaviour.

> 6 vs 6 bots
> player joined
> 1 bot should be kicked

That's what you want?
