### ISSUE TITLE
[MSVS] '_Bool': undeclared identifier

### ISSUE THREAD

**Issue by souvikdas95** [s1lentq/ReGameDLL_CS#45]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2976	'std::vector_vs6': too few template arguments	ReGameDLL	E:\Games\Counter-Strike\Module Coding\ReGameDLL_CS-master\regamedll\hookers\stl\vector	564	

Error	C2065	'_Bool': undeclared identifier	ReGameDLL	E:\Games\Counter-Strike\Module Coding\ReGameDLL_CS-master\regamedll\hookers\stl\vector	245	

Error	C2923	'std::vector_vs6': '_Bool' is not a valid template type argument for parameter '_Ty'	ReGameDLL	E:\Games\Counter-Strike\Module Coding\ReGameDLL_CS-master\regamedll\hookers\stl\vector	245	`	

Using Visual Studio 2015

**Comment by s1lentq** [comment]
you can use solution configurations only these Debug MP/Release MP
