### ISSUE TITLE
Outdated Compiled Binaries

### ISSUE THREAD

**Issue by hashnimmo** [s1lentq/ReGameDLL_CS#450]
So the latest official commit for ReGameDLL is 12 days ago from this moment. Doesn't it get compiled immediately and added to the [compiled binary index](http://nexus.rehlds.org/nexus/content/repositories/regamedll-dev/regamedll/regamedll/)? The last update is from August 26, 2019.

Or aren't these updates ready to be released to the public?

**Comment by Mistrick** [comment]
Releases sorted by name and not like windows sort files.
`5.12.0.425-dev/ | Sat Nov 02 10:03:01 CET 2019`
Last release exists in folder.

**Comment by hashnimmo** [comment]
Thank you.
