### ISSUE TITLE
Can't join team if there are not enough spawn points 

### ISSUE THREAD

**Issue by Karaulov** [s1lentq/ReGameDLL_CS#456]
Possible to fix it? Or add cvar to support ?

**Comment by fant1kua** [comment]
https://github.com/s1lentq/ReGameDLL_CS/blob/49965644c3a23c1ce2afd6f3d5463fa9f6522d58/regamedll/dlls/multiplay_gamerules.cpp#L2046

**Comment by Karaulov** [comment]
> https://github.com/s1lentq/ReGameDLL_CS/blob/49965644c3a23c1ce2afd6f3d5463fa9f6522d58/regamedll/dlls/multiplay_gamerules.cpp#L2046

how to hook this function and always return true ?

**Comment by Karaulov** [comment]
@fant1kua this https://github.com/s1lentq/ReGameDLL_CS/pull/458 can fix this problem ?

**Comment by fant1kua** [comment]
This is only yiur problem. Don't create PR that crash game. Make your own fork and do what you want here. Not in original regame. Or beter choise is to make more spawns. I belive s1lent will close your PR withot merge

**Comment by Karaulov** [comment]
> This is only yiur problem. Don't create PR that crash game. Make your own fork and do what you want here. Not in original regame. Or beter choise is to make more spawns. I belive s1lent will close your PR withot merge

@fant1kua no.
