### ISSUE TITLE
Half Life maps is broken ?

### ISSUE THREAD

**Issue by Karaulov** [s1lentq/ReGameDLL_CS#460]
Half Life maps is broken ?

(многие элементы half life карт не работают, на crossfire бесконечная сирена, а gasworks вообще сервер крашит)

Как в них играть :( :( :( Кажется раньше такого не было :(

**Comment by Giferns** [comment]
How does this question relate to the regamedll?

**Comment by Karaulov** [comment]
Раньше работало теперь нет, почему? :( Верните режим совместимости :(

**Comment by theshadowz** [comment]
Whats the attitude between regamedll and your problem?

**Comment by Vaqtincha** [comment]
шизик.

**Comment by Karaulov** [comment]
@Vaqtincha я почти уверен что раньше играл на regamedll в **crossfire** (с заранее созданными спаунами) и там работал бункер можно было взорвать)))

Сейчас  там бесконечная сирена, а еще если меняешь карту на **gasworks** получаешь краш сервера))

**Comment by Karaulov** [comment]
А проверил оригинал, до первого рестарта все работает)) Значит так и должно быть :(
