### ISSUE TITLE
[feature request] add screenfade on kill like into CS:GO

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#463]
effect like in CS:GO
https://www.youtube.com/watch?v=Gp9CR-xEKTw

**Comment by Vaqtincha** [comment]
засунь в жопу свою идею

**Comment by wopox1337** [comment]
@Vaqtincha Раздвигай 🌚

**Comment by Vaqtincha** [comment]
скажи почему ты такой неадекватный ? и зачем мой каждый комм скриншотит и скинуть в чат ? я то знаю что ты мой фанат и многое учился от меня но непонятно из за чего твой пукан горит.

**Comment by RauliTop** [comment]
You can do it by plugins.

Don't need to have this on ReGame
