### ISSUE TITLE
spelling mistake on naming

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#464]
https://github.com/s1lentq/ReGameDLL_CS/search?q=CAMERA_MODE_SPEC_ONLY_FRIST_PERSON&unscoped_q=CAMERA_MODE_SPEC_ONLY_FRIST_PERSON

CAMERA_MODE_SPEC_ONLY_ **FRIST** _PERSON -> CAMERA_MODE_SPEC_ONLY_ **FIRST** _PERSON

**Comment by Vaqtincha** [comment]
о чем ты говоришь недоумок ?

**Comment by fl0werD** [comment]
Он говорит, что ты не можешь прочитать название топика и его суть, а именно ошибку в названии макроса.

**Comment by Vaqtincha** [comment]
Ты один такой "умный" (нет). Но ты не понял вопроса.
Ты лох из гей кс.

**Comment by Vaqtincha** [comment]
Похуй на название макроса когда есть более важные проблемы

**Comment by Vaqtincha** [comment]
Я теперь назову тебя проституткой и знаешь почему.

**Comment by fl0werD** [comment]
Зачем называть меня своей матерью?

**Comment by Vaqtincha** [comment]
Ты не мужик просто школьник. Родителей не надо трогать (твоя мама не учила ?)

Ты готовь отсосать за какие то статусы "разрабатчика" форуме.

**Comment by Vaqtincha** [comment]
У тебя горит как и вся гейкс. Вы сидите в чате и обсуждаете меня и нихуя не делаете для развитие игры. Смотрите на себя на кого вы теперь похожи.

**Comment by Vaqtincha** [comment]
Неблагодарные твары все забыли. Забыли как я многое сделал для паблика бесплатно для всем когда всякие фловеры пилили свой приват (говнокод без исходника) на уголке.

**Comment by fl0werD** [comment]
Тебя никто не просил пилить в паблик. А что сделано, то сделано, не обижайся. И горит у тебя, школьник. Может тебя в чат добавить? Про твою мать повторяю.

**Comment by Vaqtincha** [comment]
Твой посл. комм показал твой уровень. Какой ты даун. тебя дали разработчика и посмеялись над тобой. Ты даже себя уважать не умеешь. С такими типами как ты вести разговор лишено здравого смысла. Давно всем ясно что ты клоун и неудачник (я думаю в жизне ты лох)

**Comment by fl0werD** [comment]
Опять что ли про мать повторить?

**Comment by Vaqtincha** [comment]
я не хочу повторить что ты шлюха. не хочу оскорблять классного человека

**Comment by fl0werD** [comment]
Передай тогда своей маме привет и что она классный человек, в отличии от ее сына, который злится на всех из-за того, что не может оформить пулл реквест правильно.

**Comment by Vaqtincha** [comment]
где не правельно. каком месте.

**Comment by fl0werD** [comment]
Да практически везде, то ты всё своё говно в один коммит кидаешь, то ноешь и срываешься на пару с карауловым, что не принимают, закрывая пулл. Истерика одним словом. Все мы прекрасно понимаем, что ты пытаешься получить статус разработчика, как у меня, но пока не выходит.

**Comment by fl0werD** [comment]
#465

**Comment by fl0werD** [comment]
https://github.com/nagist/cs16nd/blob/cb03c59eaf076b0b4bb2eb8b6a05179651d7763c/dlls/game.h#L53

It seems to me it needs REGAMEDLL_FIXES.
