### ISSUE TITLE
mp_round_restart_delay and mp_roundover

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#468]
it would be nice if after a extended 'mp_roundover 0' map is finished, the mapchange to the nextmap  waits the 'mp_round_restart_delay' value.

**Comment by SmileYzn** [comment]
I think you can reach this using mp_chattime if cvar name is correct, also need extra plugin to block SVC_INTERMISSION message...

**Comment by fred0r** [comment]
It turned out that i had multiple amx-plugins trying to manage end-round extension and that was the cause for that 'misbehavior'
