### ISSUE TITLE
[feature request] Change time after death to switch camera

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#484]
Need a new CVar
https://www.youtube.com/watch?v=9DAISSlRfz4

https://github.com/s1lentq/ReGameDLL_CS/blob/7983a9d9293b65d359b7971305362175ba3f277e/regamedll/dlls/player.cpp#L3602
m_fDeadTime + **3**

**Comment by Vaqtincha** [comment]
bred

**Comment by RauliTop** [comment]
Good addition!
