### ISSUE TITLE
Add Option : Auto Join Team

### ISSUE THREAD

**Issue by Slinfy97** [s1lentq/ReGameDLL_CS#49]
Greetings, writing about the cvar mp_auto_join_team , i would like to suggest an addon - exception for the admins (they can choose whether they can join the game or spectate, for example at public server they need to switch back to spec every map), it is working very fine and nice to have the cvar , but just give it a thought.

**Comment by souvikdas95** [comment]
Not possible. It's not related to ReGameDLL at all. It can be fixed by making a plugin that will not let the player spawn if he is an admin upon game join. Then, force team unassigned and invoke message that brings the teammenu on that player.
