### ISSUE TITLE
[Feature] mp_scoreboard_defusekit

### ISSUE THREAD

**Issue by SanjaySRocks** [s1lentq/ReGameDLL_CS#492]
Request to add mp_scoreboard_defusekit so can be disabled becuase its totally useless in pub servers because they have 16000$ always so they do have kits.

Also i found a bug that Dead T player can see the defuse kit status of CT.

Please fix and add this feature.

Ty

**Comment by etojuice** [comment]
Duplicate of #472. Resolved with 6ff75da
