### ISSUE TITLE
Wrong black Screenfade on server joining (`mp_fadetoblack 2`)

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#501]
need to add `#ifdef REGAMEDLL_ADD` block with CVar checking `mp_fadetoblack == 1`
there: https://github.com/s1lentq/ReGameDLL_CS/blob/49965644c3a23c1ce2afd6f3d5463fa9f6522d58/regamedll/dlls/API/CSPlayer.cpp#L60-L64
and there: https://github.com/s1lentq/ReGameDLL_CS/blob/1f615d36b51c7f3259a246c5793bd06fbafbef9f/regamedll/dlls/client.cpp#L1904-L1908

**Comment by Vaqtincha** [comment]
Nado pobistree prinimat vawix pr 4tobi bagov bilo more. Tiper jvite s etim. :D
