### ISSUE TITLE
[bug] Observers don't blind from flash (mp_fadetoblack 2)

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#506]
Need to fix there
https://github.com/s1lentq/ReGameDLL_CS/blob/c2f62eb98a2280ee6b18ec9cd7281ab511b1ec1c/regamedll/dlls/combat.cpp#L7-L17

**Comment by Vaqtincha** [comment]
stolko bagov izza odnogo sranogo commita.
