### ISSUE TITLE
[bug] latest version is bugged

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#511]
since https://github.com/s1lentq/ReGameDLL_CS/commit/8c82c6236ed4826be9abeb5a4ec2d2d8498f23aa ppl are unable to hear steps - to reload - to hear/see shots

**Comment by Vaqtincha** [comment]
chi oma tutani pipi to saskan miola falkiu

**Comment by fred0r** [comment]
since https://github.com/s1lentq/ReGameDLL_CS/commit/8c82c6236ed4826be9abeb5a4ec2d2d8498f23aa the Weapon is also left-handed and its even impossible to shoot.
Its really hard for me to believe that i'm the only one facing these Issues :/
I also tried to gcc-build the newest RegameDLL_CS, but its still not useable to me.

**Comment by fant1kua** [comment]
Maybe you have some plugin that blocks all events

**Comment by fred0r** [comment]
@fant1kua 
Could you please take a look ?
The current Plugins/Modules are running for ages, and i did recompile them with each new amxx/reapi version.
Amxx-Modules:
          [ 1] MySQL                   1.9.0.5263  AMX Mod X Dev Team   running    
          [ 2] ReAPI                   5.12.0.192  Asmodai & s1lent     running    
          [ 3] Ham Sandwich            1.9.0.5263  AMX Mod X Dev Team   running    
          [ 4] CSX                     1.9.0.5263  AMX Mod X Dev Team   running    
          [ 5] CStrike                 1.9.0.5263  AMX Mod X Dev Team   running    
          [ 6] FakeMeta                1.9.0.5263  AMX Mod X Dev Team   running    
          [ 7] Engine                  1.9.0.5263  AMX Mod X Dev Team   running    
          [ 8] Fun                     1.9.0.5263  AMX Mod X Dev Team   running    
          [ 9] ReAimDetector           0.2.2       ReHLDS Team          running    
          [10] RegEx                   1.9.0.5263  AMX Mod X Dev Team   running    
          [11] Sockets                 1.9.0.5263  AMX Mod X Dev Team   running    

Amxx-Plugins:
          [  1] AMXBans                 5.0         YoMama/Lux & lan  amxbans5.amxx    running  
          [  2] Hide                    1.1         xPaw              hide.amxx        running  
          [  3] Admin Base              1.9.0.5263  AMXX Dev Team     admin.amxx       running  
          [  4] Admin Commands          1.9.0.5263  AMXX Dev Team     admincmd.amxx    running  
          [  5] Admin Help              1.9.0.5263  AMXX Dev Team     adminhelp.amxx   running  
          [  6] Ultimate RSlots         1.0         OneEyed           ultimate_rslot.  running  
          [  7] Multi-Lingual System    1.9.0.5263  AMXX Dev Team     multilingual.am  running  
          [  8] Menus Front-End         1.9.0.5263  AMXX Dev Team     menufront.amxx   running  
          [  9] Commands Menu           1.9.0.5263  AMXX Dev Team     cmdmenu.amxx     running  
          [ 10] Players Menu            1.9.0.5263  AMXX Dev Team     plmenu.amxx      running  
          [ 11] Maps Menu               1.9.0.5263  AMXX Dev Team     mapsmenu.amxx    running  
          [ 12] Admin Chat              1.9.0.5263  AMXX Dev Team     adminchat.amxx   running  
          [ 13] Anti Flood              1.9.0.5263  AMXX Dev Team     antiflood.amxx   running  
          [ 14] Info. Messages          1.9.0.5263  AMXX Dev Team     imessage.amxx    running  
	  [ 15] Admin Votes             1.9.0.5263  AMXX Dev Team     adminvote.amxx   running  
          [ 16] Pause Plugins           1.9.0.5263  AMXX Dev Team     pausecfg.amxx    running  
          [ 17] Stats Configuration     1.9.0.5263  AMXX Dev Team     statscfg.amxx    running  
          [ 18] Items Restrict          1.1         s1lent            items_restrict.  running  
          [ 19] StatsX                  1.9.0.5263  AMXX Dev Team     statsx.amxx      running  
          [ 20] CS Misc. Stats          1.9.0.5263  AMXX Dev Team     miscstats_mod.a  running  
          [ 21] gameME Plugin           2.4         TTS Oetzel & Goe  gameme_cstrike.  running  
          [ 22] Map Spawns Editor       1.0.16      iG_os             Map_Spawns_Edit  running  
          [ 23] Loading Sound           0.1         Fusion            loadsound0.3.am  running  
          [ 24] Admin ESP               1.5b_mini   KoST              admin_esp_mini.  running  
          [ 25] LAN Notifier            1.0a        Brad Jones        lann.amxx        running  
          [ 26] Play or Be Kicked       1.5.243     Brad Jones        pbk1.5.243.amxx  running  
          [ 27] Auto Restart vl         1.3         vato loco [GE-S]  auto_restart_vl  running  
          [ 28] Sank Sounds Plugin      1.6.6d      White Panther, L  sank_sounds_1.6  running  
          [ 29] Team Balancer           1.8b3       Ptahhotep         ptb-1.8b3.amxx   running  
	  [ 30] AWP/AUTO Limit (Team/W  1.3         SuicideDog/MattO  sniperlimit.amx  running  
          [ 31] High Ping Kicker        1.0         Shadow/Bo0m!      amx_hpk.amxx     running  
          [ 32] JETB                    0.5         Janzert           jetb.amxx        running  
          [ 33] AdThemes                1.8         Vet(3TT3V)        adthemes1.8.amx  running  
          [ 34] Descriptive 'Fire in t  0.1         VEN               descriptive_fir  running  
          [ 35] c4 timer                1.1         cheap_suit        c4timer.amxx     running  
          [ 36] Flash Remote Control    12.0        OT                flashbang_remot  running  
          [ 37] Alltalk Limit           0.1         dev00             alltalklimit.am  running  
          [ 38] HLTV AutoRecord         1.7         Dr.Aft            hltv_autorecord  running  
          [ 39] Reconnect Features      0.2.4 BETA  ConnorMcLeod      reconnect_featu  running  
          [ 40] Admin RestartRound      0.9.2       f117bomb          amx_restartroun  running  
          [ 41] Files Check             1.0         ConnorMcLeod      filescheck.amxx  running  
          [ 42] Galileo                 v5.9.1-929  Brad Jones/Addon  galileo.amxx     running  
          [ 43] scorediffcmd            0.1         pietrmar          scorediff.amxx   running  
          [ 44] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running  
	  [ 45] [ReAPI] AdminFreeLook   1.0         ReHLDS Team       adminfreelook.a  running  
          [ 46] Whose the weapon?       2.1         Yek'-ta           WhoseTheWeapon.  running  
          [ 47] ATAC                    3.0.1       ATAC Team         atac.amxx        running  
          [ 48] Slap                    1.1         ATAC Team         atac_slap.amxx   running  
          [ 49] Slap2One                1.1         ATAC Team         atac_slap2one.a  running  
          [ 50] Slay                    1.1         ATAC Team         atac_slay.amxx   running  
          [ 51] Spawn Slay              1.0         ATAC Team         atac_spawnslay.  running  
          [ 52] Hud Messages            1.1         ATAC Team         atac_hudmsg.amx  running  
          [ 53] Team Attack             1.0         ATAC Team         atac_ta.amxx     running  
          [ 54] ATAC AMXBans            1.1         ATAC Team         atac_amxbans.am  running

**Comment by fred0r** [comment]
> the Weapon is also left-handed and its even impossible to shoot.
was wrong on that - only after spawn the weapon is in the wrong hand.
its possible to switch between pistol and knife, but its impossible to use them.

**Comment by fred0r** [comment]
narrowed it down to 'Whose the weapon? 2.1'
this Plugin prevented the latest Regame_dll_cs from working on my server.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/76589960-c2656480-64e3-11ea-86bc-1b8880f0f9f3.png)


Lol. Author is too dumb.
Whach u wanna by this plugin?
Just show whose weapon you just picked up? or what?

**Comment by fred0r** [comment]
right

**Comment by afwn90cj93201nixr2e1re** [comment]
ok, we gonna try to write some another.

**Comment by fred0r** [comment]
do you have multiple personalities, or who is "we"?

**Comment by fred0r** [comment]
but i'm still wondering how this 'malformed' plugin is able to harm regamedll_cs in such a 'serious' way - to make it unuseable.

**Comment by afwn90cj93201nixr2e1re** [comment]
you can just try to open provided link and check who make's translations, most of them scripters, and we know each other. So, but here's, yep, seems like im only one who understand the problem.
Im gonna rewrite it.

**Comment by afwn90cj93201nixr2e1re** [comment]
It's changes weapon id, inside classname(CSBase_Player_Weapon), that's why it's bugged little bit, instead of this we should take free members on CSBaseEntity class.

**Comment by fred0r** [comment]
thx

**Comment by afwn90cj93201nixr2e1re** [comment]
So, if player 1 dropped weapon, second player get it, and then dropped, who is the weapon owner? Player 1 or player 2?

**Comment by fred0r** [comment]
player2 ofc

**Comment by fred0r** [comment]
or both ? 
Player1 in ( ) after player2 ?

**Comment by fred0r** [comment]
'last player' would be really nice - everything else isnt really needed

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok.

**Comment by fred0r** [comment]
thx

**Comment by fred0r** [comment]
did you had time for looking into that ?

**Comment by afwn90cj93201nixr2e1re** [comment]
Yep. Try this one. If it's works post somewhere.

https://hastebin.com/dobajaciji.cs
https://hastebin.com/ufedekilap.makefile


> It's changes weapon id, inside classname(CSBase_Player_Weapon), that's why it's bugged little bit, instead of this we should take free members from CSBaseEntity class.

About this and why this issue caused only after update, that's coz set_item_info wasn't implemented till the end, and now it's work's as expected.

**Comment by afwn90cj93201nixr2e1re** [comment]
> 'last player' would be nice - everything else isnt really needed

oh, lol
wait minute...

**Comment by afwn90cj93201nixr2e1re** [comment]
Also you should uncomment ADDITIONAL_CHECKS  and ADDITIONAL_CHECKS_RESET_STATE (optional)
if ur sure that you doesnt have 2 bill. connects to the server until restart (not map restart).

**Comment by fred0r** [comment]
thx - i'll try it and report back

**Comment by fred0r** [comment]
Maybe i'm too dumb, but i cant compile:
```
WhoseWeapon2.sma(37) : error 017: undefined symbol "id"
WhoseWeapon2.sma(53) : error 017: undefined symbol "id"

```

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/76699323-5716c080-66a4-11ea-9253-192809bfabf8.png)


There are 2 version, one without owner rewriting, another one with.

They r exactly same, only owner rewriting is diff.

>  Updated version compiles fine, but can you please post me also a version with that 'sure that not 2 billion'-variant ?

i really dont get.
> that you doesnt have 2 bill. connects to the server until restart 

2 billion connects.

So, now i get u. Little typo on this lines, `id` -> `pPlayer`.

With rewriting:
https://hastebin.com/vacahufiqi.cs

Without:
https://hastebin.com/jirolotume.cs

> Where to add these language-variables ?

Just find `register_dictionary` function in code and create file with that name, upload to `lang` dir (`data/lang`).

**Comment by fred0r** [comment]
Could you pls repost all components, because all of your links currently show a empty screen.

**Comment by afwn90cj93201nixr2e1re** [comment]
x D, hastebin is down, i haven't mirrors, seems like we loosed it. Lol.
So, just post here last copies. Im gonna try to fix them.

**Comment by fred0r** [comment]
I only have one variant:
https://crypt.is-by.us/?8498b20bb0f86ca0#oOdhMsHsbE6xVOGG9YB/1vnbjiTW/4fwA83PxHhqV4U=
The lang-entries are lost on my side.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://crypt.is-by.us/?22387aa05ac7fa1c#8+lJOSpkQskJasCUsgIGVl40r/P9TjB8DKCsGBdndso=

btw im suggest to wait untill hastebin gonna start up, im not sure but i think i make more changes on latest hastes.

**Comment by fred0r** [comment]
thx - lets wait then.

**Comment by fred0r** [comment]
hastebin is back online
