### ISSUE TITLE
mp_scoreboard_showmoney and mp_scoreboard_showhealth -1 not working

### ISSUE THREAD

**Issue by 2020karaulov2020** [s1lentq/ReGameDLL_CS#522]
mp_scoreboard_showmoney и mp_scoreboard_showhealth -1 не отменяют регистрацию этих пакетов.

**Comment by 2020karaulov2020** [comment]
хотя хрен с ними)

**Comment by seypaa** [comment]
2020 versiyon karaulov you'r welcome
