### ISSUE TITLE
cant install it

### ISSUE THREAD

**Issue by KevinH404** [s1lentq/ReGameDLL_CS#523]
I downloaded the file
https://github.com/s1lentq/ReGameDLL_CS/releases/download/5.15.0.457/regamedll-dist-5.15.0.457-dev.zip
copied mp.dll from
Desktop\regamedll-dist-5.15.0.457-dev\bin\win32\cstrike\dlls
to
C:\Program Files (x86)\Steam\steamapps\common\Half-Life\cstrike\dlls

Run game from steam, nothing really happens. I follow the instructions here:
https://github.com/s1lentq/ReGameDLL_CS

> **How can use it?**
> ReGameDLL_CS is fully compatible with official mod CS 1.6 / CZero by Valve. All you have to do is to download binaries and replace original mp.dll/cs.so

**Comment by fl0werD** [comment]
Do you have errors? Try to write "game version" in console.

**Comment by KevinH404** [comment]
@fl0werD Hi, thanks for your help.
"game version" didnt do anything, "versino" returned the following:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 15:17:55 Jul 24 2019 (8308)

**Comment by KevinH404** [comment]
@fl0werD with the original dll i get the same output.

**Comment by KevinH404** [comment]
@fl0werD I ended up following instructions here:
https://steamcommunity.com/sharedfiles/filedetails/?id=1725204346

works perfect.
