### ISSUE TITLE
 Host_Error: Consistency:  server sent too many filenames

### ISSUE THREAD

**Issue by NamVr** [s1lentq/ReGameDLL_CS#546]
It happens when I join my CS 1.6 Server.
Specs::

> version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.693-dev
Build date: 18:20:58 Jan 28 2020 (2117)
Build from: https://github.com/dreamstalker/rehlds/commit/c4cecf5
amxx version
AMX Mod X 1.8.3-dev+4739 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: May 10 2015 08:13:56
Built from: https://github.com/alliedmodders/amxmodx/commit/c5f6e26
Build ID: 4739:c5f6e26
Core mode: JIT+ASM32
game version
ReGameDLL version: 5.17.0.466-dev
Build date: 02:56:24 May 27 2020
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/bffb373
meta version
Metamod-r v1.3.73, API (5:13)
Metamod-r build: 00:14:56 Jul  7 2017 (1.3.73)
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/daea1f8 (asmodai)`

Also tried mp_consistency 0 and 1 both. Nothing happens either from server side or client side.

**Comment by WPMGPRoSToTeMa** [comment]
What metamod plugins do you have installed?

**Comment by allroundernaman** [comment]
I have many metamod plugins. I disabled all of them, except regamedll and amxmodx and tried enabling them one by one to find the culprit.

I found the culprit: reauthcheck and rerechecker. They both were causing problems. Any compactibility issue??
I have disabled both of them, but I need them too.

**Comment by WPMGPRoSToTeMa** [comment]
Looks like you're checking too many files with rechecker.

**Comment by allroundernaman** [comment]
What should I do?

**Comment by seypaa** [comment]
Delete useless line ?

**Comment by NamVr** [comment]
I have just disabled the faulty rechecker and other meta plugins.
Worked fine.
