### ISSUE TITLE
biohazard bug

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [s1lentq/ReGameDLL_CS#548]
It seems that it does not work with biohazard, we kill each other like in normal cstrike and zombie dont infect, they kill :s   help

**Comment by TDMidkwhatisxd** [comment]
I only used this for the bots :(

**Comment by fl0werD** [comment]
Write to bioharard's author.

**Comment by TDMidkwhatisxd** [comment]
This is useless anyway nvm
