### ISSUE TITLE
[Bug] Train reset on new round

### ISSUE THREAD

**Issue by spark512** [s1lentq/ReGameDLL_CS#55]
From ReHLDS issue # 238 - https://github.com/dreamstalker/rehlds/issues/238

I read somewhere that trains are bugged on cs 1.6 because they dont follow the new round event. If a train gets activated and the round ends before it reaches the destination, when a new round starts, the train is not properly reset, it's position is set back to start, but it is still active and going towards the destination. Can anything be done to fix this and make trains properly reset on new round?

I've noticed this problem on zombie escape maps, i've attached a map where this happens. To reproduce this problem, go to the end of the map and press the last button that starts the train. When the train start to move kill yourself and go to spectator so the round ends. When the new round begins, the train's position is set to start, but the train keeps going to the end. The same thing happens with the metal bridge in the middle.

[zm_mechanix_escape_v2.zip](https://github.com/s1lentq/ReGameDLL_CS/files/433290/zm_mechanix_escape_v2.zip)

**Comment by s1lentq** [comment]
This bug has been in the official version gamedll from Valve?

**Comment by spark512** [comment]
yes

**Comment by fuzun** [comment]
I noticed it as well. (In HL when new level gets loaded while you ride)

**Comment by spark512** [comment]
Yes, i just tested it, works perfectly. The train gets reset properly on new round. Thank you very much.

Another thing i noticed is the buttons dont reset as well. Could you make buttons reset on new round as well? Should i open another issue for that?

**Comment by WPMGPRoSToTeMa** [comment]
> Should i open another issue for that?

Yes, and I think would be great to create the general issue about properly entity reset.

**Comment by spark512** [comment]
I found a problem, some of the automated trains which are supposed to be running were also reset. I'm talking about the elevators and the crushing pistons going up and down. They are supposed to be running automatically, but they were reset and deactivated on new round.

Can you distinguish between entities that should be automatically activated and ones that need to be triggered by a button? Can those entities be filtered out somehow?

**Comment by WPMGPRoSToTeMa** [comment]
@spark512 can u give a map for example?

**Comment by spark512** [comment]
Look at the first post, i attached zm_mechanix_escape_v2.

It has both types of trains, automatic ones(elevators and piston crushers) and activated ones(middle brigde, platform going up, escape train).

**Comment by WPMGPRoSToTeMa** [comment]
@spark512 we need restart the trigger_once for this.

**Comment by spark512** [comment]
hmm, i see, but sadly that map is pretty old and i dont think the mapper is around to edit that.

What about a selective approach? Being able to select which trains get reset and which dont. A native perhaps?

**Comment by WPMGPRoSToTeMa** [comment]
I'm thinking about trigger resetting (they are not reset).

**Comment by spark512** [comment]
I noticed another bug with trains. The train's movements seems to be wrong. I noticed this on the maps zm_boatescape and zm_osprey_escape. The boats in the water move sideways, they are not facing the proper direction. The plane in zm_osprey_escape is going backwards, also facing the wrong direction.

They are going the correct way in term of path, but they are facing the wrong direction.

I tested this on ReGameDLL_CS build 175 and 171, same problem in both.

zm_boatescape - http://maps.cs-bg.info/maps/cs/273/
zm_osprey_escape - http://maps.cs-bg.info/maps/cs/1745/

**Comment by spark512** [comment]
I need a solution for this, i cant apply this update because it breaks a few maps that use `func_trains` with `trigger_once`.

**Comment by s1lentq** [comment]
@spark512 sorry for a delay, i will to fix a bit later

**Comment by WPMGPRoSToTeMa** [comment]
@s1lentq good job :+1:

**Comment by spark512** [comment]
@s1lentq i just installed the new update and put it on a test server, i still have the same problem. All `func_trains` are reset on new round and the ones that should be automatic are not moving. The buttons were also not reset. Their timer is still running and they still activate in the new round...

**Comment by WPMGPRoSToTeMa** [comment]
@s1lentq we also need `multi_manager` resetting.

**Comment by WPMGPRoSToTeMa** [comment]
@s1lentq also needs `multi_manager` resetting.

**Comment by spark512** [comment]
We tested the newest update, trains and buttons are reset properly. Ignore my previous comment, i had the wrong version installed by mistake...

**Comment by spark512** [comment]
here is a map with a multi_manager for you to test.

zm_omega - http://gamebanana.com/maps/174384

**Comment by spark512** [comment]
Thank you

**Comment by spark512** [comment]
We also need a `trigger_auto` reset. There are some maps with trains that are activated by a `trigger_auto`.

**Comment by s1lentq** [comment]
@spark512 give me the names of the maps.

**Comment by spark512** [comment]
@s1lentq zm_zod_egyptian - https://www.sendspace.com/file/8jz8bn

There are automatic blocks that come out of the wall and back. They get stopped after new round.

I tried the new update now, it didnt fix them...

**Comment by spark512** [comment]
Sry to bug you, egyptian is one of our most played maps, just a reminder, please have a look at the problem when you have free time. Thanks

**Comment by s1lentq** [comment]
@spark512 I'll take a look

**Comment by spark512** [comment]
The automatic blocks on egyptian are working again, thank you.
