### ISSUE TITLE
c4 is not shown in the tab score

### ISSUE THREAD

**Issue by stefanofabi** [s1lentq/ReGameDLL_CS#551]
Hello, having on

mp_forcechasecam "2"

c4 is not seen when you are dead and you are ct.

 It hurts a lot for competitive servers that need only the first person to be seen.

Could you add an option to restrict yourself to first person and if you can see c4 in the tab score?

**Comment by wopox1337** [comment]
Why u should see T bomb?

**Comment by stefanofabi** [comment]
because that's the game, if you're ct and you're dead you can see who's carrying the bomb

**Comment by twisterniq** [comment]
CTs shouldn't see who has the bomb

**Comment by Haco** [comment]
Please add the cvar like "mp_scoreboard_showbomb" to hide/show the c4 in the scoreboard.
In the original CS, the c4 is visible in the scoreboard for dead CT players.

**Comment by fred0r** [comment]
> because that's the game, if you're ct and you're dead you can see who's carrying the bomb
What would it change, since as a dead CT you arent able to talk to your Teammates anyway?

**Comment by stefanofabi** [comment]
> > because that's the game, if you're ct and you're dead you can see who's carrying the bomb
> 
> What would it change, since as a dead CT you arent able to talk to your Teammates anyway?

You can talk to your team by putting sv_alltalk 3 .

The idea of seeing the bomb is designed so as not to lose the fun when playing competitive games. In a 32-slot public server I doubt that this functionality is used.
