### ISSUE TITLE
[Small Report] mp_falldamage

### ISSUE THREAD

**Issue by germansassone** [s1lentq/ReGameDLL_CS#552]
I think in newer versions mp_falldamage is disabled (0) by default

**Comment by theshadowz** [comment]
So? Sure, this is enabled and always was enabled, because it's a default behavior of the game

**Comment by germansassone** [comment]
Report updated @theshadowz

**Comment by twisterniq** [comment]
How did you check that it's disabled by default? If you download the latest ReGameDLL version and open game.cfg you will see that "mp_falldamage" is "1".

**Comment by germansassone** [comment]
@twisterniq That is correct. With the game.cfg is "1". Without the game.cfg is "0". I noticed that. Might be useful to modify It. I don't know

**Comment by WPMGPRoSToTeMa** [comment]
Even when `game.cfg` is missing this cvar should be equal to `1`:https://github.com/s1lentq/ReGameDLL_CS/blob/6c80744146fb583d066be0a2977225da29e575fe/regamedll/dlls/game.cpp#L150

**Comment by germansassone** [comment]
I'm so so sorry. I've fucked up. It's my mistake, I didn't check the values of my server.cfg. Sorry for wasting your time

**Comment by Dr-Strange91** [comment]
Close the issue then?

**Comment by WPMGPRoSToTeMa** [comment]
@germansassone no problem, please close the issue.
