### ISSUE TITLE
heey

### ISSUE THREAD

**Issue by sanjeevsihag** [s1lentq/ReGameDLL_CS#554]
i want to make a cs server and make it online always like host made them. any help

**Comment by seypaa** [comment]
Wrong section go back

**Comment by sanjeevsihag** [comment]
> Wrong section go back

tell me right section than

**Comment by seypaa** [comment]
Search google ? Can you do it for me ?

**Comment by sanjeevsihag** [comment]
i can't find . can you provide me sources for it.

**Comment by sanjeevsihag** [comment]
> Search google ? Can you do it for me ?

did you find it>

**Comment by seypaa** [comment]
https://developer.valvesoftware.com/wiki/SteamCMD

**Comment by seypaa** [comment]
And search  like ; hlds server installing port rules, firewall , etc

**Comment by seypaa** [comment]
By the way close issiue

**Comment by sanjeevsihag** [comment]
okay
