### ISSUE TITLE
[Feature request] mp_free_armor

### ISSUE THREAD

**Issue by metita** [s1lentq/ReGameDLL_CS#560]
CS:GO logic, basically.

**mp_free_armor 0** - No armor on spawn, but will keep armor the player already have.
**mp_free_armor 1** - Player spawn with Kevlar.
**mp_free_armor 2** - Player spawn with Kevlar and Helmet.

FROM: https://github.com/perilouswithadollarsign/cstrike15_src/blob/master/game/shared/cstrike15/cs_gamerules.cpp#L16958

**Comment by Jairitocs** [comment]
Good Idea!

**Comment by seypaa** [comment]
I understand you, but too many features have been added to "regamedll". Some are unnecessary

**Comment by RauliTop** [comment]
> I understand you, but too many features have been added to "regamedll". Some are unnecessary

It's easy to do it and doesn't required too much time.

**Comment by stefanofabi** [comment]
Very good idea.
