### ISSUE TITLE
[Bug] Train movement

### ISSUE THREAD

**Issue by spark512** [s1lentq/ReGameDLL_CS#58]
I found another bug with trains. The train's movements seems to be wrong. I noticed this on the maps zm_boatescape and zm_osprey_escape. The boats in the water move sideways, they are not facing the proper direction. The plane in zm_osprey_escape is going backwards, also facing the wrong direction.

They are going the correct way in term of path, but they are facing the wrong direction.

I tested this on ReGameDLL_CS build 175 and 171, same problem in both. This doesn't happen on the original game dll from valve.

zm_boatescape - http://maps.cs-bg.info/maps/cs/273/
zm_osprey_escape - http://maps.cs-bg.info/maps/cs/1745/

EDIT:

Same problem on deathrun_train_v4, you can see it when the moving block goes downwards. Watch what the moving block does all around the map, and you'll understand what i mean.

deathrun_train_v4 - http://maps.cs-bg.info/maps/cs/3409/

**Comment by omertelli** [comment]
Yes, cars be like drifting

**Comment by s1lentq** [comment]
@spark512 Thanks for report.

**Comment by spark512** [comment]
@s1lentq thank you.

Please check issue #55 again, there's still a problem with that.
