### ISSUE TITLE
5.18.0.479 release doesn't compiled with last related commit 

### ISSUE THREAD

**Issue by zipper-krew** [s1lentq/ReGameDLL_CS#580]
When we installing 5.18.0.479 release we've got 478 build inside.

**Comment by afwn90cj93201nixr2e1re** [comment]
.

**Comment by zipper-krew** [comment]
https://github.com/s1lentq/ReGameDLL_CS/releases/download/5.18.0.479/regamedll-dist-5.18.0.479-dev.zip

**Comment by afwn90cj93201nixr2e1re** [comment]
.

**Comment by zipper-krew** [comment]
Not actual, since 5.18.0.480 released

**Comment by afwn90cj93201nixr2e1re** [comment]
.
