### ISSUE TITLE
Can and will this work together with metamod and AMXX 1.8.2?

### ISSUE THREAD

**Issue by AWandererInInternet** [s1lentq/ReGameDLL_CS#585]
I am referring to s1lentq's mp.dll If yes, how? It crashes when I start a game with the bots without showing a prompt nor error
I edit the liblist.gam as follows:
```
gamedll "dlls\mp.dll"
gamedll "addons\metamod\dlls\metamod.dll"
```
but if I disable metamod
```
gamedll "dlls\mp.dll" 
//gamedll "addons\metamod\dlls\metamod.dll" 
```
The bots and the game works flawlessly without metamod and enabling only s1lentq's mp.dll alone.
What did I do wrong?

When I use the original CSCZ (Condition Zero) mp.dll and enable it together with metamod, it works flawlessly with metamod .

Metamod Version metamod-p-1.21p38

**Comment by voed** [comment]
AMXX 1.8.2 is outdated, use 1.9 instead.

**Comment by AWandererInInternet** [comment]
How about metamod-p-1.21p38, is that the latest version?

**Comment by afwn90cj93201nixr2e1re** [comment]
.
