### ISSUE TITLE
Adding Cvar to Open/Close Duck Bugs

### ISSUE THREAD

**Issue by Snakeren** [s1lentq/ReGameDLL_CS#592]
Duck Bug is basically a body boosting type for two players. There are two players, one of them is in the head of other one. Above player ducks and hold downs ctrl. Lower player jumps by holding down ctrl. Thus above player gets in bug and rises more than normal. A video that shows this bug:

https://www.youtube.com/watch?v=Jvgfys46RMc

This bug was avaliable in older hlds versions. After i updated my server, the bug has been disabled. (im not sure what exactly removes this bug) What i need is to add a cvar which opens/closes it.

**Comment by etojuice** [comment]
> This bug was avaliable in older hlds versions. After i updated my server, the bug has been disabled. (im not sure what exactly removes this bug) What i need is to add a cvar which opens/closes it.

https://github.com/s1lentq/ReGameDLL_CS/blob/master/dist/game_init.cfg

**Comment by Snakeren** [comment]
> https://github.com/s1lentq/ReGameDLL_CS/blob/master/dist/game_init.cfg

I have already tried it, nothing changes. I guess that cvar is for roof bugs.
