### ISSUE TITLE
Server crashes when second player connects

### ISSUE THREAD

**Issue by johnally** [s1lentq/ReGameDLL_CS#6]
I downloaded the latest snapshot of ReGameDLL_CS from "http://nexus.rehlds.org/nexus/content/repositories/regamedll-snapshots/regamedll/regamedll/0.2-SNAPSHOT/". With both "bugfixed" and "pure", my server crashes as soon as a second player enters the servers. (Sometimes there's a small timelapse after the player entered and the server crashing)

I've cloned the repository and compiled the mp.dll myself. Still no luck!

I've disabled all custom plugins I've made and stripped my server to a point where debugging should be easier. Even with such changes, It was really hard to find the exact cause. At first, I thought it could have been the "cstrike_amxx" module but turns out even with the fix on dedicated-server.ru, it made no difference.

Here's some details about my server configuration:
- ReHLDS  (latest to date - http://nexus.rehlds.org/nexus/content/repositories/rehlds-snapshots/rehlds/rehlds/0.2-SNAPSHOT/rehlds-0.2-20151227.174610-104.zip)

![screenshot_80](https://cloud.githubusercontent.com/assets/16476232/12044657/dba6a764-aeae-11e5-829b-d84157313227.png)

![screenshot_81](https://cloud.githubusercontent.com/assets/16476232/12044669/fa20c468-aeae-11e5-8151-7dba01b2a46d.png)

![screenshot_82](https://cloud.githubusercontent.com/assets/16476232/12044678/1bbaabca-aeaf-11e5-9bb5-9962ca386eb0.png)

![screenshot_83](https://cloud.githubusercontent.com/assets/16476232/12044729/33710b3c-aeb0-11e5-95e5-ff30f23dd342.png)

![screenshot_84](https://cloud.githubusercontent.com/assets/16476232/12044740/59a5d80a-aeb0-11e5-9d13-133b8b872852.png)

Your help is greatly appreciated :)

**Comment by johnally** [comment]
For more information, I'm using the latest HLDS using "app_update 90 validate" (Ran multiple times because they said their could be a bug)

![screenshot_85](https://cloud.githubusercontent.com/assets/16476232/12049543/bca74168-af01-11e5-9fd2-f57a89706d5c.png)

**Comment by s1lentq** [comment]
1. check on a clean server without metamod.
have a any crashes?
2. why use mmtimer if you running with rehlds?

**Comment by johnally** [comment]
1. I will do that as soon as I'm over with dishes. (But I can already fore-tell that that amxmodx is the cause)
2. Good question. I will remove it. When I run it with rehlds, I get 2000fps. Without it I get 1000fps. But 1000fps is enough. I don't know why I keep leaving it there. 

Thank you,

**Comment by johnally** [comment]
Amxmodx is NOT at fault. My bad. I disabled it alone to test and it still crashes. Right now people are playing in my server (8+ at the moment) with the following metamod/plugins.ini:
win32	addons\reunion\reunion_mm.dll
;win32      addons\amxmodx\dlls\amxmodx_mm.dll
;win32	addons\revoice\revoice_mm.dll
;win32	addons\whblocker\whblocker.dll
;win32	addons\srdetector\srdetector.dll

When I disabled revoice, whblocker and srdetector, the server stopped crashing. 

The final culprit is "whblocker". However, it is the same as http://www.dedicated-server.ru/vbb/showthread.php?t=25639 with default configuration file. Hmm..

**Comment by s1lentq** [comment]
try in whblocker setting "team" set to 1
this should your help.

**Comment by johnally** [comment]
Like you said, it worked indeed.
However, I looked at what the "team" setting does and I'm baffled it solved the proble.

Can you explain why it worked? (I don't want to be the guy to remain ignorant in such situations lol)

**Comment by s1lentq** [comment]
setting "team" is 1 requires the presence of pointer g_pGameRules for to determine the enemy or teammate using g_pGameRules->PlayerRelationship(object1, object2), but since g_pGameRules not finds and turning to a zero address we get crash.

**Comment by johnally** [comment]
Thank you a lot for your explanation. It makes more sense now. I did see that with ReGameDll that g_pGameRules was missing. However, I did not know WHBlocker was using it. 

Hope to see a future version of WHBlocker with the error handling. 

Thanks again. (You are free to close that issue as it was resolved from a ReGameDll point of view)

**Comment by coolmans** [comment]
team = 1 server crash


Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 18:40:48 Dec 27 2015 (624)
ReHLDS API version 2.5

 [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.57   ini  Start Never
 [ 2] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.620  ini  Chlvl ANY  
 [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-d  ini  Start ANY  
 [ 4] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-d  pl3  ANY   ANY  
 [ 5] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-d  pl3  ANY   ANY  
 [ 6] Engine           RUN   -    engine_amxx_i386  v1.8.3-d  pl3  ANY   ANY  
 [ 7] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-d  pl3  ANY   ANY  
 [ 8] GeoIP            RUN   -    geoip_amxx_i386.  v1.8.3-d  pl3  ANY   ANY  
 [ 9] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-d  pl3  ANY   ANY  
 [10] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-d  pl3  ANY   ANY  
 [11] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-d  pl3  ANY   ANY

**Comment by johnally** [comment]
Indeed. It was rather unexpected that WHBlocker would make the whole server crash. Don't have access to the source code to patch it though. Will have to wait for s1lentq to take care of it.
