### ISSUE TITLE
Bug with spectator

### ISSUE THREAD

**Issue by spark512** [s1lentq/ReGameDLL_CS#61]
Hey,

I'm sure you've heard of this bug before. If a player joins the game, picks a team, but doesn't select a skin(leet, urban, gign, etc...) he gets spawned, but he teleports around the map where there are cameras. We tested this with a friend, he said it works through the old style menus.

Here is a map with cameras to test the issue:
zm_toronto_v4 - https://www.sendspace.com/file/6sa8kj

To reproduce the issue, switch to old style menus, join, pick a team without picking a skin and when you get spawned you keep teleporting around the map where there are cameras

**Comment by Vaqtincha** [comment]
я лично не обнаружил

**Comment by s1lentq** [comment]
`when you get spawned`
Please explain this, as the player get spawned? from gameplay? or 3rd-party meddling?

**Comment by spark512** [comment]
Yes, i believe when he's spawned from new round. I'm not sure what exactly is going on and how to explain it, i can show you in a test server if you'd like..

**Comment by s1lentq** [comment]
@spark512 If it is possible for you can provide a video or demo?

**Comment by spark512** [comment]
After a bit of testing i found out more about this bug. So the bug happens when you're between jointeam and joinclass. You have a team selected, but you dont have a class yet. The problem is produced when you are spawned by 3rd party plugins (since there is nothing to spawn you under normal circumstances), basically anything that spawns you in this state. The previous cause was the Zombie Plague mod, but i managed to use AMX_Super to reproduce the same problem.

To reproduce with AMX_Super, select a team and respawn yourself with amx_revive or amx_transfer.

Here is a demo of what happens:
https://www.sendspace.com/file/rj6cr1

You get teleported to the places where there are cameras because you were spawned without properly selecting a class. I think i add need to add a check in these plugins to prevent spawning when there is no class selected. But i also think those cameras should only affect unassigned players, and not players who selected a team...

**Comment by spark512** [comment]
Tested and it's working, players are not able to spawn. Good job 👍
