### ISSUE TITLE
Краш-лог! Версия 5.20.0.498 не совместим с модулем CSDM by v2.1.3c-KWo

### ISSUE THREAD

**Issue by ykpon2** [s1lentq/ReGameDLL_CS#613]
[src.zip](https://github.com/s1lentq/ReGameDLL_CS/files/6301590/src.zip)
Здравствуйте! 
Сегодня обновлял REGameDLL_CS на новую версию 5.20.0.498 и столкнулся с проблемой. Сервер постоянно крашит 
На версии **5.20.0.496 - проблем нет** , появилась проблема на новой 5.20.0.498 версии

Сервер крашит сразу же после запуска, как прогружается meta модули , аммх плагины и сервер через 1 секунду уходит в краш с ошибкой 
`./hlds_run: line 255: 15691 Segmentation fault      (core dumped) $HL_CMD
./hlds_run: line 201: gdb: command not found
email debug.log to linux@valvesoftware.com
Tue Apr 13 01:59:04 EDT 2021: Server restart in 10 seconds`

Нашел причину падения. Когда отключаю модуль CSDM
`CSDM2            RUN   -    csdm_amxx_i386.so           v2.1.3c-KWo      pl6  ANY   ANY`
То падения прекращаются и 5.20.0.498 версия - работает
 
 Возможно ли пофиксить, чтобы новая версия 5.20.0.498 также была совместима с модулем CSDM ?

[модуль_CSDM.zip](https://github.com/s1lentq/ReGameDLL_CS/files/6301591/src.zip)

**Comment by stambeto2006** [comment]
ReCSDM 3.6 It works without any crashes, use it!

**Comment by ykpon2** [comment]
> ReCSDM 3.6 It works without any crashes, use it!

ReCSDM работает только с версии Amx Mod X 1.9.0 :((
У меня версия 1.8.2

**Comment by stambeto2006** [comment]
I don't know why you still use old versions of platforms and other things, as there are newer things and optimized and maintained!

**Comment by ykpon2** [comment]
Проблема решена! 
Перешел на ReCSDM 3.6 по совету stambeto2006
Спасибо за подсказку :)
