### ISSUE TITLE
[Баг] Авп висит в воздухе, поднялся вверх, т.к стоя не получается нормально сделать скриншот

### ISSUE THREAD

**Issue by DrHesperus** [s1lentq/ReGameDLL_CS#617]
![ScreenShot_20210421210151](https://user-images.githubusercontent.com/37004902/116418675-cd996200-a855-11eb-8713-8c2adf00b386.png)

**Comment by wopox1337** [comment]
What's wrong?

**Comment by DrHesperus** [comment]
> What's wrong?

I didn’t buy it, it spawns in the second round ...

**Comment by theshadowz** [comment]
Shitty amxx plugins. There isn't any problem in RegameDLL that could refer to your problem
