### ISSUE TITLE
[Bug] Yapb Bot and POD bot clone do nothing (idle) after spawn.

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#62]
I use Yapb bot (Yet Another POD Bot) to play in ReHLDS and i noticed the bots just idle after spawn.

Details:
Operating System:
`Windows 10 Pro x64 latest update.`

Game:
`Counter-Struck 1.6`

Client:
`Counter-Struck 1.6 (Steam)`

status

```
hostname:  The.Good.Old.Days
version :  48/1.1.2.7 881 secure  (10)
tcp/ip  :  x.x.x.x:270xx
map     :  de_dust2 at: 0 x, 0 y, 0 z
players :  19 active (32 max)

#      name userid uniqueid frag time ping loss adr
#1 "The Administrator" 21 BOT   0 01:27    0    0
#2 "Gentlemanne of Leisure" 2 BOT   0 01:27    0    0
#3 "Crazed Gunman" 3 BOT   0 01:27    0    0
#4    "Dog" 4 BOT   0 01:27    0    0
#5 "Mann Co." 5 BOT   0 01:27    0    0
#6 "Companion Cube" 6 BOT   0 01:27    0    0
#7 "BoomerBile" 7 BOT   0 01:27    0    0
#8 "SMELLY UNFORTUNATE" 8 BOT   0 01:27    0    0
#9   "Pow!" 9 BOT   0 01:27    0    0
#10 "Ze Ubermensch" 10 BOT   0 01:27    0    0
#11 "The Freeman" 11 BOT   0 01:27    0    0
#12    "C++" 12 BOT   0 01:27    0    0
#13 "Force of Nature" 13 BOT   0 01:27    0    0
#14 "Freakin' Unbelievable" 14 BOT   0 01:27    0    0
#15 "Mentlegen" 15 BOT   0 01:27    0    0
#16 "CrySomeMore" 16 BOT   0 01:27    0    0
#17 "One-Man Cheeseburger Apocalypse" 17 BOT   0 01:27    0    0
#18  "AmNot" 18 BOT   0 01:27    0    0
#19 "The Combine" 19 BOT   0 01:27    0    0
19 users
```

version

```
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 20:01:06 Sep  9 2016 (881)
ReHLDS API version 2.13
```

game_version
`"game_version" is "0.2.150"`

sv_version
`"sv_version" is "1.1.2.7,48,881"`

meta list

```
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] Yet Another POD  RUN   -    yapb.dll          v2.73     ini   Chlvl ANY
1 plugins, 1 running
```

• This issue happen when using current regamedll.
• No problem with valve mp.dll.
• Build-in csbot in regamedll also working fine.

HOW TO REPRODUCE:
Set this cvar:

```
// Automatically joins the team
// 0 - disabled
// 1 - enable (Use in conjunction with the cvar humans_join_team any/CT/T)
//
// Default value: "0"
mp_auto_join_team 1
```

**Comment by vase070** [comment]
strange ... i use ybot to and don't have this kind of issue using the latest rehlds and regamedll can you paste your yapb.cfg ?

**Comment by lespaul64** [comment]
@vase070 heres mine.

`// ------------------------------------------------------------------------
// This file is part of Yet Another Ping Of Death Bot Configuration Files.
// Copyright (c) 2003-2017, by YaPB Development Team.
//
// Please check out the documentation, before altering config files.
// ------------------------------------------------------------------------

//
// Display's additional debug information about bot, when you spectating him.
//
// Default: 0
//
yb_debug "0"

//
// Forces all bots to move to specified here goal.
//
// Default: -1
//
yb_debug_goal "-1"

//
// Chance that bot will autofollow human-commander in start of each round.
//
// Default: 20
//
yb_user_follow_percent "20"

//
// Maximum number of bots, that can follow human-commander each round.
//
// Default: 1
//
yb_user_max_followers "0"

//
// Forces all bot's to play only with knives.
//
// Default: 0
//
yb_jasonmode "0"

//
// Select's bot's radio-chatter-communication types.
//
// Allowed values:
//   0 - Radio & Chatter Disabled.
//   1 - Only Radio Enabled.
//   2 - Chatter & Radio Enabled.
//
// Default: 2
yb_communication_type "0"

//
// Enables bot's economics rounds. See general.cfg for more info.
//
// Default: 1
//
yb_economics_rounds "0"

//
// Enables or disables bot's ability to move silently, if they hears enemy.
//
// Default: 1
//
yb_walking_allowed "0"

//
// Forces bot to punish teammate, that shooting him. This also forces bots to vote for kick against his tk'ing teammate.
//
// Default "1"
//
yb_tkpunish "0"

//
// Bot's do nothings, and stays at spawn.
//
// Default: 0
//
yb_freeze_bots "0"

//
// Allows or disallows bot's to do spraypaints.
//
// Default: 1
//
yb_spraypaints "0"

//
// Allows or disallows bots ability to buy weapons.
//
// Default: 1
//
yb_botbuy "0"


//
// Path to chatter, by default points to chatter from Official CSBot
//
// Default: sound/radio/bot
//
yb_chatter_path "sound/radio/bot"

//
// Weapons that bot unable to buy in any situations. Priority of this cvar higher, than the data specified in general.cfg
//
// Default: 
//
yb_restricted_weapons ""

//
// Allows or disallows bot's shooting through walls at enemies.
//
// Default: 2
//
yb_shoots_thru_walls "2"

//
// When enabled, bot's will ignore any enemies on the way, but will do their goals.
//
// Default: 0
//
yb_ignore_enemies "0"


//
// Only used with CSDM mod, and selects whether CSDM is active. This cvar automatically configured by bot.
// No need to edit manually in most cases.
//
// Available values:
//  0 - Disabled CSDM.
//  1 - CSDM Active.
//  2 - CSDM Active with FFA mode.
//
yb_csdm_mode "0"

//
// Kick bots to automatically make room for human players.
//
// Default: 1
//
yb_autovacate "1"

//
// Adds this number of bots per human users.
//
// Default: 0
//
yb_quota_match "0"


// Bot's will join the game, only one alive human already joined team.
//
// Default: 0
//
yb_join_after_player "0"

//
// Forces bot's to join specific team.
//
// Available values:
//   any - Bot's will join both teams.
//   ct - Bot's will join only CT team.
//   te - Bot's will join only T team.
//
// Default: any
//
yb_join_team "any"

//
// Specifies bot "clan" tag, that displayed before his name.
//
// Default: ""
//
yb_name_prefix ""

//
// Controls what latency will be shown in scoreboard for bots.
// 
// Available values:
//  0 - Nothing is displayed.
//  1 - "BOT" latency is displayed.
//  2 - Simulating human latency.
//
yb_latency_display "0"

//
// Allows or disallows bots text-chat.
//
// Default: 1
//
yb_chat "0"

//
// Controls the password to access bot command and menus, when connected to server running yapb.
//
// Default: thebot
//
// Notes: Change this, if you going to run bots on dedicated server.
//
yb_password "nosecretok"

//
// Setinfo password key, that holds yb_password on client, to access bot commands and menus, when connected to server
// running yapb.
//
// Default: _ybpw
//
// Usage:
//   setinfo _ybpw thebot  - You will be able to access bot's menu in commands remotely.
//
yb_password_key "_lalala"

//
// Small welcome message on first round, showing version and build of the bot.
//
// Default: 1
//
yb_listenserver_welcome "0"

//
// Specifies host, that contains dozen of waypoint files. Host must contain subdirectory /wpdb/ which contains all the waypoints.
//
// Default; yapb.jeefo.net
//
yb_waypoint_autodl_host "yapb.jeefo.net"

//
// Allows or disallows bot to download waypoints from autodl_host.
//
// Default: 1
//
// Notes: This may freeze game loading process for a few seconds, as download done in main thread.
//
yb_waypoint_autodl_enable "0"

//
// Language that used to display menus and messages from bot dll.
//
// Default: en
//
yb_language "en"

//
// Bot difficulty. As it-is.
//
// Default: 4
//
yb_difficulty "4"

//
// Amount of bots to add. Adding many bots will use more cpu. Start with a few bots, then add more if needed.
//
// Default: 9
//
yb_quota "19"

//
// Binds "=" key to open bot's main menu
//
bind "=" "yb menu"
`

Make sure to set this in your game.cfg:
`// Automatically joins the team
// 0 - disabled
// 1 - enable (Use in conjunction with the cvar humans_join_team any/CT/T)
//
// Default value: "0"
humans_join_team any
mp_auto_join_team 1`

**Comment by Vaqtincha** [comment]
У меня тоже при mp_auto_join_ team 1 они стоят без действие (но покупают оружие). 
А при mp_auto_join_ team 0 они вообще сидят в спектаторах.

**Comment by ViBE-HU** [comment]
similar happens with me IF a waypoint file is undone.

**Comment by lespaul64** [comment]
Tested again and there is no problem anymore. I'm not sure regamedll or yapb fix this issue.
