### ISSUE TITLE
Crash when using ENG_CHECK_PARM

### ISSUE THREAD

**Issue by OrangePee1** [s1lentq/ReGameDLL_CS#625]
bool UTIL_AreHostagesImprov()
{
	if (AreRunningCZero())
	{
		return true;
	}

#ifdef REGAMEDLL_ADD
	// add check null
	if (g_engfuncs.pfnEngCheckParm == nullptr)
		return false;

	// someday in CS 1.6
	int improv = ENG_CHECK_PARM("-host-improv", nullptr);
	if (improv)
	{
		return true;
	}
#endif

	return false;
}

**Comment by s1lentq** [comment]
don't use metamod version 1.20 or earlier
