### ISSUE TITLE
[-bots] - should it still work?

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#629]
i've started latest rehlds/regamedll(505) with  `+maxplayers 26 -beta -bots -host-improv`

game.cfg:
```
bot_quota_mode "fill"
bot_quota "4"
bot_auto_vacate "1"
```
copied  the content of botprofiles.zip and hostimprov.zip into server/cstrike, but there are no bots joining.
what am i missing?

**Comment by Vaqtincha** [comment]
bot_join_after_player 0

**Comment by fred0r** [comment]
thx
