### ISSUE TITLE
Precompiled headers are evil

### ISSUE THREAD

**Issue by a1batross** [s1lentq/ReGameDLL_CS#63]
I tried to compile latest regamedll for Android, using GCC 4.8 from NDK r10e to add GCC and Android support in this project, instead of maintaining [fork](http://github.com/FWGS/regamelite).
1) Tons of errors because invalid header placement. I fixed it for one file, in other file it errored again. 
Example: game_shared/bot/improv.h uses an enum, which are not defined before in dlls.h.
2) I can't find where is defined symbol without simple script. 
3) ~~It's about time.  Preprocessor need to include a big count of headers. Only 5% is useful for one cpp file. Compiler still need to parse a C++ code, which is very complicated task.~~ I just wrong used precompiled headers in GCC. Still, no time improvements.
4) Precompiled headers are evil for those programmers, who want to modify this project for his own needs.

**Comment by a1batross** [comment]
I'm not here for comments like "Use ICC/MSVC".  They just can't compile code for Android.

**Comment by WPMGPRoSToTeMa** [comment]
2) F12 in visual studio?

**Comment by a1batross** [comment]
@WPMGPRoSToTeMa I don't use Visual Studio. It's not ported to Linux.

**Comment by theAsmodai** [comment]
1) You doing something wrong. Headers order is the same for any С++ compiler.
2) It's problem of your IDE.
3) Precompiled headers are much more faster than any parsing (especially for STL headers). I think you don't understand how this technology works. You need to add precompilers headers support to NDK.
4) ... Consequence of 3

**Comment by mittorn** [comment]
IDE? What? We are talking about compiler/build system, not IDE

**Comment by WPMGPRoSToTeMa** [comment]
@mittorn how can he find symbol definition in compiler?
> 2) I can't find where is defined symbol without simple script. 

@a1batross on Linux you can try use CLion.

**Comment by a1batross** [comment]
Forget about it. It can be solved with one line in shell or with find tool
in every IDE. Anyway, I think that precompiled is useful for system
headers, which are read-only almost everywhere. But I also think that
project which uses pch must be "buildable" even with disabled pch.
03.10.2016 17:17 пользователь "Artem Golubikhin" <notifications@github.com>
написал:
