### ISSUE TITLE
sv_alltalk enhancement

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#643]
Need to add new type `sv_alltalk 5`
https://github.com/s1lentq/ReGameDLL_CS/wiki/sv_alltalk

### sv_alltalk "5"

 |Team|Alive CT :speaking_head:|Alive T :speaking_head:|Dead CT :speaking_head:|Dead T :speaking_head:|Spectator :speaking_head:|
 | --------: | :------: | :------: | :-----: | :-----: | :-------: |
 | Alive CT :ear:| :white_check_mark: | :x: | :x: | :x: | :x: |
 | Alive T :ear:| :x: | :white_check_mark: | :x: | :x: | :x: |
 | Dead CT :ear:| :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |                                               
 | Dead T :ear:| :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
 | Spectator :ear:| :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |

**Comment by Vaqtincha** [comment]
Confused feature with 1k vars 😃

**Comment by fred0r** [comment]
https://github.com/s1lentq/ReGameDLL_CS/issues/645

**Comment by wopox1337** [comment]
@fred0r  In my opinion, it is better to transfer all the settings from CS:GO. Otherwise,  `sv_alltalk` will expand into 999 values 🤔

```cpp
// Set game rules to allow all clients to talk to each other.
// Muted players still can't talk to each other.
ConVar sv_alltalk( "sv_alltalk", "0", FCVAR_REPLICATED | FCVAR_NOTIFY | FCVAR_RELEASE, "Deprecated. Replaced with sv_talk_enemy_dead and sv_talk_enemy_living." );

// [jason] Can the dead speak to the living?
ConVar sv_deadtalk( "sv_deadtalk", "0",	FCVAR_REPLICATED | FCVAR_NOTIFY | FCVAR_RELEASE, "Dead players can speak (voice, text) to the living" );

// [jason] Override that removes all chat restrictions, including those for spectators
ConVar sv_full_alltalk( "sv_full_alltalk", "0", FCVAR_REPLICATED | FCVAR_RELEASE, "Any player (including Spectator team) can speak to any other player" );

ConVar sv_talk_enemy_dead( "sv_talk_enemy_dead", "0", FCVAR_REPLICATED | FCVAR_RELEASE, "Dead players can hear all dead enemy communication (voice, chat)" );
ConVar sv_talk_enemy_living( "sv_talk_enemy_living", "0", FCVAR_REPLICATED | FCVAR_RELEASE, "Living players can hear all living enemy communication (voice, chat)" );

#ifdef GAME_DLL
ConVar sv_auto_full_alltalk_during_warmup_half_end( "sv_auto_full_alltalk_during_warmup_half_end", "1", FCVAR_RELEASE, "When enabled will automatically turn on full all talk mode in warmup, at halftime and at the end of the match" );
#endif

ConVar sv_spec_hear( "sv_spec_hear", "1", FCVAR_REPLICATED | FCVAR_NOTIFY | FCVAR_RELEASE, "Determines who spectators can hear: 0: only spectators; 1: all players; 2: spectated team; 3: self only; 4: nobody" );
```

**Comment by afwn90cj93201nixr2e1re** [comment]
.

**Comment by fred0r** [comment]
Why do you call these possible Options  'weird/obscure'?
A Option like _sv_add_talkmode_ would be a nice addition.
