### ISSUE TITLE
[bug][gamedll] 'game_player_equip'

### ISSUE THREAD

**Issue by Vaqtincha** [s1lentq/ReGameDLL_CS#65]
Имеется проблема "летающие оружие"
https://github.com/ValveSoftware/steam-for-linux/issues/1270
https://github.com/ValveSoftware/steam-for-linux/issues/1273
как видно из кода https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/maprules.cpp#L579
носилно пытается выдавать игроку без проверок в итоге мы видим (если прошлом раунде не потеряли оружие) вокруг "летающие оружие"  их можно "поймать" (бросав текущий) иногда это может крашит сервер.
Знаю перед выдачей можно отбирать все (с помощью player_weaponstrip) но если на карте есть различные итемы (типа гранат) то выходить не очень хорошо.

Еще не помешал бы добавить один spawnflag для game_player_equip типа "strip before giving" (или update weapons on new round) отпадает необходимости player_weaponstrip и multi_manager (использую для задержки).

**Comment by Vaqtincha** [comment]
И еще если террористам выдавать бомбу то они не могут поставить его и даже не видно StatusIcon и body (рюкзак). А так же перед выдачей не хватает проверка команды игрока т.к если в equip'е есть item_thighpack то вокруг террористов появится дефузеры.

**Comment by wopox1337** [comment]
Closed? Или баг еще имеет место быть?
