### ISSUE TITLE
Improper "TextMsg" message work

### ISSUE THREAD

**Issue by rust2** [s1lentq/ReGameDLL_CS#654]
After transferring to ReGameDLL_CS from HLDS I noticed that "TextMsg" message works wrong (not as should) when someone uses radio commands (use "radio1/2/3" commands or throw grenades).
Originally it sends as 2nd argument message itself.
Here it sends userid (idk why it does, maybe someone can explain?) as 2nd arg and only as 3rd arg goes message.

**Comment by hajimura** [comment]
The first, UserMsg functions dont refer to regamedll, these functions are implemented on client side, so should look into client sources
And the second, i dont have any problem with TextMsg you described above

**Comment by rust2** [comment]
> The first, UserMsg functions dont refer to regamedll, these functions are implemented on client side, so should look into client sources
Are you sure? So why when I changing dlls TextMsg's behavior changes too?
> And the second, i dont have any problem with TextMsg you described above
You can't see it as common player. I made simple amxx script to hook TextMsg messages. When you receive one you will see info 'bout received message in console.
`#include <amxmodx>

new const ARG[][] =
{
	"",
	"ARG_BYTE (int)",
	"ARG_CHAR (int)",
	"ARG_SHORT (int)",
	"ARG_LONG (int)",
	"ARG_ANGLE (float)",
	"ARG_COORD (float)",
	"ARG_STRING (string)",
	"ARG_ENTITY (int)"
}

new const DEST[][] =
{
	"MSG_BROADCAST",
	"MSG_ONE",
	"MSG_ALL",
	"MSG_INIT",
	"MSG_PVS",
	"MSG_PAS",
	"MSG_PVS_R",
	"MSG_PAS_R",
	"MSG_ONE_UNRELIABLE",
	"MSG_SPEC"
}

public plugin_init()
{
	register_plugin("name", "version", "author")
	register_message(get_user_msgid("TextMsg"), "onMessageSent")
}

public onMessageSent(iMessage, iDest, id)
{
	console_print(id, "--")
	
	new _args = get_msg_args()
	console_print(id, "^tGot %i arguments", _args)
	
	new _type
	new _szLine[128]
	
	for(new _argn = 1; _argn <= _args; _argn++)
	{
		_type = get_msg_argtype(_argn)
		
		switch(_type)
		{
			case ARG_BYTE, ARG_CHAR, ARG_SHORT, ARG_LONG, ARG_ENTITY: 
			{
				num_to_str(get_msg_arg_int(_argn), _szLine, charsmax(_szLine))
			}
			case ARG_ANGLE, ARG_COORD: 
			{
				float_to_str(get_msg_arg_float(_argn), _szLine, charsmax(_szLine))
			}
			case ARG_STRING: 
			{
				get_msg_arg_string(_argn, _szLine, charsmax(_szLine))
			}
		}
		
		if(_argn == 1)
		{
			console_print(id, "^t%i :: Destination type: %s", _argn, DEST[iDest])
		}
		else
		{
			console_print(id, "^t%i :: %s :: %s", _argn, ARG[_type], _szLine)
		}
	}
	
	console_print(id, "--")
	
	return PLUGIN_CONTINUE
}`

**Comment by rust2** [comment]
Oh, my bad
Now I used latest steam's mp.dll and this happens there too. Idk when they changed this
