### ISSUE TITLE
After buy a weapon full bpammo for it.

### ISSUE THREAD

**Issue by mforce95** [s1lentq/ReGameDLL_CS#66]
```
// Refill amount of backpack ammo up to the max
// 0 - disabled (default behaviour)
// 1 - refill backpack ammo on player spawn
// 2 - refill backpack ammo on each weapon reload (NOTE: Useful for mods like DeathMatch, GunGame, ZombieMod etc.)
//
// Default value: "0"
mp_refill_bpammo_weapons 1
```

**Please add another option to refill bpammo on spawn & after buy a weapon.**

**Comment by omertelli** [comment]
it should be nice 
+1

**Comment by Vaqtincha** [comment]
nej. det är bättre att lägga till en krok inköp i reapi

**Comment by mforce95** [comment]
Nu Jag använder din plugin för att det, men det är inte i reapi

**Comment by theAsmodai** [comment]
Vaqtincha, du går till dick. Follow the rules of international communication or get out of here.

**Comment by Vaqtincha** [comment]
asmeday, oke.

**Comment by Vaqtincha** [comment]
Но пойми это тебе не ds.ru. Твои правила здесь не работают. Гидхаб - свободный сайт язык тут неважен и я пишу по теме. Если ты не знаешь мой язык это твои проблемы. Больше не пиши мне.

**Comment by ish12321** [comment]
Another option to fill but take their that much money to😁

**Comment by mforce95** [comment]
Now this future in the game.cfg :) Thanks.
```
// Refill amount of backpack ammo up to the max
// 0 - disabled (default behaviour)
// 1 - refill backpack ammo on player spawn
// 2 - refill backpack ammo on player spawn and on the purchase of the item
// 3 - refill backpack ammo on each weapon reload (NOTE: Useful for mods like DeathMatch, GunGame, ZombieMod etc.)
//
// Default value: "0"
mp_refill_bpammo_weapons 2
```
