### ISSUE TITLE
Hide ping from scoreboard

### ISSUE THREAD

**Issue by RauliTop** [s1lentq/ReGameDLL_CS#668]
I don't want to use ping faker because too many calls using FM_UpdateClientData.

Something like mp_scoreboard_showhealth, but for ping (mp_scoreboard_showping), will be perfect.

Is that can be possible?

**Comment by etojuice** [comment]
ping updates are handled by server library, not game library

**Comment by RauliTop** [comment]
> ping updates are handled by server library, not game library

So? Rehlds?

**Comment by RauliTop** [comment]
closed by https://github.com/dreamstalker/rehlds/issues/857
