### ISSUE TITLE
Crashing/Metamod Error

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#68]
I recently installed latest build of ReGameDLL_CS on my counter strike 1.6 server
It wasn't working so I then tried on my PC build to check what's problem 

I found that metamod was not loading any plugin :O 

Please help me

**Comment by s1lentq** [comment]
what version of metamod are you running?

**Comment by ish12321** [comment]
Sorry, 
It was actually problem with my installation xD 
But however when I install this on server it's crashing :'(

**Comment by spark512** [comment]
post `meta list` here please

**Comment by ish12321** [comment]
I don't have access to rcon 
However, plugins.ini is here : 
linux addons/amxmodx/dlls/amxmodx_mm_i386.so
;linux addons/dproto/dproto_i386.so
linux addons/whblocker/whblocker_mm_i386.so
;linux addons/vtc/vtc.so
linux addons/fake_detector/fakedetector_mm_i386.so
linux addons/reunion/reunion_mm_i386.so
linux addons/revoice/revoice_mm_i386.so

**Comment by Mistrick** [comment]
fakedetector don't work on ReHLDS

**Comment by ish12321** [comment]
I tested this before I enabled fakedetector :\

**Comment by ish12321** [comment]
And btw does this thing fixes the most common problem, bullet lag ?

**Comment by ish12321** [comment]
BUMP

**Comment by spark512** [comment]
amx version?
meta list?

**Comment by ish12321** [comment]
Already gave metamod.ini
I use amxmodx 1.8.2

**Comment by Mistrick** [comment]
Show output: meta version, amxx version, meta list, game version. Not text from ini.
When is server crash? If when player connecting to server then for amxx 1.8.2 you need fixed cstrike module.

**Comment by spark512** [comment]
@Mistrick exactly my thoughts.

@ish12321 You can find the fixed cstrike module in one of the threads about ReGameDLL_CS on the forums out there. Everyone has it public.

**Comment by ish12321** [comment]
Not when player connects
But as soon as I restart server :(

**Comment by ish12321** [comment]
Also sadly our gamepanel doesn't have console visible 
So it's not possible for me to enter command in console and also get output :\ 
I have Linux system

**Comment by spark512** [comment]
Here: https://www.sendspace.com/file/lmfv7b

Throw this in and tell me if it keeps crashing...

**Comment by ish12321** [comment]
You mean I install again regamedll_cs with this and check  ?

**Comment by ish12321** [comment]
Not solved :( 
Now 1 more question : Should I keep this new fixed module or old ? 
Also please help me

**Comment by ish12321** [comment]
Problem Exists 
Via RCON I got the meta list amxx list amxx version and meta version from my server after reverting back to normal dll as that new was making crash

Here are the results : 

AMXX LIST : 

Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running  
 [ 13] Scrolling Message       1.8.2       AMXX Dev Team     scrollmsg.amxx   running  
 [ 14] Info. Messages          1.8.2       AMXX Dev Team     imessage.amxx    running  

 [ 15] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
 [ 16] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running  
 [ 17] Nextmap Chooser         1.8.2       AMXX Dev Team     mapchooser.amxx  running  
 [ 18] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running  
 [ 19] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running  
 [ 20] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running  
 [ 21] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running  
 [ 22] Warcraft 3 Frozen Thro  10.0.32     RaZz              war3ft.amxx      debug    
 [ 23] D.I.C.E.                1.1         OciXCrom          dice_main.amxx   running  
 [ 24] D.I.C.E. Items          1.1         OciXCrom          dice_items_glob  running  
 [ 25] D.I.C.E. Items: Cstrik  1.1         OciXCrom          dice_items_cstr  running
25 plugins, 25 running

META LIST 

      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini  Start ANY  
 [ 2] <whblocker_mm_i  badf load  whblocker_mm_i38  v -       ini   -     -   
 [ 3] Reunion          RUN   -    reunion_mm_i386.  v0.1.67   ini  Start Never
 [ 4] <revoice_mm_i38  badf load  revoice_mm_i386.  v -       ini   -     -   
 [ 5] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
 [ 6] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2-d  pl1  ANY   ANY  
 [ 7] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl1  ANY   ANY  
 [ 8] SQLite           RUN   -    sqlite_amxx_i386  v1.8.2    pl1  ANY   ANY  
 [ 9] MySQL            RUN   -    mysql_amxx_i386.  v1.8.2    pl1  ANY   ANY  
 [10] Engine           RUN   -    engine_amxx_i386  v1.8.2    pl1  ANY   ANY  
 [11] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.2    pl1  ANY   ANY  
 [12] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl1  ANY   ANY  
12 plugin

AMXX VERSION 

AMX Mod X 1.8.2 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Feb 14 2013, 00:55:09
Build ID: 1.8.2 61:2ae84f7c0a97
Core mode: Core mode: JIT+ASM32


META VERSION 

Metamod v1.20  2013-02-16 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Feb 16 2013, 17:11:35 +0100 (optimized)

**Comment by spark512** [comment]
Yes, you need to run the fixed cstrike module in order ReGameDLL_CS to work with amxx 1.8.2.

Now tell me WHBlocker version.

**Comment by ish12321** [comment]
Actually on this new test server 
I copied the entire files but the dll's of metamod I didn't copied
I just copied plugins.ini
So badload is because of file not found :\

**Comment by Mistrick** [comment]
Did you try mm 1.21p37?

**Comment by spark512** [comment]
Why are you avoiding our questions? Tell me which WHBlocker version you are running?

Older versions conflict with regamedll and make the server crash...

**Comment by ish12321** [comment]
mm 1.21p37?
Is that new version of metamod

Already told whblocker is not running
It's dll files are not there
So file not found error comes and it doesn't works

**Comment by spark512** [comment]
yes mm 1.21p37 is the latest release, you should update it.

Make sure you use the latest whblocker 1.5.626 if you use regamedll, the previous versions have conflicts with regamedll and crash the server.

Also,
.dll = windows
.so = linux

**Comment by ish12321** [comment]
OK thanks
I'm not at home right now
Will check as soon as I reach home 😊

**Comment by ish12321** [comment]
Can you tell me where to get the latest metamod ?

**Comment by ish12321** [comment]
btw is official metamod not good that I should try metamod-p ?

**Comment by ish12321** [comment]
Off-topic but please can anyone tell that
If i use mp fraglimit 
And my server has resetscore amxmodx plugin
Will that mp fraglinit work correctly even if user reset his score to prevent reach the fraglimit
