### ISSUE TITLE
issue in mp_buytime it always sets to 9 seconds

### ISSUE THREAD

**Issue by indraraj26** [s1lentq/ReGameDLL_CS#69]
Linux centos
game version
ReGameDLL build: 16:58:28 Oct 11 2016 (0.2.156)
ReGameDLL API version 4.2
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/0006bac (s1lentq)

i set the mp_buytime "0.15" but still in game its shows 9 second you cant buy 
i m using bugfixed version of 194 zip
Thanks

**Comment by s1lentq** [comment]
[read here](https://github.com/s1lentq/ReGameDLL_CS/blob/master/dist/game.cfg#L11-L16)
mp_buytime (in minutes)

> 0.15 * 60 = 9 seconds

**Comment by indraraj26** [comment]
**s1lentq**  Thanks for quick response 
i thought it will be same calculation as in default mp_buytime

**Comment by WPMGPRoSToTeMa** [comment]
>> i thought it will be same calculation as in default mp_buytime 
It has the same calculation, but minimal time was decreased (old has minimum 0.25 = 15 seconds).

**Comment by indraraj26** [comment]
@PRoSToTeMa okay! :)
