### ISSUE TITLE
Autobuy doesn't buy primary weapon in TE team. And rebuy doesn't buy ammo too.

### ISSUE THREAD

**Issue by mforce95** [s1lentq/ReGameDLL_CS#7]
Autobuy doesn't buy primary weapon in TE team. And rebuy doesn't buy ammo too.

**Comment by s1lentq** [comment]
i need to make sure that you exactly are using regamedll?

**Comment by mforce95** [comment]
more bugs:
flash and smoke not working everytime.
Bomb planted and CT win.

(Now I've deleted all Re Things.)

**Comment by latinas** [comment]
Is this bug still relevant?

**Comment by IgnacioFDM** [comment]
I haven't been able to reproduce it, but maybe it's just me.

**Comment by mforce95** [comment]
now reinstalled all re things about 3 days ago and no problem.
