### ISSUE TITLE
New Request/Suggestion

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#70]
Like FRAGLIMIT can we have a roundlimit such that when XX rounds (total over) then the map changes

**Comment by Mistrick** [comment]
mp_maxrounds ?

**Comment by ish12321** [comment]
Yes please

**Comment by Mistrick** [comment]
This cvar already exists in original gamedll and regamedll.

**Comment by ish12321** [comment]
What if i want that if a team has got XX score then map change

**Comment by Mistrick** [comment]
mp_winlimit - already exists

**Comment by ish12321** [comment]
:O 
Cool !
Didn't ever knew about these :\
BtW also last question : is there something like roundsleft  ? 
This will help players know how much rounds left 
and something like roundslimit to know maxrounds limit :\

**Comment by ish12321** [comment]
Also is there any map vote or direct change ? :\

**Comment by Mistrick** [comment]
votemap - only console
direct change for who? server console or rcon - changelevel "mapname"
For output rounds left, etc you can create light amxx plugin.

**Comment by ish12321** [comment]
By direct change i mean to say that if i use maxrounds 
Then after the over of those round will there be a vote for map change or will map change directly to the next present in mapcycle

**Comment by Mistrick** [comment]
Without plugins gamedll only changes map to the next from mapcycle.

**Comment by ish12321** [comment]
If I have amxmodx installed

**Comment by ish12321** [comment]
`For output rounds left, etc you can create light amxx plugin.`
Actually thing's integrated directly in the engine is better 
As they have less chances of errors and bugs in the thing 

So please, if possible think of it :\ : (

**Comment by Mistrick** [comment]
Client doesn't support multilang message for winlimit, maxrounds, fraglimit. It supports only timeleft.
With amxx you can easy add multilang output for roundsleft, fragsleft. In gamedll can add only one lang.

**Comment by ish12321** [comment]
Okay.
