### ISSUE TITLE
ReCSDM 3.6 does not work on ReGameDLL 5.21.0.534

### ISSUE THREAD

**Issue by stambeto2006** [s1lentq/ReGameDLL_CS#705]
ReGameDLL 5.21.0.534 does not work (and with newer versions too) on ReCSDM 3.6 and causes the server to crash when there is a person on the server logged in!
With an older version of ReGameDLL 5.20.0.525 there are no problems with the operation of ReCSDM 3.6!

**Comment by Vaqtincha** [comment]
vice versa. "recsdm does not work with new regamedlls". so this is not a regame bug

**Comment by Vaqtincha** [comment]
the authors of recsdm abandoned the project. this (regamedll) project is also possibly abandoned. since no one even accepts my usual pr.

**Comment by stambeto2006** [comment]
@Vaqtincha Well, can't there be a way to work again as in the older versions?

**Comment by stambeto2006** [comment]
@wopox1337 @theAsmodai  @Adidasman1 @s1lentq   Can anyone help fix this problem?

**Comment by d3m37r4** [comment]
Where did you get idea that problem relates to regamedll?

**Comment by stambeto2006** [comment]
> Where did you get idea that problem relates to regamedll?

It is impossible to work on each version without any problems, and here in the last two versions it does not work! As you think it is not in it, before how it worked and now it is not, you say the problem and it can be used now! Because this type has more options and works much more stably!

**Comment by wopox1337** [comment]
> @Vaqtincha Well, can't there be a way to work again as in the older versions?

The source code of the ReCSDM project is open. It can be updated, updated to keep it working. I have no specific information from the author of ReCSDM. I can not say for sure if it will be updated.

This is not a problem with ReGameDLL.
https://bitbucket.org/Adidasman/recsdm/

**Comment by stambeto2006** [comment]
@wopox1337 Is there no way to make a decision on this mod until the author appears, because a lot of servers use this mod and if they update their server with the latest versions, they will not be able to use it?

**Comment by wopox1337** [comment]
Specifically, I don't have time to do it.

**Comment by francoromaniello** [comment]
Error message:
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
Line:
https://bitbucket.org/Adidasman/recsdm/src/ca9dbb007884f6cc06627f5570e7835dd4faaacc/csdm_natives.cpp#lines-265

**Comment by stambeto2006** [comment]
@francoromaniello Is there no way to contact the author of the plugin or to fix the fashion to use again?

**Comment by stambeto2006** [comment]
Will there be any development?

**Comment by wopox1337** [comment]
This is not a problem with ReGameDLL.
ReCSDM needs a fix.
