### ISSUE TITLE
mp_hullbounds_sets

### ISSUE THREAD

**Issue by teddiboy** [s1lentq/ReGameDLL_CS#706]
Hello, mp_hullbounds_sets "0" not working with windows system, please fix it :(
I use the newest REHLDS and REGAMEDLL on older versions, it doesn't work the same way. I compiled by visual studio and the same problem.

**Comment by etojuice** [comment]
change the setting in game_init.cfg

**Comment by teddiboy** [comment]
Yes i changed in game_init.cfg but it not working with Windows System. It only works with linux.

**Comment by justgo97** [comment]
Just a guess, In your liblist.gam file have both those lines commented or removed :

gamedll_linux "dlls/cs.so"
gamedll "dlls\mp.dll"

**Comment by teddiboy** [comment]
i use plugins so
gamedll "addons/metamod/dlls/metamod.dll"

**Comment by etojuice** [comment]
```
"game_version" is "5.21.0.540-dev"
ReHLDS version: 3.11.0.767-dev
```
I can confirm that the cvar is working

**Comment by justgo97** [comment]
> i use plugins so gamedll "addons/metamod/dlls/metamod.dll"

I know but sometimes having this line **gamedll "dlls\mp.dll"** in liblist.gam makes some functions not work correctly. like in here https://github.com/dreamstalker/rehlds/issues/382

**Comment by teddiboy** [comment]
Everything works fine without regamedll...
My versions;
![screen](https://user-images.githubusercontent.com/76532569/141481793-6864bc7c-664f-4feb-a305-6196a15124d2.png)

**Comment by etojuice** [comment]
original game library doesn't have that setting 🤣

**Comment by teddiboy** [comment]
Yes, I have regamedll turned on but mp_hullbounds_sets 0 does not work on Windows, which you do not understand?

**Comment by justgo97** [comment]
You should also install rehlds?

> Yes, I have regamedll turned on but mp_hullbounds_sets 0 does not work on Windows, which you do not understand?

**Comment by etojuice** [comment]
> 
> 
> Yes, I have regamedll turned on but mp_hullbounds_sets 0 does not work on Windows, which you do not understand?

it does work 😂
