### ISSUE TITLE
Precache ammo ID's using ammoIndex structure

### ISSUE THREAD

**Issue by Rafflesian** [s1lentq/ReGameDLL_CS#715]
My suggestion is precaching ammo ID's on the hardcoded const 'ammoIndex' instead of using _UTIL_PrecacheOtherWeapon._ and looping between pszAmmox ItemInfo in _AddAmmoNameToAmmoRegistry_
This was due to a headache recently figuring what was going on adding it's own ammo to the knife, besides, a lot of mods nowadays doesn't even use the C4 weapon as a base, so... I altered the pszAmmo1 info to C4, everything was going fine till I saw it was colliding with later precached ammo ID's (9mm and grenades).
I know it's only for 1 weapon but I think it would be great for some weapon mods

**ammoIndex const**
[https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/weapons.cpp#L189](url)
![image](https://user-images.githubusercontent.com/56321479/148350979-f956e9a6-3f5b-48d0-a401-b38cced071c3.png)

**Weapon precache**
[https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/weapons.cpp#L346](url)
![image](https://user-images.githubusercontent.com/56321479/148350669-113405ee-4a51-48db-8970-f34a09d98f80.png)

**AddAmmoNameTo...**
[https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/weapons.cpp#L230](url)
![image](https://user-images.githubusercontent.com/56321479/148351338-d0c07feb-efbe-4e3d-ab20-e6bab925bf5c.png)

**Server Logs**
![image](https://user-images.githubusercontent.com/56321479/148351432-5337a693-b7bd-40ca-a26a-8f776381f717.png)

**Comment by RauliTop** [comment]
Good addition for add more possibilities to the game.

**Comment by Rafflesian** [comment]
Now that reapi can precache new ammo, it's no longer an issue.
