### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#73]
Hello 
We have edited CS-Warzone and added reHLDS and reGAMEDLL_CS
Now the problem is that when we use it's "New Game" to play offline with bots the game crashes/stucks 
How to fix this please help us 

You can see our modified CS here https://www.oldskoolgaming.in/csdownload/

Regards,
Ish Chhabra
OSG Team

**Comment by Mistrick** [comment]
rehlds doesn't work with listen server(new game).

**Comment by ish12321** [comment]
:O 
Any way to make that possible  ? :( 
As reHLDS I think fixes many bugs ? :\ 
Which may help players in playing offline ? :\

**Comment by ish12321** [comment]
Solved ! Problem was not with reHLDS. Fixed :)
