### ISSUE TITLE
Bullet Lag

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#74]
Is bullet lag/animation skipping which is well known bug related to reGAMEDLL_CS
Please can someone fix it ??
I found it to be one of the most big problem of Counter-Strike 1.6 which caused and is causing all players to leave CS1.6 
Even if not related to this please someone fix it

**Comment by theAsmodai** [comment]
Did you using edited gamemenu to enter the server?

**Comment by ish12321** [comment]
Yes.., 
When I experienced it I had a self edited gamemenu for removing 'Join Random Server' and adding directly my server shortcuts there in my non-steam :)

**Comment by theAsmodai** [comment]
It's a clientside problem.

**Comment by ish12321** [comment]
Any way to fix this clientside problem ? 
By editing client files ?

**Comment by spark512** [comment]
No, because they dont have access to client files. Only valve has the power to make a change in client's files and force an update to all clients. And we all know how valve cares about goldsrc games..

Valve's ignorance is what created the ReHLDS project in the first place...

**Comment by ish12321** [comment]
I don't know much about these things but what about making such a new project like reHLDS to fix this :) :P :D

**Comment by ish12321** [comment]
> 

> 

>

**Comment by WPMGPRoSToTeMa** [comment]
Are you talking about first shoot?

**Comment by ish12321** [comment]
No
I'm talking about this bullet-lag/animation skipping when we fire gun continuously [not 2-3 but continuous many shots]
It can be specially seen in MACHINE GUN as it experiences the most I think
However, ak47/m4a1 also gets it 

https://www.youtube.com/watch?v=6RxPCoQY570

**Comment by WPMGPRoSToTeMa** [comment]
@ish12321 have you this problem on 5787 build?

**Comment by ish12321** [comment]
I'm using latest steam CS currently 
Before that used OSG-CS oldskoolgaming.in/csdownload/
Which is based on WARZONE CS

Had/have problem with all :(

**Comment by WPMGPRoSToTeMa** [comment]
I mean server build.

**Comment by ish12321** [comment]
Server has latest build with regamedll_cs and rehlds 
On server gladly now a days it occurs very rarely and only with MACHINE GUN
It has reduced by a lot but still to complete remove it would be better

**Comment by ish12321** [comment]
However most server also don't use regamedll so any way to play on those

**Comment by ish12321** [comment]
BUMP

**Comment by lespaul64** [comment]
This is known bug after February 2013 updates. In 2013 i had a server too a windows server. My friends and other players keep telling me that my server is so laggy. They compare to other server and i make some investigation, i join other server and check the server build it was an old build. So i tried to use older mp.dll from build 4554 and put in server then people can play smoothly. So it's clear now that mp.dll build >= February 2013 has this issue. Valve has changed something related to firing method in 2013. I believe the current 6153/6153 beta still has this issue to. Because it tried both of it (mp.dll used on server) the result still the same. It would be great if reHLDS team can reverse engineering the mp.dll/cs_i386.so from build 4554/5758. And compare the firing code that valve changed.

**Comment by lespaul64** [comment]
Maybe this will help your team to fix this issue.
Taken from Nagist cssdk -- https://github.com/Nagist/cs16nd/blob/cb03c59eaf076b0b4bb2eb8b6a05179651d7763c/dlls/weapons.cpp#L621

Your regamedll weapon.cpp -- https://github.com/s1lentq/ReGameDLL_CS/blob/8f5b702cb16ea8840b994130a53abd96fe18c95b/regamedll/dlls/weapons.cpp#L885

Compare the code, as you can see in Nagist cssdk there are no m_flLastFireTime. This cssdk based on build 4554, if i'm not wrong, longtime already not chitchat with him.

**Comment by WPMGPRoSToTeMa** [comment]
GameDLL from 6153 beta is fixed.

**Comment by ish12321** [comment]
o.O 
But I have regamedll_cs installed on my server still rarely bullet lag occurs :(

**Comment by ish12321** [comment]
However, my net is good but not alls

**Comment by lespaul64** [comment]
They need to completely remove the new hle creep calculation. Use the old next attack calculation. Try and see the result.

**Comment by ish12321** [comment]
Please someone fix it
