### ISSUE TITLE
Не работает sv_enablebunnyhopping

### ISSUE THREAD

**Issue by insellium** [s1lentq/ReGameDLL_CS#745]
При sv_enablebunnyhopping 1, так и не получается сделать распрыжку из-за снижающейся скорости.

**Comment by wopox1337** [comment]
Read desc please: https://github.com/s1lentq/ReGameDLL_CS/pull/686

**Comment by insellium** [comment]
Окей, жаль.
А хотелось бы сделать распрыжку как в Quake, не скачивая сторонние плагины.

**Comment by fl0werD** [comment]
Check the second cvar in description.

**Comment by insellium** [comment]
I checked. It's not working.
https://youtu.be/PyAmok-fZns

**Comment by Vaqtincha** [comment]
@fl0werD блаблабла

**Comment by insellium** [comment]
@ShadowsAdi not working
