### ISSUE TITLE
Bug on de_storm (pickable ak47 on the crate of one of the bombsites)

### ISSUE THREAD

**Issue by Vladislav4KZ** [s1lentq/ReGameDLL_CS#746]
ReGameDLL version 5.21.0.546
https://youtu.be/ooHM9fXPaXA

Behaviour of the original GameDLL (ak47 is not picked up)
https://youtu.be/zScN8foGpuA

**Comment by StevenKal** [comment]
Bug is on the original game DLL. ReGameDLL_CS fixes the pick up. This is cool to find a free AK!
The AK47 you can pick up is an "armoury_entity" (same kind of entity you have on the ground on iceworld maps & cie).
