### ISSUE TITLE
sv_cheats * while playing game will cause crash

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [s1lentq/ReGameDLL_CS#762]
![image](https://user-images.githubusercontent.com/41063376/184480163-748f01f4-3dcd-4aa4-abde-6aa921a40b5a.png)

When game is started, entering sv_cheats 0/1 will crash the game
is it related to ReGameDLL ?
i know this command has no effect while game is started, no matter if it has no effect, but it should not kill cs 1.6 process
my CS 1.6 version is GSClient with latest ReGameDLL

**Comment by s1lentq** [comment]
This crash have only in this $hit client which you mentioned, but also have in Steam version which already [fixed](https://github.com/ValveSoftware/halflife/issues/2785), so this issue actually is not related ReGameDLL

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
I found no newer no-steam client that contains no malware
