### ISSUE TITLE
[Question] Compile mp.dll included REGAMEDLL_ADD and REGAMEDLL_FIXES.

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#81]
I wonder is JDK mandatory to compile this project?
Can i compile directly ReGameDLL.sln using VS2013?

I tried but it has many option, which one included REGAMEDLL_ADD and REGAMEDLL_FIXES?
Image:
https://s30.postimg.org/pntdwjsxd/regamedll.png

**Comment by s1lentq** [comment]
for build on Windows you can use VisualStudio with configuration's Release MP/Debug MP (also include REGAMEDLL_ADD and REGAMEDLL_FIXES)

**Comment by lespaul64** [comment]
Thanks for the respond, so the jdk is optional.

**Comment by lespaul64** [comment]
One more question, why my compiled binary size using Release MP is bigger than bugfixed binary provided in http://nexus.rehlds.org/nexus/content/repositories/regamedll-dev/regamedll/regamedll/ ?
Mine is about 1.4MB
dev is about 1.28MB

**Comment by theAsmodai** [comment]
This can be caused by different versions of compilers or by difference of compilation options.

**Comment by Vaqtincha** [comment]
Project>Properties>C/C++>Code Generation>Runtime Library
multi-threaded (/MT)
change to 
multi-threaded (/MD)

P.s there will be problems
http://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt

**Comment by lespaul64** [comment]
I have a problem when trying to compile Release MP with current repository.
I'm using Visual Studio 2013.

Error:
```
Error	1	error LNK2001: unresolved external symbol _A_strcmp	K:\xx\xx\ReGameDLL_CS-master\msvc\airtank.obj	ReGameDLL
Error	2	error LNK2001: unresolved external symbol _A_strlen	K:\xx\xx\ReGameDLL_CS-master\msvc\animation.obj	ReGameDLL
Error	3	error LNK2001: unresolved external symbol _A_memcpy	K:\xx\xx\ReGameDLL_CS-master\msvc\animation.obj	ReGameDLL
Error	4	error LNK2001: unresolved external symbol _A_strcat	K:\xx\xx\ReGameDLL_CS-master\msvc\cs_bot_chatter.obj	ReGameDLL
Error	5	error LNK2001: unresolved external symbol _A_strcpy	K:\xx\xx\ReGameDLL_CS-master\msvc\cs_bot_chatter.obj	ReGameDLL
Error	6	error LNK2001: unresolved external symbol _A_memset	K:\xx\xx\ReGameDLL_CS-master\msvc\buttons.obj	ReGameDLL
Error	7	error LNK2001: unresolved external symbol _A_strstr	K:\xx\xx\ReGameDLL_CS-master\msvc\client.obj	ReGameDLL
Error	8	error LNK2001: unresolved external symbol _A_memmove	K:\xx\xx\ReGameDLL_CS-master\msvc\hookchains_impl.obj	ReGameDLL
Error	9	error LNK1120: 8 unresolved externals	K:\xx\xx\ReGameDLL_CS-master\msvc\Release MP\mp.dll	ReGameDLL

```

**Comment by theAsmodai** [comment]
Project properties -> Linker -> Input -> Additional Dependencies:
libacof32.lib

**Comment by lespaul64** [comment]
@theAsmodai 
Thank you, it worked.

@Vaqtincha 
Nice, the size is smaller now. Thanks you.
