### ISSUE TITLE
gamedll file need

### ISSUE THREAD

**Issue by Escap3d** [s1lentq/ReGameDLL_CS#818]
@[justgo97](https://github.com/justgo97)justgo97
opened
https://github.com/s1lentq/ReGameDLL_CS/pull/817
[justgo97:ftrace-knife](https://github.com/justgo97/ReGameDLL_CS/tree/ftrace-knife)

this update linux have not included plzz give me

**Comment by wopox1337** [comment]
![image](https://user-images.githubusercontent.com/18553678/229305764-c1a9abd1-ad29-4c0c-9ac9-8a7ebd50470f.png)
check actions and download it
