### ISSUE TITLE
ReSemiClip

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#82]
Please can anyone update ReSemiClip for ReAPI version 5 [not latest]
The latest version I don't need as for that many other plugins aren't updated so I'm not willing for it

**Comment by WPMGPRoSToTeMa** [comment]
ReSemiclip doesn't use ReAPI.

**Comment by ish12321** [comment]
That's plugin's not working with the nov1. version of regamedll_cs :\ 
Can you tell me how to make it work ? 



Also ......, 
btW 
Can someone update these 

 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.73   ini   Start Never
 [ 3] Revoice          RUN   -    revoice_mm_i386.  v0.1.25   ini   Start Never
 [ 4] Rechecker        RUN   -    rechecker_mm_i38  v2.1      ini   Chlvl ANY  
 [ 5] ReSemiclip       fail load  resemiclip_mm_i3  v2.3.7    ini   Chlvl ANY

For the latest regamedll_cs and rehlds so that I can update :)

**Comment by Mistrick** [comment]
https://github.com/s1lentq/ReGameDLL_CS/issues/79
