### ISSUE TITLE
[Feature Request] Enable bunny hopping just like in CS1.3

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#83]
In csgo valve already enable bunny hopping controlled by these cvars:
```
• sv_enablebunnyhopping -- enable bunnyhoping.
• sv_autobunnyhopping -- auto jump while holding jump key (SPACE button).
```

I tried to edit the sourcecode but no luck :( i'm not good enough for this stuff.

CS1.3 bhopping style:
```
• No speed limitation.
• No landing speed penalty (no slowdown).
```

**Comment by MAXBURAOT** [comment]
@lespaul64 i guess client.dll handles the bunnyhopping function not the mp.dll. and they need to enable also the "_special" command for alias binding.
it would be great if they add this feature. sv_bhop 1/0
