### ISSUE TITLE
Regarding the execution priority of common parameters in server.cfg and game.cfg

### ISSUE THREAD

**Issue by tarimren-admin** [s1lentq/ReGameDLL_CS#833]
First of all, I apologize for my poor English. Some of my expressions may not be appropriate.
My question is: When there are common parameters in both server.cfg and game.cfg, such as sv_alltalk, and server.cfg sets it to 0 while game.cfg sets it to 3, which one will the server execute?

**Comment by abecee** [comment]
> First of all, I apologize for my poor English. Some of my expressions may not be appropriate.
> My question is: When there are common parameters in both server.cfg and game.cfg, such as sv_alltalk, and server.cfg sets it to 0 while game.cfg sets it to 3, which one will the server execute?

Hi. Server.cfg is executed when you start the server then game.cfg and also game.cfg is executed everytime when you change the map. Just check the console and you will see there.
