### ISSUE TITLE
CZ: Career Tasks Fix with Orpheu

### ISSUE THREAD

**Issue by WaLkZa** [s1lentq/ReGameDLL_CS#835]
I found a fix for CZ with a detailed description, so maybe it would be a good idea someone to add it directly into ReGameDLL.
https://forums.alliedmods.net/showthread.php?p=2742088

**Comment by dystopm** [comment]
> I found a fix for CZ with a detailed description, so maybe it would be a good idea someone to add it directly into ReGameDLL. https://forums.alliedmods.net/showthread.php?p=2742088

I've just done a little research and pull request. Take a look.
