### ISSUE TITLE
[Bug] mp_forcerespawn not working on zbot.

### ISSUE THREAD

**Issue by lespaul64** [s1lentq/ReGameDLL_CS#84]
```
// Players will automatically respawn when killed.
// 0  - disabled
// >0 - time delay to respawn
//
// Default value: "0"
mp_forcerespawn 3
```

I run server with -bots parameter to enable zbot on server. I set mp_forcerespawn 3 to play deathmatch, but only human able to respawn.

I'm using current bugfixed mp.dll.

**Comment by lespaul64** [comment]
Still no respond about this? This is regamedll bug, yapb bot can respawn without any problem.

**Comment by lespaul64** [comment]
This is a bug report not a request. Try yourself. Enable zbot and then set mp_forcerespawn 1. See whether zbot can respawn or not.

**Comment by In-line** [comment]
Was fixed.
