### ISSUE TITLE
When player team is changed via cs_set_user_team player loses HUD.

### ISSUE THREAD

**Issue by abhishekdeshkar** [s1lentq/ReGameDLL_CS#85]
Hello,

When I transfer all players to Spectator and then if I use cs_set_user_team() to set their teams, they don't get crosshair and HUD info of HP,Armor etc. Also Some players can still play while they are in spec. :/

**Comment by s1lentq** [comment]
@abhishekdeshkar 
You can give test a plugin with cs_set_user_team to reproduce it?

**Comment by In-line** [comment]
@abhishekdeshkar, `cs_get-user_team` is very bad, don't use it unless it's fixed. Use reapi.
Related: s1lentq/reapi#81
