### ISSUE TITLE
Suggest adding parameters for Tactical Pause and Team Surrender functionality

### ISSUE THREAD

**Issue by tarimren-admin** [s1lentq/ReGameDLL_CS#860]
Tactical Pause and Team Surrender features are very useful for game modes, it is suggested to add them。

**Comment by dystopm** [comment]
I mean, I do not think everybody knows what those terms mean, can you please elaborate on that? :)

**Comment by tarimren-admin** [comment]
First of all, I apologize for my poor English. Some of my expressions may not be appropriate.
Thank you very much for providing prompt feedback.
“Tactical Pause“：Tactical pause is similar to the pause feature in CS:GO, initiated by CT or T through a voting process. Once approved, the game will be paused at the start of the next round, allowing team members to communicate tactics. The default duration is approximately 60 seconds.
Similar code link on the AMX Mod X forum: https://forums.alliedmods.net/showthread.php?t=339686
“ Team Surrender ”：For example, if there is a significant power imbalance between the two sides in a match and it lacks any enjoyable gameplay, one side may propose a surrender request. If the surrender is approved, the match can be ended prematurely.

**Comment by wopox1337** [comment]
Now try to apply your idea for the standard mode in CS 1.6. It's useless without a competitive mode. Implement your "your FASTCUP" with AMXX and be happy.
