### ISSUE TITLE
weapons zoom speed

### ISSUE THREAD

**Issue by scripting6** [s1lentq/ReGameDLL_CS#863]
Hey
Previously in old HLDS rigs if you used zoom in AWP the speed would drop to 150 instead of 210 when walking, the player would walk slower
Today I see that it doesn't work and even through a mod I can't fix it

**Comment by scripting6** [comment]
in scout and rifles too...
scout need to be 220 speed with zoom

**Comment by scripting6** [comment]
fixed, its was plugin

**Comment by abecee** [comment]
> fixed, its was plugin

And the plugin is?
