### ISSUE TITLE
[Error]  slowdown after jumping - dmg when falling 

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#869]
seems since https://github.com/s1lentq/ReGameDLL_CS/commit/1e49d947927e7f6f2fd70d8398e4a9519a34450a players get a massive slowndown after landing when just  jumping.
also  falling from a height, which normaly triggers no dmg, now creates dmg.
server has `mp_falldamage 1` configured for ages.

**Comment by fred0r** [comment]
@wopox1337 
is [this](https://github.com/wopox1337/ReGameDLL_CS/tree/refactor/ff_damage) a potential fix forthat misbehaviour?

**Comment by dystopm** [comment]
> @wopox1337 is [this](https://github.com/wopox1337/ReGameDLL_CS/tree/refactor/ff_damage) a potential fix for that misbehaviour?

It is just a code refactory of what is actually done now, get the last binary from Actions

**Comment by fred0r** [comment]
@dystopm 
thx - but theres no cs.so inside that linux32.zip - thats why i compiled locally.

**Comment by fred0r** [comment]
thx - just understood  that i need to copy+rename the cs-gcc.so from linux32.zip.
