### ISSUE TITLE
Accuracy Fix.

### ISSUE THREAD

**Issue by abhishekdeshkar** [s1lentq/ReGameDLL_CS#88]
Hello,

Recently lots of changes have been made in Regame DLL. Have you guys fixed accuracy issue of some guns  like AK47 ? I still have to use accuracy fix plugin :/ Can you please merge that in ReGameDLL ?

Thanks!

**Comment by abhishekdeshkar** [comment]
@s1lentq : Can you please look into it ? :)

**Comment by S0m3Th1nG-AwFul** [comment]
Actually he is talking about accuracy fixes which implemented in this plugin:
https://forums.alliedmods.net/showthread.php?p=1549133

**Comment by In-line** [comment]
Same as #35
