### ISSUE TITLE
`IsInWorld()` should use `sv_maxvelocity` cvar value instead of hardcoded number

### ISSUE THREAD

**Issue by Nord1cWarr1or** [s1lentq/ReGameDLL_CS#887]
https://github.com/s1lentq/ReGameDLL_CS/blob/96e2121c4504d26376d655f036d32e2fd967e4e5/regamedll/dlls/cbase.cpp#L869

**Comment by Nord1cWarr1or** [comment]
https://github.com/s1lentq/ReGameDLL_CS/blob/96e2121c4504d26376d655f036d32e2fd967e4e5/regamedll/dlls/cbase.cpp#L869

**Comment by StevenKal** [comment]
Yes, and will allow us (if we increase "sv_maxvelocity") to fix grenades removed if we throw them faster then 2000 units/sec (case with speedhack plugin or super fast LongJump tuned).

**Comment by dystopm** [comment]
Seems reasonable

**Comment by Nord1cWarr1or** [comment]
> Yes, and will allow us (if we increase "sv_maxvelocity") to fix grenades removed if we throw them faster then 2000 units/sec (case with speedhack plugin or super fast LongJump tuned).

It will not be a complete solution to the problem
