### ISSUE TITLE
Limit Teams

### ISSUE THREAD

**Issue by ish12321** [s1lentq/ReGameDLL_CS#89]
Any way to limit Ct and T teams to XX numbers
So that if teams are filled with that much members all others are forced to join spectator 

@s1lentq @theAsmodai is it possible to make this thing possible as an addition feature in RegameDLL_CS

**Comment by theAsmodai** [comment]
Youn need to write amxx plugin for it.

**Comment by ish12321** [comment]
Could you write 1 for me please :( :\ 
As I won't be able to do so

**Comment by ish12321** [comment]
Hey please
