### ISSUE TITLE
REGAMEDLL - REAPI - BUG - rg_fire_bullets3

### ISSUE THREAD

**Issue by wilianmaique** [s1lentq/ReGameDLL_CS#892]
If you use 'rg_fire_bullets3' the bullets do not go through the 'cycler_sprite' class, as for the standard cs bullets, it works normally.

Follow video: [bug reapi - regamedll](https://youtu.be/JVllgZxyptA)

**Comment by dystopm** [comment]
Code implementation at least? We need to figure the details in the script

**Comment by dystopm** [comment]
You cannot describe a behaviour as wrong without providing context, that screenshot is not enough as we may need to test it by ourselves. It may differ depending on parameters. By the way, if you want to  replicate CS shooting, both attacker and inflictor are player's index, no weaponent index is used, check it and test
