### ISSUE TITLE
sv_allow_shaders

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#903]
todays update of the official server introduced `sv_allow_shaders`

https://steamdb.info/patchnotes/12830899/

**Comment by s1lentq** [comment]
This CVar does not related to the gamedll part, even to the server (hlds) part too, only listenserver.
This is implemented very weird, it's better to wait until they make it work properly.

**Comment by fred0r** [comment]
properly?

**Comment by s1lentq** [comment]
@fred0r [yep](https://github.com/ValveSoftware/halflife/issues/3547#issuecomment-1833216870)
