### ISSUE TITLE
RegameDLL not found...

### ISSUE THREAD

**Issue by abecee** [s1lentq/ReGameDLL_CS#911]
Hi.
I also put this new version of regameDLL, and now I get this in the console.
[ReAPI]: Interface CCSEntity API version 'CSENTITY_API_INTERFACE_VERSION002' not found.
L 01/01/2024 - 17:23:17: [ReAPI] ReGameDll: isn't available

**Comment by dystopm** [comment]
You updated Regamedll, you must also update ReAPI :)
https://github.com/s1lentq/reapi/actions/runs/7181474921 - download linux32 or win32 depending on your server's OS

**Comment by abecee** [comment]
> You updated Regamedll, you must also update ReAPI :) https://github.com/s1lentq/reapi/actions/runs/7181474921 - download linux32 or win32 depending on your server's OS

Ty :D
