### ISSUE TITLE
Add a new sv_alltalk mode.

### ISSUE THREAD

**Issue by HODAKdev** [s1lentq/ReGameDLL_CS#915]
Hi, I would like to add a new talk mode.
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/82084934/4f2cb4ad-549f-478e-8d04-592e9f531b8d)
These are the others.
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/82084934/8c031123-e7ed-4815-9128-7412f98be2e8)
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/82084934/cd64f156-3446-4965-b958-7c17191a3d99)
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/82084934/6f3e3532-c659-474e-9a54-0bb4d48c0598)
Here is the code.
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/82084934/3473e09c-ce28-4258-9d71-598adc31719c)
Link to the code.
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/multiplay_gamerules.cpp

**Comment by dystopm** [comment]
Are you aware that ReGameDLL does not provides admin privilege system? It's (mostly) an AMXX feature. It's ambiguous to define an "admin" flag at gamedll level. I do not know if you are aware also of ReAPI and the possibility to hook CanPlayerHearPlayer function to write your own logic. Consider this done
