### ISSUE TITLE
FireBullets3. punchangle for SHIELD

### ISSUE THREAD

**Issue by NoobWithCheats** [s1lentq/ReGameDLL_CS#918]
https://github.com/s1lentq/ReGameDLL_CS/blob/15df1a9cf2e6a9afe284556a23af83d007926cb6/regamedll/dlls/cbase.cpp#L1452-L1455

`pEntity->pev->punchangle.x = 4; ?`

**Comment by dystopm** [comment]
Just checked a decompiled version of the original CS, and it behaves like that:

![image](https://github.com/s1lentq/ReGameDLL_CS/assets/3503046/8a14a9fe-f8bd-4fa3-9411-beb595041a2d)

It may break some "expected" behaviour. I always felt the excesive punchangle when getting hit. By just looking at, it will directly force you to have -4 units of X punchangle, and the other side has no boundaries. I'll offer a PR
