### ISSUE TITLE
Why is `pev->gravity` different for grenades?

### ISSUE THREAD

**Issue by wopox1337** [s1lentq/ReGameDLL_CS#922]
SMOKEGRENADE: https://github.com/s1lentq/ReGameDLL_CS/blob/193c1ed52ad7af69a0e7f4e22e09f8cc16555635/regamedll/dlls/ggrenade.cpp#L1307
FLASHBANG: https://github.com/s1lentq/ReGameDLL_CS/blob/193c1ed52ad7af69a0e7f4e22e09f8cc16555635/regamedll/dlls/ggrenade.cpp#L977
HEGRENADE:
https://github.com/s1lentq/ReGameDLL_CS/blob/193c1ed52ad7af69a0e7f4e22e09f8cc16555635/regamedll/dlls/ggrenade.cpp#L932

HLDS HEGRENADE:
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/18553678/1b4c5acc-5733-4d70-a4dc-7d38814c7e67)

Why **0.55** only for HEGRENADE ? Is this a bug? Or was it designed that way?

P.S: Just in case I looked up how it works in [CS:S](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/cstrike/basecsgrenade_projectile.h#L52), [CS:GO](https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/shared/cstrike15/basecsgrenade_projectile.h#L66), there gravity is the same for all grenades. (0,4)

I don't even want to fix it. I would like to speculate, first. 😏

**Comment by StevenKal** [comment]
Probably devs wanted to make them a little "heavier" in-game, must check if real life ones are, but normaly they should be, as they can contain different projectiles inside which can make them heavier.

**Comment by wopox1337** [comment]
@StevenKal This game is not about reallism at all, **at all**. I suppose referencing the experience of newer iterations of game development. But, I doubt anyone needs or would want or use these edits.

**Comment by dystopm** [comment]
It was designed that way, 25 years ago lmao

**Comment by Vaqtincha** [comment]
> HLDS HEGRENADE

😂

**Comment by Maxi605** [comment]
> @StevenKal This game is not about reallism at all, **at all**. I suppose referencing the experience of newer iterations of game development. But, I doubt anyone needs or would want or use these edits.

People are used to it and it doesn't really cause any issue as it is, i don't know if a change would be necessary.

**Comment by wopox1337** [comment]
Guys! Thanks everyone for the discussion, I totally agree with everyone that "habitual" behavior should not be changed in this case.
