### ISSUE TITLE
Assertion Failed: m_toggle_state == TS_AT_TOP; local compiling; [SOLVED]

### ISSUE THREAD

**Issue by hellmoss** [s1lentq/ReGameDLL_CS#926]
![image](https://github.com/s1lentq/ReGameDLL_CS/assets/20055714/845e441a-f6a1-4206-9e0c-eb65f5454ac6)

I have modified my regamedll and I update it on every new release. After the final update this comes out as soon as I launch my server. I thought I might have made some mistakes while porting my modified code. Then I decided to simply download clean regamedll source and compile it to see if error will come out, well it did come out. If I put the already compiled regamedll from the release, everything is ok. This happens after a local compilation without any errors.

Solved by commenting:

![image](https://github.com/s1lentq/ReGameDLL_CS/assets/20055714/4a22e02b-4359-4248-9271-42095421a408)

**Comment by molamaster999** [comment]
I have the same problem as you, but it seems you already solved it. So, thank you for the solution man. 👍
