### ISSUE TITLE
!suggestion Garnade.

### ISSUE THREAD

**Issue by Escap3d** [s1lentq/ReGameDLL_CS#959]
Is it possible that when we throw any grenade, the name of the player along with the name of the grenade is also shown? Like I mentioned here, it also shows in CS2 which grenade was thrown with the player's name.

Escape* : Fire in the hole! HE
Escape* : Fire in the hole! Flash
Escape* : Fire in the hole! Smoke

**Comment by StevenKal** [comment]
A plugin exists, named "Descriptive 'Fire in the hole!'" (in case you not aware of).
