### ISSUE TITLE
Podbots can't join a team after connecting

### ISSUE THREAD

**Issue by souvikdas95** [s1lentq/ReGameDLL_CS#96]
Build: 5.1.0.170-dev

PODBots created bots can't / don't join team after connecting to Server. They remain in Spectator while CSBots are able to join team.

**Comment by Freeman-AM** [comment]
This bug i still active. If you can look around to fix it, that would be appreciated.

**Comment by In-line** [comment]
@Freeman-AM It seems that bug is in Podbots. Try to use Yapb.

**Comment by MAXBURAOT** [comment]
@souvikdas95 Bots can join, so this case can consider closed lol
Here are the bots i tested with REHLDS/HLDS/ReGameDLL_CS/ReUnion all is working below mentioned

-MetaMod
CSBotv1.5
HPB Bot v4.0 
PLBot v0.99 
PodBotMM v3.0.23 
RealBot r3073 Beta 
YaPB Bot v2.8.4766 
JoeBot v1.6.5.3
-Non-MetaMod
EPODBot v5.4 
IvPBot v1.1.2 

![3](https://user-images.githubusercontent.com/33173384/33237696-35ed3a5e-d2b5-11e7-89a8-13b4529a5c44.png)
![4](https://user-images.githubusercontent.com/33173384/33237697-3630e3c6-d2b5-11e7-8a2a-c8e6d7427845.png)
![5](https://user-images.githubusercontent.com/33173384/33237698-36717d46-d2b5-11e7-8005-c4dacedc6bf6.png)
![2](https://user-images.githubusercontent.com/33173384/33237718-cd80b300-d2b5-11e7-8a33-ddce7d4eddb2.png)
![4 2](https://user-images.githubusercontent.com/33173384/33237719-cdc10dd8-d2b5-11e7-8fb1-f81f6b29573d.png)

**Comment by In-line** [comment]
Closing as non active.
