### ISSUE TITLE
player can throw flash, start  defuse, throw second flash and continues defusing?!

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#964]
player throws flash, start  defuse, throws second flash and continues defusing at the same point he threwed  the second flash - without interrupting.
(maybe he got hit once after starting defuse and before throwing second flash)

using 'latest everything' on linux.

**Comment by fred0r** [comment]
nvm

**Comment by dystopm** [comment]
lmao

**Comment by fred0r** [comment]
was rly stange, but i checked the my client demo and the hltv demo of the same occasion now..... the  hltv doesnt contain the 'defuse-bar' and on my client-demo its looks 'normal', but just ingame it didnt?!
