### ISSUE TITLE
linux compile .so file not inclued...

### ISSUE THREAD

**Issue by Escap3d** [s1lentq/ReGameDLL_CS#969]
The cs.so file for RegameDLL isn't compiled. If anyone has the latest compiled file for the Action Build, please share it. Thanks.

**Comment by Nord1cWarr1or** [comment]
> The cs.so file for RegameDLL isn't compiled

?

**Comment by Escap3d** [comment]
> > The cs.so file for RegameDLL isn't compiled
> 
> 
> 
> ?

Ye check on new action build i am can not find.. u have plzz share it new link cs.so

**Comment by Nord1cWarr1or** [comment]
![изображение](https://github.com/s1lentq/ReGameDLL_CS/assets/47604048/c40e2bc4-b454-4f6a-9398-ee7ae0b4b4fc)

**Comment by Escap3d** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/47604048/341009023-c40e2bc4-b454-4f6a-9398-ee7ae0b4b4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI0ODAsIm5iZiI6MTcxODgwMjE4MCwicGF0aCI6Ii80NzYwNDA0OC8zNDEwMDkwMjMtYzQwZTJiYzQtYjQ1NC00ZjZhLTkzOTgtZWU3YWUwYjRiNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTc5YmQ5OWFjMWUyZTQyYWNmMWEyMWVjNzgxMDkzYWQ4NGM3OTdmNWMzNjRmNWM3M2I2NjZhMGQ2ZTQ1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNcyrh0T2_T3ncUIoDspXgWUYoYcA1VFC7z5ynPuHLc)

U mean to i am change the name of this file cs.so???

**Comment by Nord1cWarr1or** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/47604048/341009023-c40e2bc4-b454-4f6a-9398-ee7ae0b4b4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MDI0ODAsIm5iZiI6MTcxODgwMjE4MCwicGF0aCI6Ii80NzYwNDA0OC8zNDEwMDkwMjMtYzQwZTJiYzQtYjQ1NC00ZjZhLTkzOTgtZWU3YWUwYjRiNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDEzMDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTc5YmQ5OWFjMWUyZTQyYWNmMWEyMWVjNzgxMDkzYWQ4NGM3OTdmNWMzNjRmNWM3M2I2NjZhMGQ2ZTQ1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNcyrh0T2_T3ncUIoDspXgWUYoYcA1VFC7z5ynPuHLc)
> 
> U mean to i am change the name of this file cs.so???

+

**Comment by SmileYzn** [comment]
Jesus Christ :facepalm:

**Comment by Escap3d** [comment]
> Jesus Christ 🤦

Bro u focus on matchbot issues 😟
