### ISSUE TITLE
Непонятные линии

### ISSUE THREAD

**Issue by Vaqtincha** [s1lentq/ReGameDLL_CS#97]
Не буду каждый раз открывать new issue за мелочи. Оставлю здесь все что найду.

Один из них.
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/player.cpp#L7735
это как ? wtf

**Comment by Vaqtincha** [comment]
еще
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/player.cpp#L1587
уже есть же в 
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/player.cpp#L1697

**Comment by theAsmodai** [comment]
http://www.ozon.ru/?context=search&text=%f3%f7%e5%e1%ed%e8%ea+%e0%ed%e3%eb%e8%e9%f1%ea%ee%e3%ee&store=1,0
http://www.ozon.ru/?context=search&text=%f3%f7%e5%e1%ed%e8%ea+c%2b%2b&store=1%2c0&group=div_book
