### ISSUE TITLE
KickBack function

### ISSUE THREAD

**Issue by NoobWithCheats** [s1lentq/ReGameDLL_CS#972]
Our behavior is changing for Y, but not for X. I think we need to check the behavior of X.
https://github.com/s1lentq/ReGameDLL_CS/blob/a94c7bd728a2b2b80b016ee86f3310459e872e0d/regamedll/dlls/weapons.cpp#L729-L749

**Comment by dystopm** [comment]
So what is this

https://github.com/s1lentq/ReGameDLL_CS/blob/a94c7bd728a2b2b80b016ee86f3310459e872e0d/regamedll/dlls/weapons.cpp#L729-L734

(?)

**Comment by dystopm** [comment]
> In a hurry, I missed a couple of words xD. Y changes in both directions, but for X it changes in one direction.

 Well, then close the issue
