### ISSUE TITLE
Strange message

### ISSUE THREAD

**Issue by laimiukas3** [s1lentq/ReGameDLL_CS#973]
Hello gentlemen, I received the following message when the server start why ?

`[AF] ReHLDS API minor version mismatch; expected at least 14, real 13
[AF] Please update the ReHLDS up to a minor version API >= 14
[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26
[AF] Please update the ReGameDLL up to a minor version API >= 27

game version
ReGameDLL version: 5.26.0.668-dev
version
ReHLDS version: 3.13.0.788-dev`

**Comment by s1lentq** [comment]
Where does it come from? What is the `[AF]` prefix?
I think you should contact the author of this module for older versions that are compatible with release build or you can update rehlds/regamedll up to dev-builds

**Comment by laimiukas3** [comment]
> Where does it come from? What is the `[AF]` prefix? I think you should contact the author of this module for older versions that are compatible with release build or you can update rehlds/regamedll up to dev-builds

Thanks for the reply. I found this message sent by https://github.com/SmileYzn/AccuracyFix
